// Autogenerated by the Generate Class from Layout plugin, version 0.3.0
// Layout file: UI/layouts/Menus/LoadingScreen/ScenarioLoadingScreen.layout

class SCR_ScenarioLoadingScreenWidgets
{
	static const ResourceName s_sLayout = "{4C8B29889444BDA3}UI/layouts/Menus/LoadingScreen/ScenarioLoadingScreen.layout";
	ResourceName GetLayout() { return s_sLayout; }

	OverlayWidget m_wBackground;

	OverlayWidget m_wContent;

	HorizontalLayoutWidget m_wSpinnerGroup;

	FrameWidget m_wCrossplayWarning;

	FrameWidget m_wModdedWarning;

	FrameWidget m_wSpinner;

	ImageWidget m_wReforgerLogo;

	FrameWidget m_wPhotoGroup;

	ImageWidget m_wLoadingImage;

	VerticalLayoutWidget m_wTextGroup;

	TextWidget m_wTitle;

	TextWidget m_wAuthor;

	RichTextWidget m_wDescription;

	OverlayWidget m_wProgressGroup;

	ImageWidget m_wProgressBarFill;

	FrameWidget m_wProgressBarSpace;

	HorizontalLayoutWidget m_wHintGroup;

	RichTextWidget m_wHintText;

	ScaleWidget m_wPreloadContent;

	OverlayWidget m_wContentOverlay;

	ImageWidget m_wBlackOverlay;

	bool Init(Widget root)
	{
		m_wBackground = OverlayWidget.Cast(root.FindWidget("m_wBackground"));

		m_wContent = OverlayWidget.Cast(root.FindWidget("FullHDFrame.m_wContent"));

		m_wSpinnerGroup = HorizontalLayoutWidget.Cast(root.FindWidget("FullHDFrame.m_wContent.m_wSpinnerGroup"));

		m_wCrossplayWarning = FrameWidget.Cast(root.FindWidget("FullHDFrame.m_wContent.m_wSpinnerGroup.m_wCrossplayWarning"));

		m_wModdedWarning = FrameWidget.Cast(root.FindWidget("FullHDFrame.m_wContent.m_wSpinnerGroup.m_wModdedWarning"));

		m_wSpinner = FrameWidget.Cast(root.FindWidget("FullHDFrame.m_wContent.m_wSpinnerGroup.m_wSpinner"));

		m_wReforgerLogo = ImageWidget.Cast(root.FindWidget("FullHDFrame.m_wContent.m_wReforgerLogo"));

		m_wPhotoGroup = FrameWidget.Cast(root.FindWidget("FullHDFrame.m_wContent.m_wPhotoGroup"));

		m_wLoadingImage = ImageWidget.Cast(root.FindWidget("FullHDFrame.m_wContent.m_wPhotoGroup.Photo.Scale0.m_wLoadingImage"));

		m_wTextGroup = VerticalLayoutWidget.Cast(root.FindWidget("FullHDFrame.m_wContent.m_wTextGroup"));

		m_wTitle = TextWidget.Cast(root.FindWidget("FullHDFrame.m_wContent.m_wTextGroup.m_wTitle"));

		m_wAuthor = TextWidget.Cast(root.FindWidget("FullHDFrame.m_wContent.m_wTextGroup.m_wAuthor"));

		m_wDescription = RichTextWidget.Cast(root.FindWidget("FullHDFrame.m_wContent.m_wTextGroup.m_wDescription"));

		m_wProgressGroup = OverlayWidget.Cast(root.FindWidget("FullHDFrame.m_wContent.m_wProgressGroup"));

		m_wProgressBarFill = ImageWidget.Cast(root.FindWidget("FullHDFrame.m_wContent.m_wProgressGroup.HorizontalLayout0.m_wProgressBarFill"));

		m_wProgressBarSpace = FrameWidget.Cast(root.FindWidget("FullHDFrame.m_wContent.m_wProgressGroup.HorizontalLayout0.m_wProgressBarSpace"));

		m_wHintGroup = HorizontalLayoutWidget.Cast(root.FindWidget("FullHDFrame.m_wContent.m_wHintGroup"));

		m_wHintText = RichTextWidget.Cast(root.FindWidget("FullHDFrame.m_wContent.m_wHintGroup.m_wHintText"));

		m_wPreloadContent = ScaleWidget.Cast(root.FindWidget("FullHDFrame.m_wPreloadContent"));

		m_wContentOverlay = OverlayWidget.Cast(root.FindWidget("m_wContentOverlay"));

		m_wBlackOverlay = ImageWidget.Cast(root.FindWidget("m_wBlackOverlay"));

		return true;
	}
}
