// Autogenerated by the Generate Class from Layout plugin v0.5.1
// Layout file: UI/layouts/HUD/InteractionSystem/ContextBasicInteractionBlip.layout
class SCR_ContextBasicInteractionBlipWidgets
{
	protected static const ResourceName LAYOUT = "{BF5FA7B21D658280}UI/layouts/HUD/InteractionSystem/ContextBasicInteractionBlip.layout";

	OverlayWidget m_wOverlayBackground;
	ImageWidget m_wBackgroundShadowInner;
	ImageWidget m_wBackground;
	ImageWidget m_wBackgroundShadowOuter;
	ImageWidget m_wBackgroundOuter;
	ImageWidget m_wIconGlow;
	ImageWidget m_wIcon;

	//------------------------------------------------------------------------------------------------
	bool Init(notnull Widget root)
	{
		m_wOverlayBackground = OverlayWidget.Cast(root.FindWidget("m_wOverlayBackground"));
		m_wBackgroundShadowInner = ImageWidget.Cast(root.FindWidget("m_wOverlayBackground.m_wBackgroundShadowInner"));
		m_wBackground = ImageWidget.Cast(root.FindWidget("m_wOverlayBackground.m_wBackground"));
		m_wBackgroundShadowOuter = ImageWidget.Cast(root.FindWidget("m_wOverlayBackground.m_wBackgroundShadowOuter"));
		m_wBackgroundOuter = ImageWidget.Cast(root.FindWidget("m_wOverlayBackground.m_wBackgroundOuter"));
		m_wIconGlow = ImageWidget.Cast(root.FindWidget("m_wOverlayBackground.IconSize.Overlay_Icon.m_wIconGlow"));
		m_wIcon = ImageWidget.Cast(root.FindWidget("m_wOverlayBackground.IconSize.Overlay_Icon.m_wIcon"));

		return true;
	}

	//------------------------------------------------------------------------------------------------
	ResourceName GetLayout()
	{
		return LAYOUT;
	}
}
