// Autogenerated by the Generate Class from Layout plugin v0.5.1
// Layout file: UI/layouts/HUD/WeaponInfo/WeaponInfo_MultiWeaponTurret.layout
class SCR_WeaponInfo_MultiWeaponTurretWidgets
{
	protected static const ResourceName LAYOUT = "{1FE821A29ACEA938}UI/layouts/HUD/WeaponInfo/WeaponInfo_MultiWeaponTurret.layout";

	VerticalLayoutWidget m_wWeaponInfoPanel;
	HorizontalLayoutWidget m_wOptics;
	RichTextWidget m_wOpticsText;
	HorizontalLayoutWidget m_wZeroing;
	RichTextWidget m_wZeroingText;
	HorizontalLayoutWidget m_wAmmoType;
	OverlayWidget m_wAmmoType_Sniper;
	OverlayWidget m_wAmmoType_Incendiary;
	OverlayWidget m_wAmmoType_Smoke;
	OverlayWidget m_wAmmoType_Frag;
	OverlayWidget m_wAmmoType_HEAT;
	OverlayWidget m_wAmmoType_HE;
	OverlayWidget m_wAmmoType_HEDP;
	OverlayWidget m_wAmmoType_AP;
	OverlayWidget m_wAmmoType_FMJ;
	OverlayWidget m_wAmmoType_Tracer;
	OverlayWidget m_wAmmoType_Illumination;
	HorizontalLayoutWidget m_wMagazinesHolder;
	OverlayWidget m_wFiremode;
	ImageWidget m_wFiremodeGlow;
	ImageWidget m_wFiremodeIcon;
	HorizontalLayoutWidget m_wWeaponNameAndCaliber;
	RichTextWidget m_wWeaponName;
	RichTextWidget m_wProjectileQuantityText;

	//------------------------------------------------------------------------------------------------
	bool Init(notnull Widget root)
	{
		m_wWeaponInfoPanel = VerticalLayoutWidget.Cast(root.FindWidget("m_WeaponInfoPanel"));
		m_wOptics = HorizontalLayoutWidget.Cast(root.FindWidget("m_WeaponInfoPanel.m_Optics"));
		m_wOpticsText = RichTextWidget.Cast(root.FindWidget("m_WeaponInfoPanel.m_Optics.m_OpticsText"));
		m_wZeroing = HorizontalLayoutWidget.Cast(root.FindWidget("m_WeaponInfoPanel.m_Zeroing"));
		m_wZeroingText = RichTextWidget.Cast(root.FindWidget("m_WeaponInfoPanel.m_Zeroing.m_ZeroingText"));
		m_wAmmoType = HorizontalLayoutWidget.Cast(root.FindWidget("m_WeaponInfoPanel.m_AmmoType"));
		m_wAmmoType_Sniper = OverlayWidget.Cast(root.FindWidget("m_WeaponInfoPanel.m_AmmoType.m_AmmoType_Sniper"));
		m_wAmmoType_Incendiary = OverlayWidget.Cast(root.FindWidget("m_WeaponInfoPanel.m_AmmoType.m_AmmoType_Incendiary"));
		m_wAmmoType_Smoke = OverlayWidget.Cast(root.FindWidget("m_WeaponInfoPanel.m_AmmoType.m_AmmoType_Smoke"));
		m_wAmmoType_Frag = OverlayWidget.Cast(root.FindWidget("m_WeaponInfoPanel.m_AmmoType.m_AmmoType_Frag"));
		m_wAmmoType_HEAT = OverlayWidget.Cast(root.FindWidget("m_WeaponInfoPanel.m_AmmoType.m_AmmoType_HEAT"));
		m_wAmmoType_HE = OverlayWidget.Cast(root.FindWidget("m_WeaponInfoPanel.m_AmmoType.m_AmmoType_HE"));
		m_wAmmoType_HEDP = OverlayWidget.Cast(root.FindWidget("m_WeaponInfoPanel.m_AmmoType.m_AmmoType_HEDP"));
		m_wAmmoType_AP = OverlayWidget.Cast(root.FindWidget("m_WeaponInfoPanel.m_AmmoType.m_AmmoType_AP"));
		m_wAmmoType_FMJ = OverlayWidget.Cast(root.FindWidget("m_WeaponInfoPanel.m_AmmoType.m_AmmoType_FMJ"));
		m_wAmmoType_Tracer = OverlayWidget.Cast(root.FindWidget("m_WeaponInfoPanel.m_AmmoType.m_AmmoType_Tracer"));
		m_wAmmoType_Illumination = OverlayWidget.Cast(root.FindWidget("m_WeaponInfoPanel.m_AmmoType.m_AmmoType_Illumination"));
		m_wMagazinesHolder = HorizontalLayoutWidget.Cast(root.FindWidget("m_WeaponInfoPanel.m_MagazinesHolder"));
		m_wFiremode = OverlayWidget.Cast(root.FindWidget("m_WeaponInfoPanel.m_MagazinesHolder.m_Firemode"));
		m_wFiremodeGlow = ImageWidget.Cast(root.FindWidget("m_WeaponInfoPanel.m_MagazinesHolder.m_Firemode.m_FiremodeGlow"));
		m_wFiremodeIcon = ImageWidget.Cast(root.FindWidget("m_WeaponInfoPanel.m_MagazinesHolder.m_Firemode.m_FiremodeIcon"));
		m_wWeaponNameAndCaliber = HorizontalLayoutWidget.Cast(root.FindWidget("m_WeaponInfoPanel.m_WeaponNameAndCaliber"));
		m_wWeaponName = RichTextWidget.Cast(root.FindWidget("m_WeaponInfoPanel.m_WeaponNameAndCaliber.m_WeaponName"));
		m_wProjectileQuantityText = RichTextWidget.Cast(root.FindWidget("m_WeaponInfoPanel.m_MagazinesHolder.m_ProjectileQuantityText"));

		return true;
	}

	//------------------------------------------------------------------------------------------------
	ResourceName GetLayout()
	{
		return LAYOUT;
	}
}
