// Autogenerated by the Generate Class from Layout plugin v0.5.0
// Layout file: UI/layouts/HUD/WeaponInfo/WeaponInfo.layout
class SCR_WeaponInfoWidgets
{
	protected static const ResourceName LAYOUT = "{8170DE93810F928A}UI/layouts/HUD/WeaponInfo/WeaponInfo.layout";

	VerticalLayoutWidget m_wWeaponInfoPanel;
	HorizontalLayoutWidget m_wOptics;
	RichTextWidget m_wOpticsText;
	HorizontalLayoutWidget m_wZeroing;
	RichTextWidget m_wZeroingText;
	HorizontalLayoutWidget m_wAmmoType;
	RichTextWidget m_wAmmoTypeText;
	OverlayWidget m_wAmmoType_Sniper;
	OverlayWidget m_wAmmoType_Incendiary;
	OverlayWidget m_wAmmoType_Smoke;
	OverlayWidget m_wAmmoType_Frag;
	OverlayWidget m_wAmmoType_HEAT;
	OverlayWidget m_wAmmoType_HE;
	OverlayWidget m_wAmmoType_AP;
	OverlayWidget m_wAmmoType_FMJ;
	OverlayWidget m_wAmmoType_Tracer;
	OverlayWidget m_wAmmoType_Illumination;
	HorizontalLayoutWidget m_wMain;
	OverlayWidget m_wFiremode;
	ImageWidget m_wFiremodeGlow;
	ImageWidget m_wFiremodeIcon;
	OverlayWidget m_wMagazineIndicator;
	ImageWidget m_wMagazineGlow;
	ImageWidget m_wMagazineBackground;
	ImageWidget m_wMagazineOutline;
	ImageWidget m_wMagazineProgress;
	ImageWidget m_wReloadBackground;
	ImageWidget m_wReloadOutline;
	SizeLayoutWidget m_wMagCount;
	RichTextWidget m_wMagCountText;
	HorizontalLayoutWidget m_wWeaponNameAndCaliber;
	RichTextWidget m_wCaliber;
	RichTextWidget m_wWeaponName;

	//------------------------------------------------------------------------------------------------
	bool Init(Widget root)
	{
		m_wWeaponInfoPanel = VerticalLayoutWidget.Cast(root.FindAnyWidget("m_WeaponInfoPanel"));
		m_wOptics = HorizontalLayoutWidget.Cast(root.FindAnyWidget("m_Optics"));
		m_wOpticsText = RichTextWidget.Cast(root.FindAnyWidget("m_OpticsText"));
		m_wZeroing = HorizontalLayoutWidget.Cast(root.FindAnyWidget("m_Zeroing"));
		m_wZeroingText = RichTextWidget.Cast(root.FindAnyWidget("m_ZeroingText"));
		m_wAmmoType = HorizontalLayoutWidget.Cast(root.FindAnyWidget("m_AmmoType"));
		m_wAmmoTypeText = RichTextWidget.Cast(root.FindAnyWidget("m_AmmoTypeText"));
		m_wAmmoType_Sniper = OverlayWidget.Cast(root.FindAnyWidget("m_AmmoType_Sniper"));
		m_wAmmoType_Incendiary = OverlayWidget.Cast(root.FindAnyWidget("m_AmmoType_Incendiary"));
		m_wAmmoType_Smoke = OverlayWidget.Cast(root.FindAnyWidget("m_AmmoType_Smoke"));
		m_wAmmoType_Frag = OverlayWidget.Cast(root.FindAnyWidget("m_AmmoType_Frag"));
		m_wAmmoType_HEAT = OverlayWidget.Cast(root.FindAnyWidget("m_AmmoType_HEAT"));
		m_wAmmoType_HE = OverlayWidget.Cast(root.FindAnyWidget("m_AmmoType_HE"));
		m_wAmmoType_AP = OverlayWidget.Cast(root.FindAnyWidget("m_AmmoType_AP"));
		m_wAmmoType_FMJ = OverlayWidget.Cast(root.FindAnyWidget("m_AmmoType_FMJ"));
		m_wAmmoType_Tracer = OverlayWidget.Cast(root.FindAnyWidget("m_AmmoType_Tracer"));
		m_wAmmoType_Illumination = OverlayWidget.Cast(root.FindAnyWidget("m_AmmoType_Illumination"));
		m_wMain = HorizontalLayoutWidget.Cast(root.FindAnyWidget("m_Main"));
		m_wFiremode = OverlayWidget.Cast(root.FindAnyWidget("m_Firemode"));
		m_wFiremodeGlow = ImageWidget.Cast(root.FindAnyWidget("m_FiremodeGlow"));
		m_wFiremodeIcon = ImageWidget.Cast(root.FindAnyWidget("m_FiremodeIcon"));
		m_wMagazineIndicator = OverlayWidget.Cast(root.FindAnyWidget("m_MagazineIndicator"));
		m_wMagazineGlow = ImageWidget.Cast(root.FindAnyWidget("m_MagazineGlow"));
		m_wMagazineBackground = ImageWidget.Cast(root.FindAnyWidget("m_MagazineBackground"));
		m_wMagazineOutline = ImageWidget.Cast(root.FindAnyWidget("m_MagazineOutline"));
		m_wMagazineProgress = ImageWidget.Cast(root.FindAnyWidget("m_MagazineProgress"));
		m_wReloadBackground = ImageWidget.Cast(root.FindAnyWidget("m_ReloadBackground"));
		m_wReloadOutline = ImageWidget.Cast(root.FindAnyWidget("m_ReloadOutline"));
		m_wMagCount = SizeLayoutWidget.Cast(root.FindAnyWidget("m_MagCount"));
		m_wMagCountText = RichTextWidget.Cast(root.FindAnyWidget("m_MagCountText"));
		m_wWeaponNameAndCaliber = HorizontalLayoutWidget.Cast(root.FindAnyWidget("m_WeaponNameAndCaliber"));
		m_wCaliber = RichTextWidget.Cast(root.FindAnyWidget("m_Caliber"));
		m_wWeaponName = RichTextWidget.Cast(root.FindAnyWidget("m_WeaponName"));

		return true;
	}

	//------------------------------------------------------------------------------------------------
	ResourceName GetLayout()
	{
		return LAYOUT;
	}
}
