// Autogenerated by the Generate Class from Layout plugin v0.5.1
// Layout file: UI/layouts/Menus/ContentBrowser/DetailsMenu/ContentBrowserDetails_OverviewSubMenu.layout
class SCR_ContentBrowserDetails_OverviewSubMenuWidgets
{
	protected static const ResourceName LAYOUT = "{18E59BE07F4DB110}UI/layouts/Menus/ContentBrowser/DetailsMenu/ContentBrowserDetails_OverviewSubMenu.layout";

	ScrollLayoutWidget m_wMainContentScroll;
	SCR_GamepadScrollComponent m_MainContentScrollComponent;

	VerticalLayoutWidget m_wMainContent;

	VerticalLayoutWidget m_wGallery;
	SCR_ContentBrowserDetails_GalleryComponent m_GalleryComponent;

	SizeLayoutWidget m_wImagesHeightSize;

	ButtonWidget m_wNextButton;
	SCR_ModularButtonComponent m_NextButtonComponent;


	ButtonWidget m_wPrevButton;
	SCR_ModularButtonComponent m_PrevButtonComponent;


	ButtonWidget m_wSpinBox;
	SCR_SpinBoxComponent m_SpinBoxComponent0;
	SCR_ModularButtonComponent m_SpinBoxComponent1;

	VerticalLayoutWidget m_wMainSection;

	ButtonWidget m_wEnableButton;
	SCR_ModularButtonComponent m_EnableButtonComponent;


	ButtonWidget m_wPrimaryActionButton;
	SCR_ModularButtonComponent m_PrimaryActionButtonComponent0;
	SCR_DynamicIconComponent m_PrimaryActionButtonComponent1;
	SCR_CoreMenuHeaderComponent m_PrimaryActionButtonComponent2;


	ButtonWidget m_wRepairButton;
	SCR_ModularButtonComponent m_RepairButtonComponent0;
	SCR_DynamicIconComponent m_RepairButtonComponent1;
	SCR_CoreMenuHeaderComponent m_RepairButtonComponent2;


	ButtonWidget m_wFavoriteButton;
	SCR_ModularButtonComponent m_FavoriteButtonComponent0;
	SCR_DynamicIconComponent m_FavoriteButtonComponent1;
	SCR_CoreMenuHeaderComponent m_FavoriteButtonComponent2;


	ButtonWidget m_wVoteUpButton;
	SCR_ModularButtonComponent m_VoteUpButtonComponent0;
	SCR_DynamicIconComponent m_VoteUpButtonComponent1;
	SCR_CoreMenuHeaderComponent m_VoteUpButtonComponent2;


	ButtonWidget m_wVoteDownButton;
	SCR_ModularButtonComponent m_VoteDownButtonComponent0;
	SCR_DynamicIconComponent m_VoteDownButtonComponent1;
	SCR_CoreMenuHeaderComponent m_VoteDownButtonComponent2;


	ButtonWidget m_wReportButton;
	SCR_ModularButtonComponent m_ReportButtonComponent0;
	SCR_DynamicIconComponent m_ReportButtonComponent1;
	SCR_CoreMenuHeaderComponent m_ReportButtonComponent2;


	ButtonWidget m_wLicenses;
	SCR_ModularButtonComponent m_LicensesComponent0;
	SCR_DynamicIconComponent m_LicensesComponent1;
	SCR_CoreMenuHeaderComponent m_LicensesComponent2;


	ButtonWidget m_wDependencies;
	SCR_ModularButtonComponent m_DependenciesComponent0;
	SCR_DynamicIconComponent m_DependenciesComponent1;
	SCR_CoreMenuHeaderComponent m_DependenciesComponent2;


	ButtonWidget m_wDependent;
	SCR_ModularButtonComponent m_DependentComponent0;
	SCR_DynamicIconComponent m_DependentComponent1;
	SCR_CoreMenuHeaderComponent m_DependentComponent2;


	ButtonWidget m_wVersionComboBox;
	SCR_ComboBoxComponent m_VersionComboBoxComponent0;
	SCR_ModularButtonComponent m_VersionComboBoxComponent1;


	ButtonWidget m_wDeleteButton;
	SCR_ModularButtonComponent m_DeleteButtonComponent0;
	SCR_DynamicIconComponent m_DeleteButtonComponent1;
	SCR_CoreMenuHeaderComponent m_DeleteButtonComponent2;


	OverlayWidget m_wAddonSize;
	SCR_DynamicIconComponent m_AddonSizeComponent0;
	SCR_CoreMenuHeaderComponent m_AddonSizeComponent1;

	HorizontalLayoutWidget m_wVersionUpdateHorizontalLayout;
	TextWidget m_wUpdateVersion;
	TextWidget m_wCurrentVersion;
	ImageWidget m_wCurrentVersionIcon;
	HorizontalLayoutWidget m_wLastPlayedHorizontalLayout;
	TextWidget m_wLastPlayed;
	HorizontalLayoutWidget m_wLastDownloadedHorizontalLayout;
	TextWidget m_wLastDownloaded;

	OverlayWidget m_wBackendSource;
	SCR_DynamicIconComponent m_BackendSourceComponent0;
	SCR_CoreMenuHeaderComponent m_BackendSourceComponent1;

	OverlayWidget m_wDownloadProgressBarOverlay;
	ProgressBarWidget m_wDownloadProgressBar;

	ButtonWidget m_wDescriptionHoverDetector;
	SCR_EventHandlerComponent m_DescriptionHoverDetectorComponent;

	TextWidget m_wSummaryText;
	TextWidget m_wDescriptionText;
	VerticalLayoutWidget m_wScenarioSection;
	VerticalLayoutWidget m_wScenariosList;

	OverlayWidget m_wScenarioDetailsPanel;
	SCR_ScenarioDetailsPanelComponent m_ScenarioDetailsPanelComponent;


	OverlayWidget m_wAddonDetailsPanel;
	SCR_AddonDetailsPanelComponent m_AddonDetailsPanelComponent;


	//------------------------------------------------------------------------------------------------
	bool Init(notnull Widget root)
	{
		m_wMainContentScroll = ScrollLayoutWidget.Cast(root.FindWidget("MainPanel.VerticalLayout0.Content.m_MainContentScroll"));
		m_MainContentScrollComponent = SCR_GamepadScrollComponent.Cast(m_wMainContentScroll.FindHandler(SCR_GamepadScrollComponent));

		m_wMainContent = VerticalLayoutWidget.Cast(root.FindWidget("MainPanel.VerticalLayout0.Content.m_MainContentScroll.m_MainContent"));

		m_wGallery = VerticalLayoutWidget.Cast(root.FindWidget("MainPanel.VerticalLayout0.Content.m_MainContentScroll.m_MainContent.m_Gallery"));
		m_GalleryComponent = SCR_ContentBrowserDetails_GalleryComponent.Cast(m_wGallery.FindHandler(SCR_ContentBrowserDetails_GalleryComponent));

		m_wImagesHeightSize = SizeLayoutWidget.Cast(root.FindWidget("MainPanel.VerticalLayout0.Content.m_MainContentScroll.m_MainContent.m_Gallery.m_ImagesHeightSize"));

		m_wNextButton = ButtonWidget.Cast(root.FindWidget("MainPanel.VerticalLayout0.Content.m_MainContentScroll.m_MainContent.m_Gallery.m_ImagesHeightSize.Overlay.ArrowsOverlay.m_NextButton"));
		m_NextButtonComponent = SCR_ModularButtonComponent.Cast(m_wNextButton.FindHandler(SCR_ModularButtonComponent));


		m_wPrevButton = ButtonWidget.Cast(root.FindWidget("MainPanel.VerticalLayout0.Content.m_MainContentScroll.m_MainContent.m_Gallery.m_ImagesHeightSize.Overlay.ArrowsOverlay.m_PrevButton"));
		m_PrevButtonComponent = SCR_ModularButtonComponent.Cast(m_wPrevButton.FindHandler(SCR_ModularButtonComponent));


		m_wSpinBox = ButtonWidget.Cast(root.FindWidget("MainPanel.VerticalLayout0.Content.m_MainContentScroll.m_MainContent.m_Gallery.m_SpinBox"));
		m_SpinBoxComponent0 = SCR_SpinBoxComponent.Cast(m_wSpinBox.FindHandler(SCR_SpinBoxComponent));
		m_SpinBoxComponent1 = SCR_ModularButtonComponent.Cast(m_wSpinBox.FindHandler(SCR_ModularButtonComponent));

		m_wMainSection = VerticalLayoutWidget.Cast(root.FindWidget("MainPanel.VerticalLayout0.Content.m_MainContentScroll.m_MainContent.m_MainSection"));

		m_wEnableButton = ButtonWidget.Cast(root.FindWidget("MainPanel.VerticalLayout0.Content.m_MainContentScroll.m_MainContent.m_MainSection.ButtonsArea.ButtonsMainHorizontalLayout.Buttons.m_EnableButton"));
		m_EnableButtonComponent = SCR_ModularButtonComponent.Cast(m_wEnableButton.FindHandler(SCR_ModularButtonComponent));


		m_wPrimaryActionButton = ButtonWidget.Cast(root.FindWidget("MainPanel.VerticalLayout0.Content.m_MainContentScroll.m_MainContent.m_MainSection.ButtonsArea.ButtonsMainHorizontalLayout.Buttons.m_PrimaryActionButton"));
		m_PrimaryActionButtonComponent0 = SCR_ModularButtonComponent.Cast(m_wPrimaryActionButton.FindHandler(SCR_ModularButtonComponent));
		m_PrimaryActionButtonComponent1 = SCR_DynamicIconComponent.Cast(m_wPrimaryActionButton.FindHandler(SCR_DynamicIconComponent));
		m_PrimaryActionButtonComponent2 = SCR_CoreMenuHeaderComponent.Cast(m_wPrimaryActionButton.FindHandler(SCR_CoreMenuHeaderComponent));


		m_wRepairButton = ButtonWidget.Cast(root.FindWidget("MainPanel.VerticalLayout0.Content.m_MainContentScroll.m_MainContent.m_MainSection.ButtonsArea.ButtonsMainHorizontalLayout.Buttons.m_RepairButton"));
		m_RepairButtonComponent0 = SCR_ModularButtonComponent.Cast(m_wRepairButton.FindHandler(SCR_ModularButtonComponent));
		m_RepairButtonComponent1 = SCR_DynamicIconComponent.Cast(m_wRepairButton.FindHandler(SCR_DynamicIconComponent));
		m_RepairButtonComponent2 = SCR_CoreMenuHeaderComponent.Cast(m_wRepairButton.FindHandler(SCR_CoreMenuHeaderComponent));


		m_wFavoriteButton = ButtonWidget.Cast(root.FindWidget("MainPanel.VerticalLayout0.Content.m_MainContentScroll.m_MainContent.m_MainSection.ButtonsArea.ButtonsMainHorizontalLayout.Buttons.m_FavoriteButton"));
		m_FavoriteButtonComponent0 = SCR_ModularButtonComponent.Cast(m_wFavoriteButton.FindHandler(SCR_ModularButtonComponent));
		m_FavoriteButtonComponent1 = SCR_DynamicIconComponent.Cast(m_wFavoriteButton.FindHandler(SCR_DynamicIconComponent));
		m_FavoriteButtonComponent2 = SCR_CoreMenuHeaderComponent.Cast(m_wFavoriteButton.FindHandler(SCR_CoreMenuHeaderComponent));


		m_wVoteUpButton = ButtonWidget.Cast(root.FindWidget("MainPanel.VerticalLayout0.Content.m_MainContentScroll.m_MainContent.m_MainSection.ButtonsArea.ButtonsMainHorizontalLayout.Buttons.m_VoteUpButton"));
		m_VoteUpButtonComponent0 = SCR_ModularButtonComponent.Cast(m_wVoteUpButton.FindHandler(SCR_ModularButtonComponent));
		m_VoteUpButtonComponent1 = SCR_DynamicIconComponent.Cast(m_wVoteUpButton.FindHandler(SCR_DynamicIconComponent));
		m_VoteUpButtonComponent2 = SCR_CoreMenuHeaderComponent.Cast(m_wVoteUpButton.FindHandler(SCR_CoreMenuHeaderComponent));


		m_wVoteDownButton = ButtonWidget.Cast(root.FindWidget("MainPanel.VerticalLayout0.Content.m_MainContentScroll.m_MainContent.m_MainSection.ButtonsArea.ButtonsMainHorizontalLayout.Buttons.m_VoteDownButton"));
		m_VoteDownButtonComponent0 = SCR_ModularButtonComponent.Cast(m_wVoteDownButton.FindHandler(SCR_ModularButtonComponent));
		m_VoteDownButtonComponent1 = SCR_DynamicIconComponent.Cast(m_wVoteDownButton.FindHandler(SCR_DynamicIconComponent));
		m_VoteDownButtonComponent2 = SCR_CoreMenuHeaderComponent.Cast(m_wVoteDownButton.FindHandler(SCR_CoreMenuHeaderComponent));


		m_wReportButton = ButtonWidget.Cast(root.FindWidget("MainPanel.VerticalLayout0.Content.m_MainContentScroll.m_MainContent.m_MainSection.ButtonsArea.ButtonsMainHorizontalLayout.Buttons.m_ReportButton"));
		m_ReportButtonComponent0 = SCR_ModularButtonComponent.Cast(m_wReportButton.FindHandler(SCR_ModularButtonComponent));
		m_ReportButtonComponent1 = SCR_DynamicIconComponent.Cast(m_wReportButton.FindHandler(SCR_DynamicIconComponent));
		m_ReportButtonComponent2 = SCR_CoreMenuHeaderComponent.Cast(m_wReportButton.FindHandler(SCR_CoreMenuHeaderComponent));


		m_wLicenses = ButtonWidget.Cast(root.FindWidget("MainPanel.VerticalLayout0.Content.m_MainContentScroll.m_MainContent.m_MainSection.ButtonsArea.ButtonsMainHorizontalLayout.Buttons.m_Licenses"));
		m_LicensesComponent0 = SCR_ModularButtonComponent.Cast(m_wLicenses.FindHandler(SCR_ModularButtonComponent));
		m_LicensesComponent1 = SCR_DynamicIconComponent.Cast(m_wLicenses.FindHandler(SCR_DynamicIconComponent));
		m_LicensesComponent2 = SCR_CoreMenuHeaderComponent.Cast(m_wLicenses.FindHandler(SCR_CoreMenuHeaderComponent));


		m_wDependencies = ButtonWidget.Cast(root.FindWidget("MainPanel.VerticalLayout0.Content.m_MainContentScroll.m_MainContent.m_MainSection.ButtonsArea.ButtonsMainHorizontalLayout.Buttons.m_wDependencies"));
		m_DependenciesComponent0 = SCR_ModularButtonComponent.Cast(m_wDependencies.FindHandler(SCR_ModularButtonComponent));
		m_DependenciesComponent1 = SCR_DynamicIconComponent.Cast(m_wDependencies.FindHandler(SCR_DynamicIconComponent));
		m_DependenciesComponent2 = SCR_CoreMenuHeaderComponent.Cast(m_wDependencies.FindHandler(SCR_CoreMenuHeaderComponent));


		m_wDependent = ButtonWidget.Cast(root.FindWidget("MainPanel.VerticalLayout0.Content.m_MainContentScroll.m_MainContent.m_MainSection.ButtonsArea.ButtonsMainHorizontalLayout.Buttons.m_wDependent"));
		m_DependentComponent0 = SCR_ModularButtonComponent.Cast(m_wDependent.FindHandler(SCR_ModularButtonComponent));
		m_DependentComponent1 = SCR_DynamicIconComponent.Cast(m_wDependent.FindHandler(SCR_DynamicIconComponent));
		m_DependentComponent2 = SCR_CoreMenuHeaderComponent.Cast(m_wDependent.FindHandler(SCR_CoreMenuHeaderComponent));


		m_wVersionComboBox = ButtonWidget.Cast(root.FindWidget("MainPanel.VerticalLayout0.Content.m_MainContentScroll.m_MainContent.m_MainSection.ButtonsArea.ButtonsMainHorizontalLayout.Buttons.m_VersionComboBox"));
		m_VersionComboBoxComponent0 = SCR_ComboBoxComponent.Cast(m_wVersionComboBox.FindHandler(SCR_ComboBoxComponent));
		m_VersionComboBoxComponent1 = SCR_ModularButtonComponent.Cast(m_wVersionComboBox.FindHandler(SCR_ModularButtonComponent));


		m_wDeleteButton = ButtonWidget.Cast(root.FindWidget("MainPanel.VerticalLayout0.Content.m_MainContentScroll.m_MainContent.m_MainSection.ButtonsArea.ButtonsMainHorizontalLayout.Info.m_DeleteButton"));
		m_DeleteButtonComponent0 = SCR_ModularButtonComponent.Cast(m_wDeleteButton.FindHandler(SCR_ModularButtonComponent));
		m_DeleteButtonComponent1 = SCR_DynamicIconComponent.Cast(m_wDeleteButton.FindHandler(SCR_DynamicIconComponent));
		m_DeleteButtonComponent2 = SCR_CoreMenuHeaderComponent.Cast(m_wDeleteButton.FindHandler(SCR_CoreMenuHeaderComponent));


		m_wAddonSize = OverlayWidget.Cast(root.FindWidget("MainPanel.VerticalLayout0.Content.m_MainContentScroll.m_MainContent.m_MainSection.ButtonsArea.ButtonsMainHorizontalLayout.Info.m_wAddonSize"));
		m_AddonSizeComponent0 = SCR_DynamicIconComponent.Cast(m_wAddonSize.FindHandler(SCR_DynamicIconComponent));
		m_AddonSizeComponent1 = SCR_CoreMenuHeaderComponent.Cast(m_wAddonSize.FindHandler(SCR_CoreMenuHeaderComponent));

		m_wVersionUpdateHorizontalLayout = HorizontalLayoutWidget.Cast(root.FindWidget("MainPanel.VerticalLayout0.Content.m_MainContentScroll.m_MainContent.m_MainSection.ButtonsArea.ButtonsMainHorizontalLayout.Info.ModVersionHorizontalLayout.m_wVersionUpdateHorizontalLayout"));
		m_wUpdateVersion = TextWidget.Cast(root.FindWidget("MainPanel.VerticalLayout0.Content.m_MainContentScroll.m_MainContent.m_MainSection.ButtonsArea.ButtonsMainHorizontalLayout.Info.ModVersionHorizontalLayout.m_wVersionUpdateHorizontalLayout.m_wUpdateVersion"));
		m_wCurrentVersion = TextWidget.Cast(root.FindWidget("MainPanel.VerticalLayout0.Content.m_MainContentScroll.m_MainContent.m_MainSection.ButtonsArea.ButtonsMainHorizontalLayout.Info.ModVersionHorizontalLayout.m_wCurrentVersion"));
		m_wCurrentVersionIcon = ImageWidget.Cast(root.FindWidget("MainPanel.VerticalLayout0.Content.m_MainContentScroll.m_MainContent.m_MainSection.ButtonsArea.ButtonsMainHorizontalLayout.Info.ModVersionHorizontalLayout.m_wCurrentVersionIcon"));
		m_wLastPlayedHorizontalLayout = HorizontalLayoutWidget.Cast(root.FindWidget("MainPanel.VerticalLayout0.Content.m_MainContentScroll.m_MainContent.m_MainSection.ButtonsArea.ButtonsMainHorizontalLayout.Info.LastPlayedSize.m_wLastPlayedHorizontalLayout"));
		m_wLastPlayed = TextWidget.Cast(root.FindWidget("MainPanel.VerticalLayout0.Content.m_MainContentScroll.m_MainContent.m_MainSection.ButtonsArea.ButtonsMainHorizontalLayout.Info.LastPlayedSize.m_wLastPlayedHorizontalLayout.m_wLastPlayed"));
		m_wLastDownloadedHorizontalLayout = HorizontalLayoutWidget.Cast(root.FindWidget("MainPanel.VerticalLayout0.Content.m_MainContentScroll.m_MainContent.m_MainSection.ButtonsArea.ButtonsMainHorizontalLayout.Info.LastDownloadedSize.m_wLastDownloadedHorizontalLayout"));
		m_wLastDownloaded = TextWidget.Cast(root.FindWidget("MainPanel.VerticalLayout0.Content.m_MainContentScroll.m_MainContent.m_MainSection.ButtonsArea.ButtonsMainHorizontalLayout.Info.LastDownloadedSize.m_wLastDownloadedHorizontalLayout.m_wLastDownloaded"));

		m_wBackendSource = OverlayWidget.Cast(root.FindWidget("MainPanel.VerticalLayout0.Content.m_MainContentScroll.m_MainContent.m_MainSection.ButtonsArea.ButtonsMainHorizontalLayout.Info.m_wBackendSource"));
		m_BackendSourceComponent0 = SCR_DynamicIconComponent.Cast(m_wBackendSource.FindHandler(SCR_DynamicIconComponent));
		m_BackendSourceComponent1 = SCR_CoreMenuHeaderComponent.Cast(m_wBackendSource.FindHandler(SCR_CoreMenuHeaderComponent));

		m_wDownloadProgressBarOverlay = OverlayWidget.Cast(root.FindWidget("MainPanel.VerticalLayout0.Content.m_MainContentScroll.m_MainContent.m_MainSection.ButtonsArea.DownloadProgressBarSize.m_wDownloadProgressBarOverlay"));
		m_wDownloadProgressBar = ProgressBarWidget.Cast(root.FindWidget("MainPanel.VerticalLayout0.Content.m_MainContentScroll.m_MainContent.m_MainSection.ButtonsArea.DownloadProgressBarSize.m_wDownloadProgressBarOverlay.m_wDownloadProgressBar"));

		m_wDescriptionHoverDetector = ButtonWidget.Cast(root.FindWidget("MainPanel.VerticalLayout0.Content.m_MainContentScroll.m_MainContent.m_MainSection.DescriptionAreaOvelay.m_DescriptionHoverDetector"));
		m_DescriptionHoverDetectorComponent = SCR_EventHandlerComponent.Cast(m_wDescriptionHoverDetector.FindHandler(SCR_EventHandlerComponent));

		m_wSummaryText = TextWidget.Cast(root.FindWidget("MainPanel.VerticalLayout0.Content.m_MainContentScroll.m_MainContent.m_MainSection.DescriptionAreaOvelay.DescriptionArea.m_SummaryText"));
		m_wDescriptionText = TextWidget.Cast(root.FindWidget("MainPanel.VerticalLayout0.Content.m_MainContentScroll.m_MainContent.m_MainSection.DescriptionAreaOvelay.DescriptionArea.m_DescriptionText"));
		m_wScenarioSection = VerticalLayoutWidget.Cast(root.FindWidget("MainPanel.VerticalLayout0.Content.m_MainContentScroll.m_MainContent.m_ScenarioSection"));
		m_wScenariosList = VerticalLayoutWidget.Cast(root.FindWidget("MainPanel.VerticalLayout0.Content.m_MainContentScroll.m_MainContent.m_ScenarioSection.m_ScenariosList"));

		m_wScenarioDetailsPanel = OverlayWidget.Cast(root.FindWidget("RightPanel.VerticalLayout0.Content.m_ScenarioDetailsPanel"));
		m_ScenarioDetailsPanelComponent = SCR_ScenarioDetailsPanelComponent.Cast(m_wScenarioDetailsPanel.FindHandler(SCR_ScenarioDetailsPanelComponent));


		m_wAddonDetailsPanel = OverlayWidget.Cast(root.FindWidget("RightPanel.VerticalLayout0.Content.m_AddonDetailsPanel"));
		m_AddonDetailsPanelComponent = SCR_AddonDetailsPanelComponent.Cast(m_wAddonDetailsPanel.FindHandler(SCR_AddonDetailsPanelComponent));


		return true;
	}

	//------------------------------------------------------------------------------------------------
	ResourceName GetLayout()
	{
		return LAYOUT;
	}
}
