// Autogenerated by the Generate Class from Layout plugin v0.5.0
// Layout file: UI/layouts/Menus/Common/DetailsPanel/Prefabs/AddonInfo.layout
class SCR_AddonInfoWidgets
{
	protected static const ResourceName LAYOUT = "{ABF8E40093827358}UI/layouts/Menus/Common/DetailsPanel/Prefabs/AddonInfo.layout";

	TextWidget m_wModSize;
	HorizontalLayoutWidget m_wDependenciesHorizontalLayout;
	TextWidget m_wDependencies;
	HorizontalLayoutWidget m_wDependentHorizontalLayout;
	TextWidget m_wDependent;
	HorizontalLayoutWidget m_wVersionUpdateHorizontalLayout;
	TextWidget m_wUpdateVersion;
	TextWidget m_wCurrentVersion;
	ImageWidget m_wCurrentVersionIcon;
	TextWidget m_wModRating;
	HorizontalLayoutWidget m_wLastDownloadedHorizontalLayout;
	TextWidget m_wLastDownloaded;

	//------------------------------------------------------------------------------------------------
	bool Init(Widget root)
	{
		m_wModSize = TextWidget.Cast(root.FindWidget("AddonInfoHorizontalLayoutMain.AddonInfoVerticalLayoutLeft.ModSizeHorizontalLayout.m_wModSize"));
		m_wDependenciesHorizontalLayout = HorizontalLayoutWidget.Cast(root.FindWidget("AddonInfoHorizontalLayoutMain.AddonInfoVerticalLayoutLeft.m_wDependenciesHorizontalLayout"));
		m_wDependencies = TextWidget.Cast(root.FindWidget("AddonInfoHorizontalLayoutMain.AddonInfoVerticalLayoutLeft.m_wDependenciesHorizontalLayout.m_wDependencies"));
		m_wDependentHorizontalLayout = HorizontalLayoutWidget.Cast(root.FindWidget("AddonInfoHorizontalLayoutMain.AddonInfoVerticalLayoutLeft.m_wDependentHorizontalLayout"));
		m_wDependent = TextWidget.Cast(root.FindWidget("AddonInfoHorizontalLayoutMain.AddonInfoVerticalLayoutLeft.m_wDependentHorizontalLayout.m_wDependent"));
		m_wVersionUpdateHorizontalLayout = HorizontalLayoutWidget.Cast(root.FindWidget("AddonInfoHorizontalLayoutMain.AddonInfoVerticalLayoutRight.ModVersionHorizontalLayout.m_wVersionUpdateHorizontalLayout"));
		m_wUpdateVersion = TextWidget.Cast(root.FindWidget("AddonInfoHorizontalLayoutMain.AddonInfoVerticalLayoutRight.ModVersionHorizontalLayout.m_wVersionUpdateHorizontalLayout.m_wUpdateVersion"));
		m_wCurrentVersion = TextWidget.Cast(root.FindWidget("AddonInfoHorizontalLayoutMain.AddonInfoVerticalLayoutRight.ModVersionHorizontalLayout.m_wCurrentVersion"));
		m_wCurrentVersionIcon = ImageWidget.Cast(root.FindWidget("AddonInfoHorizontalLayoutMain.AddonInfoVerticalLayoutRight.ModVersionHorizontalLayout.m_wCurrentVersionIcon"));
		m_wModRating = TextWidget.Cast(root.FindWidget("AddonInfoHorizontalLayoutMain.AddonInfoVerticalLayoutRight.ModRatingHorizontalLayout.m_wModRating"));
		m_wLastDownloadedHorizontalLayout = HorizontalLayoutWidget.Cast(root.FindWidget("AddonInfoHorizontalLayoutMain.AddonInfoVerticalLayoutRight.LastDownloadedSize.m_wLastDownloadedHorizontalLayout"));
		m_wLastDownloaded = TextWidget.Cast(root.FindWidget("AddonInfoHorizontalLayoutMain.AddonInfoVerticalLayoutRight.LastDownloadedSize.m_wLastDownloadedHorizontalLayout.m_wLastDownloaded"));

		return true;
	}

	//------------------------------------------------------------------------------------------------
	ResourceName GetLayout()
	{
		return LAYOUT;
	}
}
