// Autogenerated by the Generate Class from Layout plugin v0.5.0
// Layout file: UI/layouts/Menus/ContentBrowser/GalleryDialog/ContentBrowser_GalleryDialog.layout
class SCR_ContentBrowser_GalleryDialogWidgets
{
	protected static const ResourceName LAYOUT = "{7D40DE47A476B49C}UI/layouts/Menus/ContentBrowser/GalleryDialog/ContentBrowser_GalleryDialog.layout";

	ButtonWidget m_wSpinBox;
	SCR_SpinBoxComponent m_SpinBoxComponent0;
	SCR_ModularButtonComponent m_SpinBoxComponent1;

	OverlayWidget m_BackendImage;
	SCR_BackendImageComponent m_BackendImageComponent;
	
	ButtonWidget m_wBackButton;
	SCR_InputButtonComponent m_BackButtonComponent;

	OverlayWidget m_wOverlay;
	ImageWidget m_wGlow;
	ImageWidget m_wOutlineClear;
	ImageWidget m_wOutline;
	ImageWidget m_wButtonImgGlow;
	ImageWidget m_wKeyBG;
	ImageWidget m_wDoubleTabIndicator;
	ImageWidget m_wHoldIndicator;
	ImageWidget m_wButtonImg;
	VerticalLayoutWidget m_wVerticalLayout0;
	RichTextWidget m_wButtonText;

	ButtonWidget m_wCloseButton;
	SCR_ModularButtonComponent m_CloseButtonComponent;

	ButtonWidget m_PrevButton;
	SCR_ModularButtonComponent m_PrevButtonComponent;
	
	ButtonWidget m_NextButton;
	SCR_ModularButtonComponent m_NextButtonComponent;

	//------------------------------------------------------------------------------------------------
	bool Init(Widget root)
	{
		m_wSpinBox = ButtonWidget.Cast(root.FindWidget("Overlay.VerticalLayout0.SpinBoxOverlay.m_SpinBox"));
		m_SpinBoxComponent0 = SCR_SpinBoxComponent.Cast(m_wSpinBox.FindHandler(SCR_SpinBoxComponent));
		m_SpinBoxComponent1 = SCR_ModularButtonComponent.Cast(m_wSpinBox.FindHandler(SCR_ModularButtonComponent));

		m_wBackButton = ButtonWidget.Cast(root.FindWidget("Overlay.VerticalLayout0.SpinBoxOverlay.m_BackButton"));
		m_BackButtonComponent = SCR_InputButtonComponent.Cast(m_wBackButton.FindHandler(SCR_InputButtonComponent));

		m_wCloseButton = ButtonWidget.Cast(root.FindWidget("Overlay.CloseButtonSize.m_CloseButton"));
		m_CloseButtonComponent = SCR_ModularButtonComponent.Cast(m_wCloseButton.FindHandler(SCR_ModularButtonComponent));

		m_PrevButton = ButtonWidget.Cast(root.FindWidget("Overlay.VerticalLayout0.ImageAndButtons.PrevButton.Button"));
		m_PrevButtonComponent = SCR_ModularButtonComponent.Cast(m_PrevButton.FindHandler(SCR_ModularButtonComponent));
		
		m_NextButton = ButtonWidget.Cast(root.FindWidget("Overlay.VerticalLayout0.ImageAndButtons.NextButton.Button"));
		m_NextButtonComponent = SCR_ModularButtonComponent.Cast(m_NextButton.FindHandler(SCR_ModularButtonComponent));

		m_BackendImage = OverlayWidget.Cast(root.FindWidget("Overlay.VerticalLayout0.ImageAndButtons.ImageSize.m_BackendImage"));
		m_BackendImageComponent = SCR_BackendImageComponent.Cast(m_BackendImage.FindHandler(SCR_BackendImageComponent));
		
		return true;
	}

	//------------------------------------------------------------------------------------------------
	ResourceName GetLayout()
	{
		return LAYOUT;
	}
}
