// Autogenerated by the Generate Class from Layout plugin v0.5.1
// Layout file: UI/layouts/Menus/DeployMenu/Journal.layout
class SCR_JournalWidgets
{
	protected static const ResourceName LAYOUT = "{7482F0B8A63C1159}UI/layouts/Menus/DeployMenu/Journal.layout";

	SizeLayoutWidget m_wSizeLayout;

	ButtonWidget m_wFocusButton;
	SCR_EventHandlerComponent m_FocusButtonComponent;

	VerticalLayoutWidget m_wEntriesWrapper;
	SizeLayoutWidget m_wEntryLayout;

	//------------------------------------------------------------------------------------------------
	bool Init(notnull Widget root)
	{
		m_wSizeLayout = SizeLayoutWidget.Cast(root.FindWidget("HorizontalLayout.m_wSizeLayout"));

		m_wFocusButton = ButtonWidget.Cast(root.FindWidget("HorizontalLayout.m_wSizeLayout.Overlay.m_wFocusButton"));
		m_FocusButtonComponent = SCR_EventHandlerComponent.Cast(m_wFocusButton.FindHandler(SCR_EventHandlerComponent));

		m_wEntriesWrapper = VerticalLayoutWidget.Cast(root.FindWidget("HorizontalLayout.m_wSizeLayout.Overlay.Vertical.Overlay.JournalScrollLayout.m_wEntriesWrapper"));
		m_wEntryLayout = SizeLayoutWidget.Cast(root.FindWidget("HorizontalLayout.VerticalLayout.m_wEntryLayout"));

		return true;
	}

	//------------------------------------------------------------------------------------------------
	ResourceName GetLayout()
	{
		return LAYOUT;
	}
}
