// Autogenerated by the Generate Class from Layout plugin, version 0.2.0
// Layout file: UI/layouts/HUD/Chat/ChatPanel.layout

class SCR_ChatPanelWidgets
{
	static const ResourceName s_sLayout = "{28C54D576A8997CF}UI/layouts/HUD/Chat/ChatPanel.layout";
	ResourceName GetLayout() { return s_sLayout; }

	VerticalLayoutWidget m_MessageHistory;

	OverlayWidget m_EditOverlay;

	ImageWidget m_EditBackgroundImage;

	TextWidget m_ChannelTagOverlay;

	ImageWidget m_ChannelTypeImage;

	EditBoxWidget m_MessageEditBox;
	EditBoxFilterComponent m_MessageEditBoxComponent0;
	SCR_EventHandlerComponent m_MessageEditBoxComponent1;

	HorizontalLayoutWidget m_WarningChannelMessage;

	ImageWidget m_WarningImage;

	TextWidget m_WarningText;

	TextWidget m_ChannelTagEditor;

	bool Init(Widget root)
	{
		m_MessageHistory = VerticalLayoutWidget.Cast(root.FindWidget("OverlayAlignTop.m_MessageHistory"));

		m_EditOverlay = OverlayWidget.Cast(root.FindWidget("OverlayAlignTop.m_MessageHistory.m_EditOverlay"));

		m_EditBackgroundImage = ImageWidget.Cast(root.FindWidget("OverlayAlignTop.m_MessageHistory.m_EditOverlay.EditLayoutBar.m_EditBackgroundImage"));

		m_ChannelTagOverlay = TextWidget.Cast(root.FindWidget("OverlayAlignTop.m_MessageHistory.m_EditOverlay.EditLayoutBar.m_ChannelTagOverlay"));

		m_ChannelTypeImage = ImageWidget.Cast(root.FindWidget("OverlayAlignTop.m_MessageHistory.m_EditOverlay.EditLayoutBar.MessageEditor.m_ChannelTypeImage"));

		m_MessageEditBox = EditBoxWidget.Cast(root.FindWidget("OverlayAlignTop.m_MessageHistory.m_EditOverlay.EditLayoutBar.MessageEditor.Width.m_MessageEditBox"));
		m_MessageEditBoxComponent0 = EditBoxFilterComponent.Cast(m_MessageEditBox.FindHandler(EditBoxFilterComponent));
		m_MessageEditBoxComponent1 = SCR_EventHandlerComponent.Cast(m_MessageEditBox.FindHandler(SCR_EventHandlerComponent));

		m_WarningChannelMessage = HorizontalLayoutWidget.Cast(root.FindWidget("OverlayAlignTop.m_MessageHistory.m_EditOverlay.EditLayoutBar.MessageEditor.m_WarningChannelMessage"));

		m_WarningImage = ImageWidget.Cast(root.FindWidget("OverlayAlignTop.m_MessageHistory.m_EditOverlay.EditLayoutBar.MessageEditor.m_WarningChannelMessage.m_WarningImage"));

		m_WarningText = TextWidget.Cast(root.FindWidget("OverlayAlignTop.m_MessageHistory.m_EditOverlay.EditLayoutBar.MessageEditor.m_WarningChannelMessage.m_WarningText"));

		m_ChannelTagEditor = TextWidget.Cast(root.FindWidget("OverlayAlignTop.m_MessageHistory.m_EditOverlay.EditLayoutBar.MessageEditor.m_ChannelTagEditor"));

		return true;
	}
};
