// Autogenerated by the Generate Class from Layout plugin v0.5.0
// Layout file: UI/layouts/HUD/Chat/ChatMessageLine.layout
class SCR_ChatMessageLineWidgets
{
	protected static const ResourceName LAYOUT = "{973C90F6B6135A50}UI/layouts/HUD/Chat/ChatMessageLine.layout";

	ImageWidget m_wBackgroundImage;
	ImageWidget m_wTypeImage;
	ImageWidget m_wPlatformImage;
	TextWidget m_wMessageText;
	SizeLayoutWidget m_wBadge;

	//------------------------------------------------------------------------------------------------
	bool Init(Widget root)
	{
		m_wBackgroundImage = ImageWidget.Cast(root.FindWidget("SizeLayout0.Overlay0.m_BackgroundImage"));
		m_wTypeImage = ImageWidget.Cast(root.FindWidget("SizeLayout0.Overlay0.MessageLayout.m_TypeImage"));
		m_wPlatformImage = ImageWidget.Cast(root.FindWidget("SizeLayout0.Overlay0.MessageLayout.m_PlatformImage"));
		m_wMessageText = TextWidget.Cast(root.FindWidget("SizeLayout0.Overlay0.MessageLayout.Width.m_MessageText"));
		m_wBadge = SizeLayoutWidget.Cast(root.FindWidget("SizeLayout0.Overlay0.m_Badge"));

		return true;
	}

	//------------------------------------------------------------------------------------------------
	ResourceName GetLayout()
	{
		return LAYOUT;
	}
}
