// Autogenerated by the Generate Class from Layout plugin v0.5.1
// Layout file: UI/layouts/Menus/Common/DetailsPanel/ContentDetailsPanelBase.layout
class SCR_ContentDetailsPanelBaseWidgets
{
	protected static const ResourceName LAYOUT = "{CB5B93884BFE5954}UI/layouts/Menus/Common/DetailsPanel/ContentDetailsPanelBase.layout";

	SizeLayoutWidget m_wTopSize;
	OverlayWidget m_wBackendImage;
	ImageWidget m_wImage;
	ImageWidget m_wMANWLogo;

	ButtonWidget m_wLoadingOverlay;
	SCR_LoadingOverlay m_LoadingOverlayComponent;

	BlurWidget m_wBlur;
	ImageWidget m_wBackgroundImage;

	ImageWidget m_wAnimationImage;
	SCR_SpinningWidgetComponent m_AnimationImageComponent;

	TextWidget m_wText;

	OverlayWidget m_wWarningOverlay;
	SCR_SimpleWarningOverlayComponent m_WarningOverlayComponent;

	HorizontalLayoutWidget m_wTypeOverlay;
	HorizontalLayoutWidget m_wTypeImages;

	FrameWidget m_wMANW;
	SCR_MANW_RankComponent m_MANWComponent;

	ImageWidget m_wRankIcon;
	TextWidget m_wCategoryText;
	FrameWidget m_wMainArea;
	ImageWidget m_wNameImg;
	TextWidget m_wNameText;
	TextWidget m_wAuthorNameText;
	TextWidget m_wDescriptionText;
	OverlayWidget m_wAdditionalInfo;

	//------------------------------------------------------------------------------------------------
	bool Init(notnull Widget root)
	{
		m_wTopSize = SizeLayoutWidget.Cast(root.FindWidget("m_TopSize"));
		m_wBackendImage = OverlayWidget.Cast(root.FindWidget("m_TopSize.m_BackendImage"));
		m_wImage = ImageWidget.Cast(root.FindWidget("m_TopSize.m_BackendImage.ImageScale.m_Image"));
		m_wMANWLogo = ImageWidget.Cast(root.FindWidget("m_TopSize.m_BackendImage.m_wMANWLogo"));

		m_wLoadingOverlay = ButtonWidget.Cast(root.FindWidget("m_TopSize.m_BackendImage.m_LoadingOverlay"));
		m_LoadingOverlayComponent = SCR_LoadingOverlay.Cast(m_wLoadingOverlay.FindHandler(SCR_LoadingOverlay));

		m_wBlur = BlurWidget.Cast(root.FindWidget("m_TopSize.m_BackendImage.m_LoadingOverlay.loadingOverlayRoot1.m_Blur"));
		m_wBackgroundImage = ImageWidget.Cast(root.FindWidget("m_TopSize.m_BackendImage.m_LoadingOverlay.loadingOverlayRoot1.m_BackgroundImage"));

		m_wAnimationImage = ImageWidget.Cast(root.FindWidget("m_TopSize.m_BackendImage.m_LoadingOverlay.loadingOverlayRoot1.m_AnimationImage"));
		m_AnimationImageComponent = SCR_SpinningWidgetComponent.Cast(m_wAnimationImage.FindHandler(SCR_SpinningWidgetComponent));

		m_wText = TextWidget.Cast(root.FindWidget("m_TopSize.m_BackendImage.m_LoadingOverlay.loadingOverlayRoot1.m_Text"));

		m_wWarningOverlay = OverlayWidget.Cast(root.FindWidget("m_TopSize.m_BackendImage.m_WarningOverlay"));
		m_WarningOverlayComponent = SCR_SimpleWarningOverlayComponent.Cast(m_wWarningOverlay.FindHandler(SCR_SimpleWarningOverlayComponent));

		m_wTypeOverlay = HorizontalLayoutWidget.Cast(root.FindWidget("m_TopSize.m_BackendImage.m_TypeOverlay"));
		m_wTypeImages = HorizontalLayoutWidget.Cast(root.FindWidget("m_TopSize.m_BackendImage.m_TypeOverlay.m_TypeImages"));

		m_wMANW = FrameWidget.Cast(root.FindWidget("m_TopSize.m_BackendImage.m_wMANW"));
		m_MANWComponent = SCR_MANW_RankComponent.Cast(m_wMANW.FindHandler(SCR_MANW_RankComponent));

		m_wRankIcon = ImageWidget.Cast(root.FindWidget("m_TopSize.m_BackendImage.m_wMANW.Overlay0.HorizontalLayout0.m_wRankIcon"));
		m_wCategoryText = TextWidget.Cast(root.FindWidget("m_TopSize.m_BackendImage.m_wMANW.Overlay0.HorizontalLayout0.m_wCategoryText"));
		m_wMainArea = FrameWidget.Cast(root.FindWidget("Bottom.m_MainArea"));
		m_wNameImg = ImageWidget.Cast(root.FindWidget("Bottom.m_MainArea.Offset.HeaderSize.HeaderHorizontalLayout.m_NameImg"));
		m_wNameText = TextWidget.Cast(root.FindWidget("Bottom.m_MainArea.Offset.HeaderSize.HeaderHorizontalLayout.m_NameText"));
		m_wAuthorNameText = TextWidget.Cast(root.FindWidget("Bottom.m_MainArea.Offset.AuthorSize.m_AuthorNameText"));
		m_wDescriptionText = TextWidget.Cast(root.FindWidget("Bottom.m_MainArea.Offset.m_DescriptionText"));
		m_wAdditionalInfo = OverlayWidget.Cast(root.FindWidget("Bottom.m_MainArea.Offset.m_AdditionalInfo"));

		return true;
	}

	//------------------------------------------------------------------------------------------------
	ResourceName GetLayout()
	{
		return LAYOUT;
	}
}
