// Autogenerated by the Generate Class from Layout plugin, version 0.3.0
// Layout file: UI/layouts/HUD/StatsPanel/StatsPanel.layout

class SCR_StatsPanelWidgets
{
	static const ResourceName s_sLayout = "{0A3C9C22CBDE338F}UI/layouts/HUD/StatsPanel/StatsPanel.layout";
	ResourceName GetLayout() { return s_sLayout; }

	HorizontalLayoutWidget m_wColorOpacity;

	ImageWidget m_wIconGlow;

	ImageWidget m_wIcon;

	TextWidget m_wLabel;

	TextWidget m_wTextPlaceholder;

	TextWidget m_wText;

	bool Init(Widget root)
	{
		m_wColorOpacity = HorizontalLayoutWidget.Cast(root.FindAnyWidget("m_wColorOpacity"));

		m_wIconGlow = ImageWidget.Cast(root.FindAnyWidget("m_wIconGlow"));

		m_wIcon = ImageWidget.Cast(root.FindAnyWidget("m_wIcon"));

		m_wLabel = TextWidget.Cast(root.FindAnyWidget("m_wLabel"));

		m_wTextPlaceholder = TextWidget.Cast(root.FindAnyWidget("m_wTextPlaceholder"));

		m_wText = TextWidget.Cast(root.FindAnyWidget("m_wText"));

		return true;
	}
}
