// Autogenerated by the Generate Class from Layout plugin, version 0.3.0
// Layout file: UI/layouts/HUD/VehicleInfo/VehicleGearShift.layout

class SCR_VehicleGearShiftWidgets
{
	static const ResourceName s_sLayout = "{5FBB1623E3CD1DF2}UI/layouts/HUD/VehicleInfo/VehicleGearShift.layout";
	ResourceName GetLayout() { return s_sLayout; }

	OverlayWidget m_LowerSelected;

	TextWidget m_LowerSelectedText;

	OverlayWidget m_Lower;

	TextWidget m_LowerText;

	OverlayWidget m_MiddleSelected;

	TextWidget m_MiddleSelectedText;

	OverlayWidget m_Middle;

	TextWidget m_MiddleText;

	OverlayWidget m_UpperSelected;

	TextWidget m_UpperSelectedText;

	OverlayWidget m_Upper;

	TextWidget m_UpperText;

	bool Init(Widget root)
	{
		m_LowerSelected = OverlayWidget.Cast(root.FindWidget("HorizontalLayout0.SlotLower.m_LowerSelected"));

		m_LowerSelectedText = TextWidget.Cast(root.FindWidget("HorizontalLayout0.SlotLower.m_LowerSelected.m_LowerSelectedText"));

		m_Lower = OverlayWidget.Cast(root.FindWidget("HorizontalLayout0.SlotLower.m_Lower"));

		m_LowerText = TextWidget.Cast(root.FindWidget("HorizontalLayout0.SlotLower.m_Lower.m_LowerText"));

		m_MiddleSelected = OverlayWidget.Cast(root.FindWidget("HorizontalLayout0.SlotMiddle.m_MiddleSelected"));

		m_MiddleSelectedText = TextWidget.Cast(root.FindWidget("HorizontalLayout0.SlotMiddle.m_MiddleSelected.m_MiddleSelectedText"));

		m_Middle = OverlayWidget.Cast(root.FindWidget("HorizontalLayout0.SlotMiddle.m_Middle"));

		m_MiddleText = TextWidget.Cast(root.FindWidget("HorizontalLayout0.SlotMiddle.m_Middle.m_MiddleText"));

		m_UpperSelected = OverlayWidget.Cast(root.FindWidget("HorizontalLayout0.SlotUpper.m_UpperSelected"));

		m_UpperSelectedText = TextWidget.Cast(root.FindWidget("HorizontalLayout0.SlotUpper.m_UpperSelected.m_UpperSelectedText"));

		m_Upper = OverlayWidget.Cast(root.FindWidget("HorizontalLayout0.SlotUpper.m_Upper"));

		m_UpperText = TextWidget.Cast(root.FindWidget("HorizontalLayout0.SlotUpper.m_Upper.m_UpperText"));

		return true;
	}
}
