// Autogenerated by the Generate Class from Layout plugin, version 0.3.0
// Layout file: UI/layouts/Menus/ContentBrowser/Dialogs/DownloadConfirmationDialogContent.layout

class SCR_DownloadConfirmationDialogContentWidgets
{
	static const ResourceName s_sLayout = "{9790161CE3D20582}UI/layouts/Menus/ContentBrowser/Dialogs/DownloadConfirmationDialogContent.layout";
	ResourceName GetLayout() { return s_sLayout; }

	ButtonWidget m_LoadingOverlay;
	SCR_LoadingOverlay m_LoadingOverlayComponent;

	BlurWidget m_Blur;

	ImageWidget m_BackgroundImage;

	ImageWidget m_AnimationImage;
	SCR_SpinningWidgetComponent m_AnimationImageComponent;

	TextWidget m_Text;

	VerticalLayoutWidget m_AddonContentVertical;

	VerticalLayoutWidget m_MainAddonSection;

	ButtonWidget m_MainAddonLine;
	SCR_DownloadManager_AddonDownloadLine m_MainAddonLineComponent0;
	SCR_ModularButtonComponent m_MainAddonLineComponent1;

	VerticalLayoutWidget m_OtherAddonsSection;

	TextWidget m_OtherAddonsMessage;

	VerticalLayoutWidget m_OtherAddonsList;

	ImageWidget m_UpdateSpacer;

	TextWidget m_UpdateAddonsMessage;

	VerticalLayoutWidget m_UpdateAddonsList;

	HorizontalLayoutWidget m_SummarySection;

	SizeLayoutWidget m_AddonSizeOverlay;

	TextWidget m_TotalAddonSizeText;

	bool Init(Widget root)
	{
		m_LoadingOverlay = ButtonWidget.Cast(root.FindWidget("Overlay.m_LoadingOverlay"));
		m_LoadingOverlayComponent = SCR_LoadingOverlay.Cast(m_LoadingOverlay.FindHandler(SCR_LoadingOverlay));

		m_Blur = BlurWidget.Cast(root.FindWidget("Overlay.m_LoadingOverlay.loadingOverlayRoot1.m_Blur"));

		m_BackgroundImage = ImageWidget.Cast(root.FindWidget("Overlay.m_LoadingOverlay.loadingOverlayRoot1.m_BackgroundImage"));

		m_AnimationImage = ImageWidget.Cast(root.FindWidget("Overlay.m_LoadingOverlay.loadingOverlayRoot1.m_AnimationImage"));
		m_AnimationImageComponent = SCR_SpinningWidgetComponent.Cast(m_AnimationImage.FindHandler(SCR_SpinningWidgetComponent));

		m_Text = TextWidget.Cast(root.FindWidget("Overlay.m_LoadingOverlay.loadingOverlayRoot1.m_Text"));

		m_AddonContentVertical = VerticalLayoutWidget.Cast(root.FindWidget("Overlay.m_AddonContentVertical"));

		m_MainAddonSection = VerticalLayoutWidget.Cast(root.FindWidget("Overlay.m_AddonContentVertical.m_MainAddonSection"));

		m_MainAddonLine = ButtonWidget.Cast(root.FindWidget("Overlay.m_AddonContentVertical.m_MainAddonSection.Overlay.m_MainAddonLine"));
		m_MainAddonLineComponent0 = SCR_DownloadManager_AddonDownloadLine.Cast(m_MainAddonLine.FindHandler(SCR_DownloadManager_AddonDownloadLine));
		m_MainAddonLineComponent1 = SCR_ModularButtonComponent.Cast(m_MainAddonLine.FindHandler(SCR_ModularButtonComponent));

		m_OtherAddonsSection = VerticalLayoutWidget.Cast(root.FindWidget("Overlay.m_AddonContentVertical.m_OtherAddonsSection"));

		m_OtherAddonsMessage = TextWidget.Cast(root.FindWidget("Overlay.m_AddonContentVertical.m_OtherAddonsSection.m_OtherAddonsMessage"));

		m_OtherAddonsList = VerticalLayoutWidget.Cast(root.FindWidget("Overlay.m_AddonContentVertical.m_OtherAddonsSection.OtherAddonsScrollSize.Overlay.ScrollLayout.AddonListWrap.m_OtherAddonsList"));

		m_UpdateSpacer = ImageWidget.Cast(root.FindWidget("Overlay.m_AddonContentVertical.m_OtherAddonsSection.OtherAddonsScrollSize.Overlay.ScrollLayout.AddonListWrap.m_UpdateSpacer"));

		m_UpdateAddonsMessage = TextWidget.Cast(root.FindWidget("Overlay.m_AddonContentVertical.m_OtherAddonsSection.OtherAddonsScrollSize.Overlay.ScrollLayout.AddonListWrap.m_UpdateAddonsMessage"));

		m_UpdateAddonsList = VerticalLayoutWidget.Cast(root.FindWidget("Overlay.m_AddonContentVertical.m_OtherAddonsSection.OtherAddonsScrollSize.Overlay.ScrollLayout.AddonListWrap.m_UpdateAddonsList"));

		m_SummarySection = HorizontalLayoutWidget.Cast(root.FindWidget("Overlay.m_AddonContentVertical.m_SummarySection"));

		m_AddonSizeOverlay = SizeLayoutWidget.Cast(root.FindWidget("Overlay.m_AddonContentVertical.m_SummarySection.m_AddonSizeOverlay"));

		m_TotalAddonSizeText = TextWidget.Cast(root.FindWidget("Overlay.m_AddonContentVertical.m_SummarySection.m_AddonSizeOverlay.AddonSizeOverlay.m_TotalAddonSizeText"));

		return true;
	}
}
