// Autogenerated by the Generate Class from Layout plugin, version 0.3.0
// Layout file: UI/layouts/Menus/ContentBrowser/DownloadManager/DownloadManager_AddonDownloadLineBase.layout

class SCR_DownloadManager_AddonDownloadLineBaseWidgets
{
	static const ResourceName s_sLayout = "{F5E8AFE1BE5FA9DB}UI/layouts/Menus/ContentBrowser/DownloadManager/DownloadManager_AddonDownloadLineBase.layout";
	ResourceName GetLayout() { return s_sLayout; }

	ProgressBarWidget m_ProgressBar;

	ImageWidget m_DownloadFinishedImage;

	ImageWidget m_DownloadFailedImage;

	ButtonWidget m_PauseResumeButton;
	SCR_ModularButtonComponent m_PauseResumeButtonComponent;

	TextWidget m_AddonNameText;

	TextWidget m_ErrorText;

	HorizontalLayoutWidget m_RightWidgetGroup;

	ButtonWidget m_CancelButton;
	SCR_ModularButtonComponent m_CancelButtonComponent;

	SizeLayoutWidget m_AddonSizeOverlay;

	ImageWidget m_AddonActionIcon;

	TextWidget m_AddonSizeText;

	SizeLayoutWidget m_ProgressOverlay;

	TextWidget m_ProgressText;

	SizeLayoutWidget m_VersionsOverlay;

	TextWidget m_VersionToText;

	TextWidget m_VersionArrow;

	TextWidget m_VersionFromText;
	
	ImageWidget m_AddonSizeIcon;

	bool Init(Widget root)
	{
		m_ProgressBar = ProgressBarWidget.Cast(root.FindWidget("Height.Overlay.m_ProgressBar"));

		m_DownloadFinishedImage = ImageWidget.Cast(root.FindWidget("Height.Overlay.LineElements.HorizontalLayout.ButtonsOverlay.Overlay.m_DownloadFinishedImage"));

		m_DownloadFailedImage = ImageWidget.Cast(root.FindWidget("Height.Overlay.LineElements.HorizontalLayout.ButtonsOverlay.Overlay.m_DownloadFailedImage"));

		m_PauseResumeButton = ButtonWidget.Cast(root.FindWidget("Height.Overlay.LineElements.HorizontalLayout.ButtonsOverlay.Overlay.m_PauseResumeButton"));
		m_PauseResumeButtonComponent = SCR_ModularButtonComponent.Cast(m_PauseResumeButton.FindHandler(SCR_ModularButtonComponent));

		m_AddonNameText = TextWidget.Cast(root.FindWidget("Height.Overlay.LineElements.HorizontalLayout.m_AddonNameText"));

		m_ErrorText = TextWidget.Cast(root.FindWidget("Height.Overlay.LineElements.HorizontalLayout.m_ErrorText"));

		m_RightWidgetGroup = HorizontalLayoutWidget.Cast(root.FindWidget("Height.Overlay.LineElements.HorizontalLayout.m_RightWidgetGroup"));

		m_CancelButton = ButtonWidget.Cast(root.FindWidget("Height.Overlay.LineElements.HorizontalLayout.m_RightWidgetGroup.CancelButtonSize.m_CancelButton"));
		m_CancelButtonComponent = SCR_ModularButtonComponent.Cast(m_CancelButton.FindHandler(SCR_ModularButtonComponent));

		m_AddonSizeOverlay = SizeLayoutWidget.Cast(root.FindWidget("Height.Overlay.LineElements.HorizontalLayout.m_RightWidgetGroup.m_AddonSizeOverlay"));

		m_AddonActionIcon = ImageWidget.Cast(root.FindWidget("Height.Overlay.LineElements.HorizontalLayout.m_RightWidgetGroup.m_AddonSizeOverlay.AddonSizeOverlay.Scale0.m_AddonActionIcon"));

		m_AddonSizeText = TextWidget.Cast(root.FindWidget("Height.Overlay.LineElements.HorizontalLayout.m_RightWidgetGroup.m_AddonSizeOverlay.AddonSizeOverlay.Size0.m_AddonSizeText"));

		m_ProgressOverlay = SizeLayoutWidget.Cast(root.FindWidget("Height.Overlay.LineElements.HorizontalLayout.m_RightWidgetGroup.m_ProgressOverlay"));

		m_ProgressText = TextWidget.Cast(root.FindWidget("Height.Overlay.LineElements.HorizontalLayout.m_RightWidgetGroup.m_ProgressOverlay.m_ProgressText"));

		m_VersionsOverlay = SizeLayoutWidget.Cast(root.FindWidget("Height.Overlay.LineElements.HorizontalLayout.m_RightWidgetGroup.m_VersionsOverlay"));

		m_VersionToText = TextWidget.Cast(root.FindWidget("Height.Overlay.LineElements.HorizontalLayout.m_RightWidgetGroup.m_VersionsOverlay.VersionsOverlay.m_VersionToText"));

		m_VersionArrow = TextWidget.Cast(root.FindWidget("Height.Overlay.LineElements.HorizontalLayout.m_RightWidgetGroup.m_VersionsOverlay.VersionsOverlay.m_VersionArrow"));

		m_VersionFromText = TextWidget.Cast(root.FindWidget("Height.Overlay.LineElements.HorizontalLayout.m_RightWidgetGroup.m_VersionsOverlay.VersionsOverlay.m_VersionFromText"));

		m_AddonSizeIcon = ImageWidget.Cast(root.FindWidget("Height.Overlay.LineElements.HorizontalLayout.m_RightWidgetGroup.m_AddonSizeOverlay.AddonSizeOverlay.Scale1.AddonSizeIcon"));
		
		return true;
	}
};
