// Autogenerated by the Generate Class from Layout plugin, version 0.2.0
// Layout file: UI/layouts/Menus/ContentBrowser/DownloadManager/DownloadManager_ProgressIndicator.layout

class SCR_DownloadManager_ProgressIndicatorWidgets
{
	static const ResourceName s_sLayout = "{5DE10779C8972DC5}UI/layouts/Menus/ContentBrowser/DownloadManager/DownloadManager_ProgressIndicator.layout";
	ResourceName GetLayout() { return s_sLayout; }

	ProgressBarWidget m_ProgressBar;

	TextWidget m_StateText;

	HorizontalLayoutWidget m_ProgressOverlay;

	TextWidget m_ProgressText;

	bool Init(Widget root)
	{
		m_ProgressBar = ProgressBarWidget.Cast(root.FindWidget("ProgressBar.m_ProgressBar"));

		m_StateText = TextWidget.Cast(root.FindWidget("m_StateText"));

		m_ProgressOverlay = HorizontalLayoutWidget.Cast(root.FindWidget("m_ProgressOverlay"));

		m_ProgressText = TextWidget.Cast(root.FindWidget("m_ProgressOverlay.m_ProgressText"));

		return true;
	}
};
