// Autogenerated by the Generate Class from Layout plugin v0.5.0
// Layout file: UI/layouts/Menus/ServerBrowser/DetailsMenu/ServerFullDialogContent.layout
class SCR_ServerFullDialogContentWidgets
{
	protected static const ResourceName LAYOUT = "{ABC1444F1353F6FA}UI/layouts/Menus/ServerBrowser/DetailsMenu/ServerFullDialogContent.layout";

	RichTextWidget m_wIPAddressText;

	ButtonWidget m_wIPAddressButton;
	SCR_ButtonComponent m_IPAddressButtonComponent;

	ImageWidget m_wDetailIcon_PasswordProtected;
	ImageWidget m_wDetailIcon_CrossPlatform;
	ImageWidget m_wDetailIcon_Modded;
	RichTextWidget m_wDiscordText;

	ButtonWidget m_wDiscordButton;
	SCR_ButtonComponent m_DiscordButtonComponent;

	OverlayWidget m_wCurrentStateOverlay;
	RichTextWidget m_wCurrentState;
	OverlayWidget m_wQueueStateOverlay;
	RichTextWidget m_wQueueState;
	OverlayWidget m_wQueueMaxSizeOverlay;
	RichTextWidget m_wQueueMaxSize;
	OverlayWidget m_wQueueWaitTimeOverlay;
	RichTextWidget m_wQueueWaitTime;
	VerticalLayoutWidget m_wExplanationEnqueuedWrapper;
	RichTextWidget m_wTimeSinceJoiningQueue;
	RichTextWidget m_wExplanationFull;

	//------------------------------------------------------------------------------------------------
	bool Init(Widget root)
	{
		m_wIPAddressText = RichTextWidget.Cast(root.FindWidget("MessagesWrapper.MessagesFirstLine.IPAddressLayout.m_wIPAddressText"));

		m_wIPAddressButton = ButtonWidget.Cast(root.FindWidget("MessagesWrapper.MessagesFirstLine.IPAddressLayout.m_wIPAddressButton"));
		m_IPAddressButtonComponent = SCR_ButtonComponent.Cast(m_wIPAddressButton.FindHandler(SCR_ButtonComponent));

		m_wDetailIcon_PasswordProtected = ImageWidget.Cast(root.FindWidget("MessagesWrapper.MessagesFirstLine.DetailIconsLayout.m_wDetailIcon_PasswordProtected"));
		m_wDetailIcon_CrossPlatform = ImageWidget.Cast(root.FindWidget("MessagesWrapper.MessagesFirstLine.DetailIconsLayout.m_wDetailIcon_CrossPlatform"));
		m_wDetailIcon_Modded = ImageWidget.Cast(root.FindWidget("MessagesWrapper.MessagesFirstLine.DetailIconsLayout.m_wDetailIcon_Modded"));
		m_wDiscordText = RichTextWidget.Cast(root.FindWidget("MessagesWrapper.MessagesSecondLine.DiscordLayout.m_wDiscordText"));

		m_wDiscordButton = ButtonWidget.Cast(root.FindWidget("MessagesWrapper.MessagesSecondLine.DiscordLayout.m_wDiscordButton"));
		m_DiscordButtonComponent = SCR_ButtonComponent.Cast(m_wDiscordButton.FindHandler(SCR_ButtonComponent));

		m_wCurrentStateOverlay = OverlayWidget.Cast(root.FindWidget("InfoSize.InfoWrapper.m_wCurrentStateOverlay"));
		m_wCurrentState = RichTextWidget.Cast(root.FindWidget("InfoSize.InfoWrapper.m_wCurrentStateOverlay.m_wCurrentState"));
		m_wQueueStateOverlay = OverlayWidget.Cast(root.FindWidget("InfoSize.InfoWrapper.m_wQueueStateOverlay"));
		m_wQueueState = RichTextWidget.Cast(root.FindWidget("InfoSize.InfoWrapper.m_wQueueStateOverlay.m_wQueueState"));
		m_wQueueMaxSizeOverlay = OverlayWidget.Cast(root.FindWidget("InfoSize.InfoWrapper.m_wQueueMaxSizeOverlay"));
		m_wQueueMaxSize = RichTextWidget.Cast(root.FindWidget("InfoSize.InfoWrapper.m_wQueueMaxSizeOverlay.m_wQueueMaxSize"));
		m_wQueueWaitTimeOverlay = OverlayWidget.Cast(root.FindWidget("InfoSize.InfoWrapper.m_wQueueWaitTimeOverlay"));
		m_wQueueWaitTime = RichTextWidget.Cast(root.FindWidget("InfoSize.InfoWrapper.m_wQueueWaitTimeOverlay.m_wQueueWaitTime"));
		m_wExplanationEnqueuedWrapper = VerticalLayoutWidget.Cast(root.FindWidget("ExplanationSize.ExplanationOverlay.m_wExplanationEnqueuedWrapper"));
		m_wTimeSinceJoiningQueue = RichTextWidget.Cast(root.FindWidget("ExplanationSize.ExplanationOverlay.m_wExplanationEnqueuedWrapper.m_wTimeSinceJoiningQueue"));
		m_wExplanationFull = RichTextWidget.Cast(root.FindWidget("ExplanationSize.ExplanationOverlay.m_wExplanationFull"));

		return true;
	}

	//------------------------------------------------------------------------------------------------
	ResourceName GetLayout()
	{
		return LAYOUT;
	}
}
