// Autogenerated by the Generate Class from Layout plugin v0.5.1
// Layout file: UI/layouts/Menus/ContentBrowser/AddonManager/AddonListTab/AddonLineBase.layout
class SCR_AddonLineBaseWidgets
{
	protected static const ResourceName LAYOUT = "{A40D588F6B8744EE}UI/layouts/Menus/ContentBrowser/AddonManager/AddonListTab/AddonLineBase.layout";

	SizeLayoutWidget m_wSizeMoveLeft;

	ButtonWidget m_wMoveLeftButton;
	SCR_ModularButtonComponent m_MoveLeftButtonComponent0;
	SCR_DynamicIconComponent m_MoveLeftButtonComponent1;

	SizeLayoutWidget m_wLeftSeparator;
	ImageWidget m_wItemTypeImage;
	RichTextWidget m_wNameText;
	HorizontalLayoutWidget m_wHorizontalState;
	RichTextWidget m_wStateText;

	ButtonWidget m_wIncompatibleButton;
	SCR_ModularButtonComponent m_IncompatibleButtonComponent0;
	SCR_DynamicIconComponent m_IncompatibleButtonComponent1;


	ButtonWidget m_wFixButton;
	SCR_ModularButtonComponent m_FixButtonComponent0;
	SCR_DynamicIconComponent m_FixButtonComponent1;


	ButtonWidget m_wRepairButton;
	SCR_ModularButtonComponent m_RepairButtonComponent0;
	SCR_DynamicIconComponent m_RepairButtonComponent1;


	ButtonWidget m_wUpdateButton;
	SCR_ModularButtonComponent m_UpdateButtonComponent0;
	SCR_DynamicIconComponent m_UpdateButtonComponent1;


	ButtonWidget m_wDeleteButton;
	SCR_ModularButtonComponent m_DeleteButtonComponent0;
	SCR_DynamicIconComponent m_DeleteButtonComponent1;

	SizeLayoutWidget m_wSizeMoveRight;

	ButtonWidget m_wMoveRightButton;
	SCR_ModularButtonComponent m_MoveRightButtonComponent0;
	SCR_DynamicIconComponent m_MoveRightButtonComponent1;

	SizeLayoutWidget m_wRightSeparator;

	//------------------------------------------------------------------------------------------------
	bool Init(notnull Widget root)
	{
		m_wSizeMoveLeft = SizeLayoutWidget.Cast(root.FindWidget("LineHeight.Overlay.LineContent.LineElements.m_SizeMoveLeft"));

		m_wMoveLeftButton = ButtonWidget.Cast(root.FindWidget("LineHeight.Overlay.LineContent.LineElements.m_SizeMoveLeft.m_MoveLeftButton"));
		m_MoveLeftButtonComponent0 = SCR_ModularButtonComponent.Cast(m_wMoveLeftButton.FindHandler(SCR_ModularButtonComponent));
		m_MoveLeftButtonComponent1 = SCR_DynamicIconComponent.Cast(m_wMoveLeftButton.FindHandler(SCR_DynamicIconComponent));

		m_wLeftSeparator = SizeLayoutWidget.Cast(root.FindWidget("LineHeight.Overlay.LineContent.LineElements.m_LeftSeparator"));
		m_wItemTypeImage = ImageWidget.Cast(root.FindWidget("LineHeight.Overlay.LineContent.LineElements.HorizontalLayoutName.m_ItemTypeImage"));
		m_wNameText = RichTextWidget.Cast(root.FindWidget("LineHeight.Overlay.LineContent.LineElements.HorizontalLayoutName.FrameName.ContentWrapper.m_NameText"));
		m_wHorizontalState = HorizontalLayoutWidget.Cast(root.FindWidget("LineHeight.Overlay.LineContent.LineElements.SizeLayoutState.m_HorizontalState"));
		m_wStateText = RichTextWidget.Cast(root.FindWidget("LineHeight.Overlay.LineContent.LineElements.SizeLayoutState.m_HorizontalState.m_StateText"));

		m_wIncompatibleButton = ButtonWidget.Cast(root.FindWidget("LineHeight.Overlay.LineContent.LineElements.SizeLayoutWarnings.HorizontalLayoutWarnings.m_IncompatibleButton"));
		m_IncompatibleButtonComponent0 = SCR_ModularButtonComponent.Cast(m_wIncompatibleButton.FindHandler(SCR_ModularButtonComponent));
		m_IncompatibleButtonComponent1 = SCR_DynamicIconComponent.Cast(m_wIncompatibleButton.FindHandler(SCR_DynamicIconComponent));


		m_wFixButton = ButtonWidget.Cast(root.FindWidget("LineHeight.Overlay.LineContent.LineElements.SizeLayoutWarnings.HorizontalLayoutWarnings.m_FixButton"));
		m_FixButtonComponent0 = SCR_ModularButtonComponent.Cast(m_wFixButton.FindHandler(SCR_ModularButtonComponent));
		m_FixButtonComponent1 = SCR_DynamicIconComponent.Cast(m_wFixButton.FindHandler(SCR_DynamicIconComponent));


		m_wRepairButton = ButtonWidget.Cast(root.FindWidget("LineHeight.Overlay.LineContent.LineElements.SizeLayoutWarnings.HorizontalLayoutWarnings.m_RepairButton"));
		m_RepairButtonComponent0 = SCR_ModularButtonComponent.Cast(m_wRepairButton.FindHandler(SCR_ModularButtonComponent));
		m_RepairButtonComponent1 = SCR_DynamicIconComponent.Cast(m_wRepairButton.FindHandler(SCR_DynamicIconComponent));


		m_wUpdateButton = ButtonWidget.Cast(root.FindWidget("LineHeight.Overlay.LineContent.LineElements.SizeLayoutWarnings.HorizontalLayoutWarnings.m_UpdateButton"));
		m_UpdateButtonComponent0 = SCR_ModularButtonComponent.Cast(m_wUpdateButton.FindHandler(SCR_ModularButtonComponent));
		m_UpdateButtonComponent1 = SCR_DynamicIconComponent.Cast(m_wUpdateButton.FindHandler(SCR_DynamicIconComponent));


		m_wDeleteButton = ButtonWidget.Cast(root.FindWidget("LineHeight.Overlay.LineContent.LineElements.SizeLayoutDeleteButton.m_DeleteButton"));
		m_DeleteButtonComponent0 = SCR_ModularButtonComponent.Cast(m_wDeleteButton.FindHandler(SCR_ModularButtonComponent));
		m_DeleteButtonComponent1 = SCR_DynamicIconComponent.Cast(m_wDeleteButton.FindHandler(SCR_DynamicIconComponent));

		m_wSizeMoveRight = SizeLayoutWidget.Cast(root.FindWidget("LineHeight.Overlay.LineContent.LineElements.m_SizeMoveRight"));

		m_wMoveRightButton = ButtonWidget.Cast(root.FindWidget("LineHeight.Overlay.LineContent.LineElements.m_SizeMoveRight.m_MoveRightButton"));
		m_MoveRightButtonComponent0 = SCR_ModularButtonComponent.Cast(m_wMoveRightButton.FindHandler(SCR_ModularButtonComponent));
		m_MoveRightButtonComponent1 = SCR_DynamicIconComponent.Cast(m_wMoveRightButton.FindHandler(SCR_DynamicIconComponent));

		m_wRightSeparator = SizeLayoutWidget.Cast(root.FindWidget("LineHeight.Overlay.LineContent.LineElements.m_RightSeparator"));

		return true;
	}

	//------------------------------------------------------------------------------------------------
	ResourceName GetLayout()
	{
		return LAYOUT;
	}
}
