// Autogenerated by the Generate Class from Layout plugin, version 0.3.0
// Layout file: UI/layouts/Menus/ContentBrowser/AddonManager/AddonsTools/AddonsPresets/AddonsPresetSubMenu.layout

class SCR_AddonsPresetSubMenuWidgets
{
	static const ResourceName s_sLayout = "{DD79194A2478216B}UI/layouts/Menus/ContentBrowser/AddonManager/AddonsTools/AddonsPresets/AddonsPresetSubMenu.layout";
	ResourceName GetLayout() { return s_sLayout; }

	ButtonWidget m_ButonNewPreset;
	SCR_ModularButtonComponent m_ButonNewPresetComponent;

	ScrollLayoutWidget m_ScrollPresets;
	SCR_ListBoxComponent m_ScrollPresetsComponent;

	bool Init(Widget root)
	{
		m_ButonNewPreset = ButtonWidget.Cast(root.FindWidget("VerticalList.m_ButonNewPreset"));
		m_ButonNewPresetComponent = SCR_ModularButtonComponent.Cast(m_ButonNewPreset.FindHandler(SCR_ModularButtonComponent));

		m_ScrollPresets = ScrollLayoutWidget.Cast(root.FindWidget("VerticalList.m_ScrollPresets"));
		m_ScrollPresetsComponent = SCR_ListBoxComponent.Cast(m_ScrollPresets.FindHandler(SCR_ListBoxComponent));

		return true;
	}
}
