// Autogenerated by the Generate Class from Layout plugin, version 0.3.0
// Layout file: UI/layouts/Menus/ContentBrowser/AddonManager/AddonsTools/AddonsExport/AddonsExportSubMenu.layout

class SCR_AddonsExportSubMenuWidgets
{
	static const ResourceName s_sLayout = "{CA5E372C0317FF86}UI/layouts/Menus/ContentBrowser/AddonManager/AddonsTools/AddonsExport/AddonsExportSubMenu.layout";
	ResourceName GetLayout() { return s_sLayout; }

	ScrollLayoutWidget m_ScrollLayout;

	TextWidget m_GenContent;

	bool Init(Widget root)
	{
		m_ScrollLayout = ScrollLayoutWidget.Cast(root.FindWidget("Overlay.m_ScrollLayout"));

		m_GenContent = TextWidget.Cast(root.FindWidget("Overlay.m_ScrollLayout.m_GenContent"));

		return true;
	}
}
