// Autogenerated by the Generate Class from Layout plugin v0.5.1
// Layout file: UI/layouts/Tasks/CurrentTask.layout
class SCR_CurrentTaskWidgets
{
	protected static const ResourceName LAYOUT = "{EE9497AB43F556F9}UI/layouts/Tasks/CurrentTask.layout";

	ButtonWidget m_wTaskIconButton;
	SCR_ModularButtonComponent m_TaskIconButtonComponent;

	SizeLayoutWidget m_wTaskIcon;
	OverlayWidget m_wIconOverlay;
	ImageWidget m_wTaskIconBackground;
	ImageWidget m_wTaskIconOutline;
	ImageWidget m_wTaskIconSymbol;
	OverlayWidget m_wOverlayTaskStates;
	OverlayWidget m_wIconOverlayFailed;
	ImageWidget m_wTaskIconFailedBG;
	ImageWidget m_wTaskIconFailed;
	OverlayWidget m_wIconOverlayFinished;
	ImageWidget m_wTaskIconFinishedBG;
	ImageWidget m_wTaskIconFinished;
	OverlayWidget m_wIconOverlayCancelled;
	ImageWidget m_wTaskIconCancelledBG;
	ImageWidget m_wTaskIconCancelled;
	RichTextWidget m_wTaskTitle;

	SizeLayoutWidget m_wProgressBar;
	SCR_WLibProgressBarComponent m_ProgressBarComponent;

	RichTextWidget m_wTaskDescription;

	//------------------------------------------------------------------------------------------------
	bool Init(notnull Widget root)
	{
		m_wTaskIconButton = ButtonWidget.Cast(root.FindWidget("SizeLayout.Overlay.VerticalLayout.HorizontalLayout.m_wTaskIconButton"));
		m_TaskIconButtonComponent = SCR_ModularButtonComponent.Cast(m_wTaskIconButton.FindHandler(SCR_ModularButtonComponent));

		m_wTaskIcon = SizeLayoutWidget.Cast(root.FindWidget("SizeLayout.Overlay.VerticalLayout.HorizontalLayout.m_wTaskIconButton.m_wTaskIcon"));
		m_wIconOverlay = OverlayWidget.Cast(root.FindWidget("SizeLayout.Overlay.VerticalLayout.HorizontalLayout.m_wTaskIconButton.m_wTaskIcon.OverlayTaskIcon.m_wIconOverlay"));
		m_wTaskIconBackground = ImageWidget.Cast(root.FindWidget("SizeLayout.Overlay.VerticalLayout.HorizontalLayout.m_wTaskIconButton.m_wTaskIcon.OverlayTaskIcon.m_wIconOverlay.m_wTaskIconBackground"));
		m_wTaskIconOutline = ImageWidget.Cast(root.FindWidget("SizeLayout.Overlay.VerticalLayout.HorizontalLayout.m_wTaskIconButton.m_wTaskIcon.OverlayTaskIcon.m_wIconOverlay.m_wTaskIconOutline"));
		m_wTaskIconSymbol = ImageWidget.Cast(root.FindWidget("SizeLayout.Overlay.VerticalLayout.HorizontalLayout.m_wTaskIconButton.m_wTaskIcon.OverlayTaskIcon.m_wIconOverlay.m_wTaskIconSymbol"));
		m_wOverlayTaskStates = OverlayWidget.Cast(root.FindWidget("SizeLayout.Overlay.VerticalLayout.HorizontalLayout.m_wTaskIconButton.m_wTaskIcon.OverlayTaskIcon.m_wOverlayTaskStates"));
		m_wIconOverlayFailed = OverlayWidget.Cast(root.FindWidget("SizeLayout.Overlay.VerticalLayout.HorizontalLayout.m_wTaskIconButton.m_wTaskIcon.OverlayTaskIcon.m_wOverlayTaskStates.m_wIconOverlayFailed"));
		m_wTaskIconFailedBG = ImageWidget.Cast(root.FindWidget("SizeLayout.Overlay.VerticalLayout.HorizontalLayout.m_wTaskIconButton.m_wTaskIcon.OverlayTaskIcon.m_wOverlayTaskStates.m_wIconOverlayFailed.m_wTaskIconFailedBG"));
		m_wTaskIconFailed = ImageWidget.Cast(root.FindWidget("SizeLayout.Overlay.VerticalLayout.HorizontalLayout.m_wTaskIconButton.m_wTaskIcon.OverlayTaskIcon.m_wOverlayTaskStates.m_wIconOverlayFailed.m_wTaskIconFailed"));
		m_wIconOverlayFinished = OverlayWidget.Cast(root.FindWidget("SizeLayout.Overlay.VerticalLayout.HorizontalLayout.m_wTaskIconButton.m_wTaskIcon.OverlayTaskIcon.m_wOverlayTaskStates.m_wIconOverlayFinished"));
		m_wTaskIconFinishedBG = ImageWidget.Cast(root.FindWidget("SizeLayout.Overlay.VerticalLayout.HorizontalLayout.m_wTaskIconButton.m_wTaskIcon.OverlayTaskIcon.m_wOverlayTaskStates.m_wIconOverlayFinished.m_wTaskIconFinishedBG"));
		m_wTaskIconFinished = ImageWidget.Cast(root.FindWidget("SizeLayout.Overlay.VerticalLayout.HorizontalLayout.m_wTaskIconButton.m_wTaskIcon.OverlayTaskIcon.m_wOverlayTaskStates.m_wIconOverlayFinished.m_wTaskIconFinished"));
		m_wIconOverlayCancelled = OverlayWidget.Cast(root.FindWidget("SizeLayout.Overlay.VerticalLayout.HorizontalLayout.m_wTaskIconButton.m_wTaskIcon.OverlayTaskIcon.m_wOverlayTaskStates.m_wIconOverlayCancelled"));
		m_wTaskIconCancelledBG = ImageWidget.Cast(root.FindWidget("SizeLayout.Overlay.VerticalLayout.HorizontalLayout.m_wTaskIconButton.m_wTaskIcon.OverlayTaskIcon.m_wOverlayTaskStates.m_wIconOverlayCancelled.m_wTaskIconCancelledBG"));
		m_wTaskIconCancelled = ImageWidget.Cast(root.FindWidget("SizeLayout.Overlay.VerticalLayout.HorizontalLayout.m_wTaskIconButton.m_wTaskIcon.OverlayTaskIcon.m_wOverlayTaskStates.m_wIconOverlayCancelled.m_wTaskIconCancelled"));
		m_wTaskTitle = RichTextWidget.Cast(root.FindWidget("SizeLayout.Overlay.VerticalLayout.HorizontalLayout.VerticalLayout.m_wTaskTitle"));

		m_wProgressBar = SizeLayoutWidget.Cast(root.FindWidget("SizeLayout.Overlay.VerticalLayout.HorizontalLayout.VerticalLayout.m_wProgressBar"));
		m_ProgressBarComponent = SCR_WLibProgressBarComponent.Cast(m_wProgressBar.FindHandler(SCR_WLibProgressBarComponent));

		m_wTaskDescription = RichTextWidget.Cast(root.FindWidget("SizeLayout.Overlay.VerticalLayout.m_wTaskDescription"));

		return true;
	}

	//------------------------------------------------------------------------------------------------
	ResourceName GetLayout()
	{
		return LAYOUT;
	}
}
