// Autogenerated by the Generate Class from Layout plugin v0.5.1
// Layout file: UI/layouts/Task/AssignedGroupLabel.layout
class SCR_AssignedGroupLabelWidgets
{
	protected static const ResourceName LAYOUT = "{070989E0DF33DAD9}UI/layouts/Task/AssignedGroupLabel.layout";

	ImageWidget m_wGroupIcon;
	TextWidget m_wGroupName;

	//------------------------------------------------------------------------------------------------
	bool Init(notnull Widget root)
	{
		m_wGroupIcon = ImageWidget.Cast(root.FindWidget("AssignedGroup.Overlay.HorizontalLayout.SizeIcon.m_wGroupIcon"));
		m_wGroupName = TextWidget.Cast(root.FindWidget("AssignedGroup.Overlay.HorizontalLayout.m_wGroupName"));

		return true;
	}

	//------------------------------------------------------------------------------------------------
	ResourceName GetLayout()
	{
		return LAYOUT;
	}
}
