// Autogenerated by the Generate Class from Layout plugin v0.5.1
// Layout file: UI/layouts/Task/TaskList.layout
class SCR_TaskListWidgets
{
	protected static const ResourceName LAYOUT = "{63125FB8AA3064FC}UI/layouts/Task/TaskList.layout";

	SizeLayoutWidget m_wSizeLayout;
	HorizontalLayoutWidget m_wTabsWrapper;
	ScrollLayoutWidget m_wTasksListScroll;
	VerticalLayoutWidget m_wTasksWrapper;

	ButtonWidget m_wHideTasksButton;
	SCR_InputButtonComponent m_HideTasksButtonComponent;

	OverlayWidget m_wOverlay;
	ImageWidget m_wGlow;
	ImageWidget m_wOutlineClear;
	ImageWidget m_wOutline;
	ImageWidget m_wButtonImgGlow;
	ImageWidget m_wKeyBG;
	ImageWidget m_wDoubleTabIndicator;
	ImageWidget m_wHoldIndicator;
	ImageWidget m_wButtonImg;
	VerticalLayoutWidget m_wVerticalLayout0;
	RichTextWidget m_wButtonText;

	OverlayWidget m_wTaskListEntryDescription;
	SCR_TaskListEntryDescriptionUIComponent m_TaskListEntryDescriptionComponent;


	ButtonWidget m_wTaskIconButton;
	SCR_ModularButtonComponent m_TaskIconButtonComponent;

	SizeLayoutWidget m_wTaskIcon;
	OverlayWidget m_wIconOverlay;
	ImageWidget m_wTaskIconBackground;
	ImageWidget m_wTaskIconOutline;
	ImageWidget m_wTaskIconSymbol;
	OverlayWidget m_wOverlayTaskStates;
	OverlayWidget m_wIconOverlayFailed;
	ImageWidget m_wTaskIconFailedBG;
	ImageWidget m_wTaskIconFailed;
	OverlayWidget m_wIconOverlayFinished;
	ImageWidget m_wTaskIconFinishedBG;
	ImageWidget m_wTaskIconFinished;
	OverlayWidget m_wIconOverlayCancelled;
	ImageWidget m_wTaskIconCancelledBG;
	ImageWidget m_wTaskIconCancelled;

	FrameWidget m_wTitleFrame;
	SCR_HorizontalScrollAnimationComponent m_TitleFrameComponent;

	RichTextWidget m_wTaskTitle;
	SizeLayoutWidget m_wAssignedPlayersCount;
	TextWidget m_wAssignedCountText;
	ImageWidget m_wAssignedCountIcon;

	ScrollLayoutWidget m_wDescriptionScrollLayout;
	SCR_GamepadScrollComponent m_DescriptionScrollLayoutComponent;

	RichTextWidget m_wDescription;
	SizeLayoutWidget m_wChildTasks;
	TextWidget m_wChildTaskText;
	ScrollLayoutWidget m_wTasksScrollLayout;
	VerticalLayoutWidget m_wChildTasksWrapper;
	Widget m_wAssignedPlayersWrapper;

	FrameWidget m_wTaskAssignGroupList;
	SCR_TaskAssignGroupListUIComponent m_TaskAssignGroupListComponent;

	SizeLayoutWidget m_wTaskStateWrapper;
	OverlayWidget m_wOverlayTaskStatesFooter;
	OverlayWidget m_wStateIconOverlayFailed;
	OverlayWidget m_wStateIconOverlayFinished;
	OverlayWidget m_wStateIconOverlayCancelled;
	TextWidget m_wTaskStateText;

	ButtonWidget m_wButtonShowMap;
	SCR_InputButtonComponent m_ButtonShowMapComponent0;
	SCR_TaskListFocusUIComponent m_ButtonShowMapComponent1;


	ButtonWidget m_wButtonAssignTask;
	SCR_InputButtonComponent m_ButtonAssignTaskComponent0;
	SCR_TaskListFocusUIComponent m_ButtonAssignTaskComponent1;


	ButtonWidget m_wButtonOpenAssignGroupList;
	SCR_InputButtonComponent m_ButtonOpenAssignGroupListComponent0;
	SCR_TaskListFocusUIComponent m_ButtonOpenAssignGroupListComponent1;


	//------------------------------------------------------------------------------------------------
	bool Init(notnull Widget root)
	{
		m_wSizeLayout = SizeLayoutWidget.Cast(root.FindWidget("m_wSizeLayout"));
		m_wTabsWrapper = HorizontalLayoutWidget.Cast(root.FindWidget("m_wSizeLayout.Overlay.VerticalLayout.VerticalLayout.m_wTabsWrapper"));
		m_wTasksListScroll = ScrollLayoutWidget.Cast(root.FindWidget("m_wSizeLayout.Overlay.VerticalLayout.Overlay.m_wTasksListScroll"));
		m_wTasksWrapper = VerticalLayoutWidget.Cast(root.FindWidget("m_wSizeLayout.Overlay.VerticalLayout.Overlay.m_wTasksListScroll.m_wTasksWrapper"));

		m_wHideTasksButton = ButtonWidget.Cast(root.FindWidget("m_wSizeLayout.Overlay.VerticalLayout.NavButtons.m_wHideTasksButton"));
		m_HideTasksButtonComponent = SCR_InputButtonComponent.Cast(m_wHideTasksButton.FindHandler(SCR_InputButtonComponent));

		m_wOverlay = OverlayWidget.Cast(root.FindWidget("m_wSizeLayout.Overlay.VerticalLayout.NavButtons.m_wHideTasksButton.HorizontalLayout1.HorizontalLayout0.InputButtonDisplayRoot.m_Overlay"));
		m_wGlow = ImageWidget.Cast(root.FindWidget("m_wSizeLayout.Overlay.VerticalLayout.NavButtons.m_wHideTasksButton.HorizontalLayout1.HorizontalLayout0.InputButtonDisplayRoot.m_Overlay.m_Glow"));
		m_wOutlineClear = ImageWidget.Cast(root.FindWidget("m_wSizeLayout.Overlay.VerticalLayout.NavButtons.m_wHideTasksButton.HorizontalLayout1.HorizontalLayout0.InputButtonDisplayRoot.m_Overlay.m_OutlineClear"));
		m_wOutline = ImageWidget.Cast(root.FindWidget("m_wSizeLayout.Overlay.VerticalLayout.NavButtons.m_wHideTasksButton.HorizontalLayout1.HorizontalLayout0.InputButtonDisplayRoot.m_Overlay.m_Outline"));
		m_wButtonImgGlow = ImageWidget.Cast(root.FindWidget("m_wSizeLayout.Overlay.VerticalLayout.NavButtons.m_wHideTasksButton.HorizontalLayout1.HorizontalLayout0.InputButtonDisplayRoot.m_Overlay.Shadow_Overlay.m_ButtonImgGlow"));
		m_wKeyBG = ImageWidget.Cast(root.FindWidget("m_wSizeLayout.Overlay.VerticalLayout.NavButtons.m_wHideTasksButton.HorizontalLayout1.HorizontalLayout0.InputButtonDisplayRoot.m_Overlay.Overlay0.m_KeyBG"));
		m_wDoubleTabIndicator = ImageWidget.Cast(root.FindWidget("m_wSizeLayout.Overlay.VerticalLayout.NavButtons.m_wHideTasksButton.HorizontalLayout1.HorizontalLayout0.InputButtonDisplayRoot.m_Overlay.Overlay0.m_DoubleTabIndicator"));
		m_wHoldIndicator = ImageWidget.Cast(root.FindWidget("m_wSizeLayout.Overlay.VerticalLayout.NavButtons.m_wHideTasksButton.HorizontalLayout1.HorizontalLayout0.InputButtonDisplayRoot.m_Overlay.Frame0.m_HoldIndicator"));
		m_wButtonImg = ImageWidget.Cast(root.FindWidget("m_wSizeLayout.Overlay.VerticalLayout.NavButtons.m_wHideTasksButton.HorizontalLayout1.HorizontalLayout0.InputButtonDisplayRoot.m_Overlay.m_ButtonImg"));
		m_wVerticalLayout0 = VerticalLayoutWidget.Cast(root.FindWidget("m_wSizeLayout.Overlay.VerticalLayout.NavButtons.m_wHideTasksButton.HorizontalLayout1.HorizontalLayout0.InputButtonDisplayRoot.m_Overlay.SizeLayout0.m_VerticalLayout0"));
		m_wButtonText = RichTextWidget.Cast(root.FindWidget("m_wSizeLayout.Overlay.VerticalLayout.NavButtons.m_wHideTasksButton.HorizontalLayout1.HorizontalLayout0.InputButtonDisplayRoot.m_Overlay.SizeLayout0.m_VerticalLayout0.m_ButtonText"));

		m_wTaskListEntryDescription = OverlayWidget.Cast(root.FindWidget("m_wTaskListEntryDescription"));
		m_TaskListEntryDescriptionComponent = SCR_TaskListEntryDescriptionUIComponent.Cast(m_wTaskListEntryDescription.FindHandler(SCR_TaskListEntryDescriptionUIComponent));


		m_wTaskIconButton = ButtonWidget.Cast(root.FindWidget("m_wTaskListEntryDescription.SizeLayout.DescriptionOverlay.VerticalLayout.Header.m_wTaskIconButton"));
		m_TaskIconButtonComponent = SCR_ModularButtonComponent.Cast(m_wTaskIconButton.FindHandler(SCR_ModularButtonComponent));

		m_wTaskIcon = SizeLayoutWidget.Cast(root.FindWidget("m_wTaskListEntryDescription.SizeLayout.DescriptionOverlay.VerticalLayout.Header.m_wTaskIconButton.m_wTaskIcon"));
		m_wIconOverlay = OverlayWidget.Cast(root.FindWidget("m_wTaskListEntryDescription.SizeLayout.DescriptionOverlay.VerticalLayout.Header.m_wTaskIconButton.m_wTaskIcon.OverlayTaskIcon.m_wIconOverlay"));
		m_wTaskIconBackground = ImageWidget.Cast(root.FindWidget("m_wTaskListEntryDescription.SizeLayout.DescriptionOverlay.VerticalLayout.Header.m_wTaskIconButton.m_wTaskIcon.OverlayTaskIcon.m_wIconOverlay.m_wTaskIconBackground"));
		m_wTaskIconOutline = ImageWidget.Cast(root.FindWidget("m_wTaskListEntryDescription.SizeLayout.DescriptionOverlay.VerticalLayout.Header.m_wTaskIconButton.m_wTaskIcon.OverlayTaskIcon.m_wIconOverlay.m_wTaskIconOutline"));
		m_wTaskIconSymbol = ImageWidget.Cast(root.FindWidget("m_wTaskListEntryDescription.SizeLayout.DescriptionOverlay.VerticalLayout.Header.m_wTaskIconButton.m_wTaskIcon.OverlayTaskIcon.m_wIconOverlay.m_wTaskIconSymbol"));
		m_wOverlayTaskStates = OverlayWidget.Cast(root.FindWidget("m_wTaskListEntryDescription.SizeLayout.DescriptionOverlay.VerticalLayout.Header.m_wTaskIconButton.m_wTaskIcon.OverlayTaskIcon.m_wOverlayTaskStates"));
		m_wIconOverlayFailed = OverlayWidget.Cast(root.FindWidget("m_wTaskListEntryDescription.SizeLayout.DescriptionOverlay.VerticalLayout.Header.m_wTaskIconButton.m_wTaskIcon.OverlayTaskIcon.m_wOverlayTaskStates.m_wIconOverlayFailed"));
		m_wTaskIconFailedBG = ImageWidget.Cast(root.FindWidget("m_wTaskListEntryDescription.SizeLayout.DescriptionOverlay.VerticalLayout.Header.m_wTaskIconButton.m_wTaskIcon.OverlayTaskIcon.m_wOverlayTaskStates.m_wIconOverlayFailed.m_wTaskIconFailedBG"));
		m_wTaskIconFailed = ImageWidget.Cast(root.FindWidget("m_wTaskListEntryDescription.SizeLayout.DescriptionOverlay.VerticalLayout.Header.m_wTaskIconButton.m_wTaskIcon.OverlayTaskIcon.m_wOverlayTaskStates.m_wIconOverlayFailed.m_wTaskIconFailed"));
		m_wIconOverlayFinished = OverlayWidget.Cast(root.FindWidget("m_wTaskListEntryDescription.SizeLayout.DescriptionOverlay.VerticalLayout.Header.m_wTaskIconButton.m_wTaskIcon.OverlayTaskIcon.m_wOverlayTaskStates.m_wIconOverlayFinished"));
		m_wTaskIconFinishedBG = ImageWidget.Cast(root.FindWidget("m_wTaskListEntryDescription.SizeLayout.DescriptionOverlay.VerticalLayout.Header.m_wTaskIconButton.m_wTaskIcon.OverlayTaskIcon.m_wOverlayTaskStates.m_wIconOverlayFinished.m_wTaskIconFinishedBG"));
		m_wTaskIconFinished = ImageWidget.Cast(root.FindWidget("m_wTaskListEntryDescription.SizeLayout.DescriptionOverlay.VerticalLayout.Header.m_wTaskIconButton.m_wTaskIcon.OverlayTaskIcon.m_wOverlayTaskStates.m_wIconOverlayFinished.m_wTaskIconFinished"));
		m_wIconOverlayCancelled = OverlayWidget.Cast(root.FindWidget("m_wTaskListEntryDescription.SizeLayout.DescriptionOverlay.VerticalLayout.Header.m_wTaskIconButton.m_wTaskIcon.OverlayTaskIcon.m_wOverlayTaskStates.m_wIconOverlayCancelled"));
		m_wTaskIconCancelledBG = ImageWidget.Cast(root.FindWidget("m_wTaskListEntryDescription.SizeLayout.DescriptionOverlay.VerticalLayout.Header.m_wTaskIconButton.m_wTaskIcon.OverlayTaskIcon.m_wOverlayTaskStates.m_wIconOverlayCancelled.m_wTaskIconCancelledBG"));
		m_wTaskIconCancelled = ImageWidget.Cast(root.FindWidget("m_wTaskListEntryDescription.SizeLayout.DescriptionOverlay.VerticalLayout.Header.m_wTaskIconButton.m_wTaskIcon.OverlayTaskIcon.m_wOverlayTaskStates.m_wIconOverlayCancelled.m_wTaskIconCancelled"));

		m_wTitleFrame = FrameWidget.Cast(root.FindWidget("m_wTaskListEntryDescription.SizeLayout.DescriptionOverlay.VerticalLayout.Header.SizeLayout.m_wTitleFrame"));
		m_TitleFrameComponent = SCR_HorizontalScrollAnimationComponent.Cast(m_wTitleFrame.FindHandler(SCR_HorizontalScrollAnimationComponent));

		m_wTaskTitle = RichTextWidget.Cast(root.FindWidget("m_wTaskListEntryDescription.SizeLayout.DescriptionOverlay.VerticalLayout.Header.SizeLayout.m_wTitleFrame.ContentWrapper.m_wTaskTitle"));
		m_wAssignedPlayersCount = SizeLayoutWidget.Cast(root.FindWidget("m_wTaskListEntryDescription.SizeLayout.DescriptionOverlay.VerticalLayout.Header.m_wAssignedPlayersCount"));
		m_wAssignedCountText = TextWidget.Cast(root.FindWidget("m_wTaskListEntryDescription.SizeLayout.DescriptionOverlay.VerticalLayout.Header.m_wAssignedPlayersCount.HorizontalLayout.m_wAssignedCountText"));
		m_wAssignedCountIcon = ImageWidget.Cast(root.FindWidget("m_wTaskListEntryDescription.SizeLayout.DescriptionOverlay.VerticalLayout.Header.m_wAssignedPlayersCount.HorizontalLayout.m_wAssignedCountIcon"));

		m_wDescriptionScrollLayout = ScrollLayoutWidget.Cast(root.FindWidget("m_wTaskListEntryDescription.SizeLayout.DescriptionOverlay.VerticalLayout.Overlay.m_wDescriptionScrollLayout"));
		m_DescriptionScrollLayoutComponent = SCR_GamepadScrollComponent.Cast(m_wDescriptionScrollLayout.FindHandler(SCR_GamepadScrollComponent));

		m_wDescription = RichTextWidget.Cast(root.FindWidget("m_wTaskListEntryDescription.SizeLayout.DescriptionOverlay.VerticalLayout.Overlay.m_wDescriptionScrollLayout.m_wDescription"));
		m_wChildTasks = SizeLayoutWidget.Cast(root.FindWidget("m_wTaskListEntryDescription.SizeLayout.DescriptionOverlay.VerticalLayout.m_wChildTasks"));
		m_wChildTaskText = TextWidget.Cast(root.FindWidget("m_wTaskListEntryDescription.SizeLayout.DescriptionOverlay.VerticalLayout.m_wChildTasks.VertialLayout.m_wChildTaskText"));
		m_wTasksScrollLayout = ScrollLayoutWidget.Cast(root.FindWidget("m_wTaskListEntryDescription.SizeLayout.DescriptionOverlay.VerticalLayout.m_wChildTasks.VertialLayout.m_wTasksScrollLayout"));
		m_wChildTasksWrapper = VerticalLayoutWidget.Cast(root.FindWidget("m_wTaskListEntryDescription.SizeLayout.DescriptionOverlay.VerticalLayout.m_wChildTasks.VertialLayout.m_wTasksScrollLayout.m_wChildTasksWrapper"));
		m_wAssignedPlayersWrapper = root.FindWidget("m_wTaskListEntryDescription.SizeLayout.DescriptionOverlay.VerticalLayout.FooterWrapper.m_wAssignedPlayersWrapper");

		m_wTaskAssignGroupList = FrameWidget.Cast(root.FindWidget("m_wTaskListEntryDescription.SizeLayout.DescriptionOverlay.VerticalLayout.FooterWrapper.m_wTaskAssignGroupList"));
		m_TaskAssignGroupListComponent = SCR_TaskAssignGroupListUIComponent.Cast(m_wTaskAssignGroupList.FindHandler(SCR_TaskAssignGroupListUIComponent));

		m_wTaskStateWrapper = SizeLayoutWidget.Cast(root.FindWidget("m_wTaskListEntryDescription.SizeLayout.DescriptionOverlay.VerticalLayout.FooterWrapper.m_wTaskStateWrapper"));
		m_wOverlayTaskStatesFooter = OverlayWidget.Cast(root.FindWidget("m_wTaskListEntryDescription.SizeLayout.DescriptionOverlay.VerticalLayout.FooterWrapper.m_wTaskStateWrapper.HorizontalLayout.m_wOverlayTaskStatesFooter"));
		m_wStateIconOverlayFailed = OverlayWidget.Cast(root.FindWidget("m_wTaskListEntryDescription.SizeLayout.DescriptionOverlay.VerticalLayout.FooterWrapper.m_wTaskStateWrapper.HorizontalLayout.m_wOverlayTaskStatesFooter.m_wStateIconOverlayFailed"));
		m_wStateIconOverlayFinished = OverlayWidget.Cast(root.FindWidget("m_wTaskListEntryDescription.SizeLayout.DescriptionOverlay.VerticalLayout.FooterWrapper.m_wTaskStateWrapper.HorizontalLayout.m_wOverlayTaskStatesFooter.m_wStateIconOverlayFinished"));
		m_wStateIconOverlayCancelled = OverlayWidget.Cast(root.FindWidget("m_wTaskListEntryDescription.SizeLayout.DescriptionOverlay.VerticalLayout.FooterWrapper.m_wTaskStateWrapper.HorizontalLayout.m_wOverlayTaskStatesFooter.m_wStateIconOverlayCancelled"));
		m_wTaskStateText = TextWidget.Cast(root.FindWidget("m_wTaskListEntryDescription.SizeLayout.DescriptionOverlay.VerticalLayout.FooterWrapper.m_wTaskStateWrapper.HorizontalLayout.m_wTaskStateText"));

		m_wButtonShowMap = ButtonWidget.Cast(root.FindWidget("m_wTaskListEntryDescription.SizeLayout.DescriptionOverlay.VerticalLayout.FooterWrapper.Footer.m_wButtonShowMap"));
		m_ButtonShowMapComponent0 = SCR_InputButtonComponent.Cast(m_wButtonShowMap.FindHandler(SCR_InputButtonComponent));
		m_ButtonShowMapComponent1 = SCR_TaskListFocusUIComponent.Cast(m_wButtonShowMap.FindHandler(SCR_TaskListFocusUIComponent));


		m_wButtonAssignTask = ButtonWidget.Cast(root.FindWidget("m_wTaskListEntryDescription.SizeLayout.DescriptionOverlay.VerticalLayout.FooterWrapper.Footer.m_wButtonAssignTask"));
		m_ButtonAssignTaskComponent0 = SCR_InputButtonComponent.Cast(m_wButtonAssignTask.FindHandler(SCR_InputButtonComponent));
		m_ButtonAssignTaskComponent1 = SCR_TaskListFocusUIComponent.Cast(m_wButtonAssignTask.FindHandler(SCR_TaskListFocusUIComponent));


		m_wButtonOpenAssignGroupList = ButtonWidget.Cast(root.FindWidget("m_wTaskListEntryDescription.SizeLayout.DescriptionOverlay.VerticalLayout.FooterWrapper.Footer.m_wButtonOpenAssignGroupList"));
		m_ButtonOpenAssignGroupListComponent0 = SCR_InputButtonComponent.Cast(m_wButtonOpenAssignGroupList.FindHandler(SCR_InputButtonComponent));
		m_ButtonOpenAssignGroupListComponent1 = SCR_TaskListFocusUIComponent.Cast(m_wButtonOpenAssignGroupList.FindHandler(SCR_TaskListFocusUIComponent));


		return true;
	}

	//------------------------------------------------------------------------------------------------
	ResourceName GetLayout()
	{
		return LAYOUT;
	}
}
