// Autogenerated by the Generate Class from Layout plugin v0.5.1
// Layout file: UI/layouts/Task/AssignedPlayerLabel.layout
class SCR_AssignedPlayerLabelWidgets
{
	protected static const ResourceName LAYOUT = "{B568B88051EFA3FA}UI/layouts/Task/AssignedPlayerLabel.layout";

	ImageWidget m_wPlatformKindIcon;
	TextWidget m_wPlayerName;

	//------------------------------------------------------------------------------------------------
	bool Init(notnull Widget root)
	{
		m_wPlatformKindIcon = ImageWidget.Cast(root.FindWidget("AssignedPlayer.Overlay.HorizontalLayout.SizeIcon.m_wPlatformKindIcon"));
		m_wPlayerName = TextWidget.Cast(root.FindWidget("AssignedPlayer.Overlay.HorizontalLayout.m_wPlayerName"));

		return true;
	}

	//------------------------------------------------------------------------------------------------
	ResourceName GetLayout()
	{
		return LAYOUT;
	}
}
