// Autogenerated by the Generate Class from Layout plugin v0.5.1
// Layout file: UI/layouts/Task/TaskAssignGroupList.layout
class SCR_TaskAssignGroupListWidgets
{
	protected static const ResourceName LAYOUT = "{E86DF82258421D68}UI/layouts/Task/TaskAssignGroupList.layout";

	VerticalLayoutWidget m_wGroupEntries;
	TextWidget m_wNoRelevantGroupText;

	ButtonWidget m_wCloseAssingGroupList;
	SCR_InputButtonComponent m_CloseAssingGroupListComponent;


	ButtonWidget m_wConfirmGroupAssignmentButton;
	SCR_InputButtonComponent m_ConfirmGroupAssignmentButtonComponent;


	//------------------------------------------------------------------------------------------------
	bool Init(notnull Widget root)
	{
		m_wGroupEntries = VerticalLayoutWidget.Cast(root.FindWidget("Overlay0.VerticalLayout0.SizeLayout0.ScrollLayout0.Overlay0.m_wGroupEntries"));
		m_wNoRelevantGroupText = TextWidget.Cast(root.FindWidget("Overlay0.VerticalLayout0.SizeLayout0.ScrollLayout0.Overlay0.m_wNoRelevantGroupText"));

		m_wCloseAssingGroupList = ButtonWidget.Cast(root.FindWidget("Overlay0.VerticalLayout0.HorizontalLayout1.m_wCloseAssingGroupList"));
		m_CloseAssingGroupListComponent = SCR_InputButtonComponent.Cast(m_wCloseAssingGroupList.FindHandler(SCR_InputButtonComponent));


		m_wConfirmGroupAssignmentButton = ButtonWidget.Cast(root.FindWidget("Overlay0.VerticalLayout0.HorizontalLayout1.m_wConfirmGroupAssignmentButton"));
		m_ConfirmGroupAssignmentButtonComponent = SCR_InputButtonComponent.Cast(m_wConfirmGroupAssignmentButton.FindHandler(SCR_InputButtonComponent));


		return true;
	}

	//------------------------------------------------------------------------------------------------
	ResourceName GetLayout()
	{
		return LAYOUT;
	}
}
