// Autogenerated by the Generate Class from Layout plugin v0.5.1
// Layout file: UI/layouts/Task/TaskListEntryDescription.layout
class SCR_TaskListEntryDescriptionWidgets
{
	protected static const ResourceName LAYOUT = "{552EB1921B5C548C}UI/layouts/Task/TaskListEntryDescription.layout";

	ButtonWidget m_wTaskIconButton;
	SCR_ModularButtonComponent m_TaskIconButtonComponent;

	SizeLayoutWidget m_wTaskIcon;
	OverlayWidget m_wIconOverlay;
	ImageWidget m_wTaskIconBackground;
	ImageWidget m_wTaskIconOutline;
	ImageWidget m_wTaskIconSymbol;
	OverlayWidget m_wOverlayTaskStates;
	OverlayWidget m_wIconOverlayFailed;
	ImageWidget m_wTaskIconFailedBG;
	ImageWidget m_wTaskIconFailed;
	OverlayWidget m_wIconOverlayFinished;
	ImageWidget m_wTaskIconFinishedBG;
	ImageWidget m_wTaskIconFinished;
	OverlayWidget m_wIconOverlayCancelled;
	ImageWidget m_wTaskIconCancelledBG;
	ImageWidget m_wTaskIconCancelled;

	FrameWidget m_wTitleFrame;
	SCR_HorizontalScrollAnimationComponent m_TitleFrameComponent;

	RichTextWidget m_wTaskTitle;
	SizeLayoutWidget m_wAssignedPlayersCount;
	TextWidget m_wAssignedCountText;
	ImageWidget m_wAssignedCountIcon;
	FrameWidget m_wAuthorFrame;

	OverlayWidget m_wTaskAuthor;
	SCR_AssignedPlayerLabelUIComponent m_TaskAuthorComponent;

	ImageWidget m_wPlatformKindIcon;
	TextWidget m_wPlayerName;

	ScrollLayoutWidget m_wDescriptionScrollLayout;
	SCR_GamepadScrollComponent m_DescriptionScrollLayoutComponent;

	RichTextWidget m_wDescription;
	SizeLayoutWidget m_wChildTasks;
	TextWidget m_wChildTaskText;
	ScrollLayoutWidget m_wTasksScrollLayout;
	VerticalLayoutWidget m_wChildTasksWrapper;
	Widget m_wAssignedPlayersWrapper;

	FrameWidget m_wTaskAssignGroupList;
	SCR_TaskAssignGroupListUIComponent m_TaskAssignGroupListComponent;

	SizeLayoutWidget m_wTaskStateWrapper;
	OverlayWidget m_wOverlayTaskStatesFooter;
	OverlayWidget m_wStateIconOverlayFailed;
	OverlayWidget m_wStateIconOverlayFinished;
	OverlayWidget m_wStateIconOverlayCancelled;
	TextWidget m_wTaskStateText;

	ButtonWidget m_wButtonShowMap;
	SCR_InputButtonComponent m_ButtonShowMapComponent0;
	SCR_TaskListFocusUIComponent m_ButtonShowMapComponent1;


	ButtonWidget m_wButtonAssignTask;
	SCR_InputButtonComponent m_ButtonAssignTaskComponent0;
	SCR_TaskListFocusUIComponent m_ButtonAssignTaskComponent1;


	ButtonWidget m_wButtonOpenAssignGroupList;
	SCR_InputButtonComponent m_ButtonOpenAssignGroupListComponent0;
	SCR_TaskListFocusUIComponent m_ButtonOpenAssignGroupListComponent1;


	//------------------------------------------------------------------------------------------------
	bool Init(notnull Widget root)
	{
		m_wTaskIconButton = ButtonWidget.Cast(root.FindWidget("SizeLayout.DescriptionOverlay.VerticalLayout.Header.m_wTaskIconButton"));
		m_TaskIconButtonComponent = SCR_ModularButtonComponent.Cast(m_wTaskIconButton.FindHandler(SCR_ModularButtonComponent));

		m_wTaskIcon = SizeLayoutWidget.Cast(root.FindWidget("SizeLayout.DescriptionOverlay.VerticalLayout.Header.m_wTaskIconButton.m_wTaskIcon"));
		m_wIconOverlay = OverlayWidget.Cast(root.FindWidget("SizeLayout.DescriptionOverlay.VerticalLayout.Header.m_wTaskIconButton.m_wTaskIcon.OverlayTaskIcon.m_wIconOverlay"));
		m_wTaskIconBackground = ImageWidget.Cast(root.FindWidget("SizeLayout.DescriptionOverlay.VerticalLayout.Header.m_wTaskIconButton.m_wTaskIcon.OverlayTaskIcon.m_wIconOverlay.m_wTaskIconBackground"));
		m_wTaskIconOutline = ImageWidget.Cast(root.FindWidget("SizeLayout.DescriptionOverlay.VerticalLayout.Header.m_wTaskIconButton.m_wTaskIcon.OverlayTaskIcon.m_wIconOverlay.m_wTaskIconOutline"));
		m_wTaskIconSymbol = ImageWidget.Cast(root.FindWidget("SizeLayout.DescriptionOverlay.VerticalLayout.Header.m_wTaskIconButton.m_wTaskIcon.OverlayTaskIcon.m_wIconOverlay.m_wTaskIconSymbol"));
		m_wOverlayTaskStates = OverlayWidget.Cast(root.FindWidget("SizeLayout.DescriptionOverlay.VerticalLayout.Header.m_wTaskIconButton.m_wTaskIcon.OverlayTaskIcon.m_wOverlayTaskStates"));
		m_wIconOverlayFailed = OverlayWidget.Cast(root.FindWidget("SizeLayout.DescriptionOverlay.VerticalLayout.Header.m_wTaskIconButton.m_wTaskIcon.OverlayTaskIcon.m_wOverlayTaskStates.m_wIconOverlayFailed"));
		m_wTaskIconFailedBG = ImageWidget.Cast(root.FindWidget("SizeLayout.DescriptionOverlay.VerticalLayout.Header.m_wTaskIconButton.m_wTaskIcon.OverlayTaskIcon.m_wOverlayTaskStates.m_wIconOverlayFailed.m_wTaskIconFailedBG"));
		m_wTaskIconFailed = ImageWidget.Cast(root.FindWidget("SizeLayout.DescriptionOverlay.VerticalLayout.Header.m_wTaskIconButton.m_wTaskIcon.OverlayTaskIcon.m_wOverlayTaskStates.m_wIconOverlayFailed.m_wTaskIconFailed"));
		m_wIconOverlayFinished = OverlayWidget.Cast(root.FindWidget("SizeLayout.DescriptionOverlay.VerticalLayout.Header.m_wTaskIconButton.m_wTaskIcon.OverlayTaskIcon.m_wOverlayTaskStates.m_wIconOverlayFinished"));
		m_wTaskIconFinishedBG = ImageWidget.Cast(root.FindWidget("SizeLayout.DescriptionOverlay.VerticalLayout.Header.m_wTaskIconButton.m_wTaskIcon.OverlayTaskIcon.m_wOverlayTaskStates.m_wIconOverlayFinished.m_wTaskIconFinishedBG"));
		m_wTaskIconFinished = ImageWidget.Cast(root.FindWidget("SizeLayout.DescriptionOverlay.VerticalLayout.Header.m_wTaskIconButton.m_wTaskIcon.OverlayTaskIcon.m_wOverlayTaskStates.m_wIconOverlayFinished.m_wTaskIconFinished"));
		m_wIconOverlayCancelled = OverlayWidget.Cast(root.FindWidget("SizeLayout.DescriptionOverlay.VerticalLayout.Header.m_wTaskIconButton.m_wTaskIcon.OverlayTaskIcon.m_wOverlayTaskStates.m_wIconOverlayCancelled"));
		m_wTaskIconCancelledBG = ImageWidget.Cast(root.FindWidget("SizeLayout.DescriptionOverlay.VerticalLayout.Header.m_wTaskIconButton.m_wTaskIcon.OverlayTaskIcon.m_wOverlayTaskStates.m_wIconOverlayCancelled.m_wTaskIconCancelledBG"));
		m_wTaskIconCancelled = ImageWidget.Cast(root.FindWidget("SizeLayout.DescriptionOverlay.VerticalLayout.Header.m_wTaskIconButton.m_wTaskIcon.OverlayTaskIcon.m_wOverlayTaskStates.m_wIconOverlayCancelled.m_wTaskIconCancelled"));

		m_wTitleFrame = FrameWidget.Cast(root.FindWidget("SizeLayout.DescriptionOverlay.VerticalLayout.Header.SizeLayout.m_wTitleFrame"));
		m_TitleFrameComponent = SCR_HorizontalScrollAnimationComponent.Cast(m_wTitleFrame.FindHandler(SCR_HorizontalScrollAnimationComponent));

		m_wTaskTitle = RichTextWidget.Cast(root.FindWidget("SizeLayout.DescriptionOverlay.VerticalLayout.Header.SizeLayout.m_wTitleFrame.ContentWrapper.m_wTaskTitle"));
		m_wAssignedPlayersCount = SizeLayoutWidget.Cast(root.FindWidget("SizeLayout.DescriptionOverlay.VerticalLayout.Header.m_wAssignedPlayersCount"));
		m_wAssignedCountText = TextWidget.Cast(root.FindWidget("SizeLayout.DescriptionOverlay.VerticalLayout.Header.m_wAssignedPlayersCount.HorizontalLayout.m_wAssignedCountText"));
		m_wAssignedCountIcon = ImageWidget.Cast(root.FindWidget("SizeLayout.DescriptionOverlay.VerticalLayout.Header.m_wAssignedPlayersCount.HorizontalLayout.m_wAssignedCountIcon"));
		m_wAuthorFrame = FrameWidget.Cast(root.FindWidget("SizeLayout.DescriptionOverlay.VerticalLayout.m_wAuthorFrame"));

		m_wTaskAuthor = OverlayWidget.Cast(root.FindWidget("SizeLayout.DescriptionOverlay.VerticalLayout.m_wAuthorFrame.ContentWrapper.m_TaskAuthor"));
		m_TaskAuthorComponent = SCR_AssignedPlayerLabelUIComponent.Cast(m_wTaskAuthor.FindHandler(SCR_AssignedPlayerLabelUIComponent));

		m_wPlatformKindIcon = ImageWidget.Cast(root.FindWidget("SizeLayout.DescriptionOverlay.VerticalLayout.m_wAuthorFrame.ContentWrapper.m_TaskAuthor.AssignedPlayer.Overlay.HorizontalLayout.SizeIcon.m_wPlatformKindIcon"));
		m_wPlayerName = TextWidget.Cast(root.FindWidget("SizeLayout.DescriptionOverlay.VerticalLayout.m_wAuthorFrame.ContentWrapper.m_TaskAuthor.AssignedPlayer.Overlay.HorizontalLayout.m_wPlayerName"));

		m_wDescriptionScrollLayout = ScrollLayoutWidget.Cast(root.FindWidget("SizeLayout.DescriptionOverlay.VerticalLayout.Overlay.m_wDescriptionScrollLayout"));
		m_DescriptionScrollLayoutComponent = SCR_GamepadScrollComponent.Cast(m_wDescriptionScrollLayout.FindHandler(SCR_GamepadScrollComponent));

		m_wDescription = RichTextWidget.Cast(root.FindWidget("SizeLayout.DescriptionOverlay.VerticalLayout.Overlay.m_wDescriptionScrollLayout.m_wDescription"));
		m_wChildTasks = SizeLayoutWidget.Cast(root.FindWidget("SizeLayout.DescriptionOverlay.VerticalLayout.m_wChildTasks"));
		m_wChildTaskText = TextWidget.Cast(root.FindWidget("SizeLayout.DescriptionOverlay.VerticalLayout.m_wChildTasks.VertialLayout.m_wChildTaskText"));
		m_wTasksScrollLayout = ScrollLayoutWidget.Cast(root.FindWidget("SizeLayout.DescriptionOverlay.VerticalLayout.m_wChildTasks.VertialLayout.m_wTasksScrollLayout"));
		m_wChildTasksWrapper = VerticalLayoutWidget.Cast(root.FindWidget("SizeLayout.DescriptionOverlay.VerticalLayout.m_wChildTasks.VertialLayout.m_wTasksScrollLayout.m_wChildTasksWrapper"));
		m_wAssignedPlayersWrapper = root.FindWidget("SizeLayout.DescriptionOverlay.VerticalLayout.FooterWrapper.m_wAssignedPlayersWrapper");

		m_wTaskAssignGroupList = FrameWidget.Cast(root.FindWidget("SizeLayout.DescriptionOverlay.VerticalLayout.FooterWrapper.m_wTaskAssignGroupList"));
		m_TaskAssignGroupListComponent = SCR_TaskAssignGroupListUIComponent.Cast(m_wTaskAssignGroupList.FindHandler(SCR_TaskAssignGroupListUIComponent));

		m_wTaskStateWrapper = SizeLayoutWidget.Cast(root.FindWidget("SizeLayout.DescriptionOverlay.VerticalLayout.FooterWrapper.m_wTaskStateWrapper"));
		m_wOverlayTaskStatesFooter = OverlayWidget.Cast(root.FindWidget("SizeLayout.DescriptionOverlay.VerticalLayout.FooterWrapper.m_wTaskStateWrapper.HorizontalLayout.m_wOverlayTaskStatesFooter"));
		m_wStateIconOverlayFailed = OverlayWidget.Cast(root.FindWidget("SizeLayout.DescriptionOverlay.VerticalLayout.FooterWrapper.m_wTaskStateWrapper.HorizontalLayout.m_wOverlayTaskStatesFooter.m_wStateIconOverlayFailed"));
		m_wStateIconOverlayFinished = OverlayWidget.Cast(root.FindWidget("SizeLayout.DescriptionOverlay.VerticalLayout.FooterWrapper.m_wTaskStateWrapper.HorizontalLayout.m_wOverlayTaskStatesFooter.m_wStateIconOverlayFinished"));
		m_wStateIconOverlayCancelled = OverlayWidget.Cast(root.FindWidget("SizeLayout.DescriptionOverlay.VerticalLayout.FooterWrapper.m_wTaskStateWrapper.HorizontalLayout.m_wOverlayTaskStatesFooter.m_wStateIconOverlayCancelled"));
		m_wTaskStateText = TextWidget.Cast(root.FindWidget("SizeLayout.DescriptionOverlay.VerticalLayout.FooterWrapper.m_wTaskStateWrapper.HorizontalLayout.m_wTaskStateText"));

		m_wButtonShowMap = ButtonWidget.Cast(root.FindWidget("SizeLayout.DescriptionOverlay.VerticalLayout.FooterWrapper.Footer.m_wButtonShowMap"));
		m_ButtonShowMapComponent0 = SCR_InputButtonComponent.Cast(m_wButtonShowMap.FindHandler(SCR_InputButtonComponent));
		m_ButtonShowMapComponent1 = SCR_TaskListFocusUIComponent.Cast(m_wButtonShowMap.FindHandler(SCR_TaskListFocusUIComponent));


		m_wButtonAssignTask = ButtonWidget.Cast(root.FindWidget("SizeLayout.DescriptionOverlay.VerticalLayout.FooterWrapper.Footer.m_wButtonAssignTask"));
		m_ButtonAssignTaskComponent0 = SCR_InputButtonComponent.Cast(m_wButtonAssignTask.FindHandler(SCR_InputButtonComponent));
		m_ButtonAssignTaskComponent1 = SCR_TaskListFocusUIComponent.Cast(m_wButtonAssignTask.FindHandler(SCR_TaskListFocusUIComponent));


		m_wButtonOpenAssignGroupList = ButtonWidget.Cast(root.FindWidget("SizeLayout.DescriptionOverlay.VerticalLayout.FooterWrapper.Footer.m_wButtonOpenAssignGroupList"));
		m_ButtonOpenAssignGroupListComponent0 = SCR_InputButtonComponent.Cast(m_wButtonOpenAssignGroupList.FindHandler(SCR_InputButtonComponent));
		m_ButtonOpenAssignGroupListComponent1 = SCR_TaskListFocusUIComponent.Cast(m_wButtonOpenAssignGroupList.FindHandler(SCR_TaskListFocusUIComponent));


		return true;
	}

	//------------------------------------------------------------------------------------------------
	ResourceName GetLayout()
	{
		return LAYOUT;
	}
}
