// Autogenerated by the Generate Class from Layout plugin v0.5.1
// Layout file: UI/layouts/Task/TaskListTabEntry.layout
class SCR_TaskListTabEntryWidgets
{
	protected static const ResourceName LAYOUT = "{A5326D834EB28E28}UI/layouts/Task/TaskListTabEntry.layout";

	SmartPanelWidget m_wBackground;
	TextWidget m_wText;

	//------------------------------------------------------------------------------------------------
	bool Init(notnull Widget root)
	{
		m_wBackground = SmartPanelWidget.Cast(root.FindWidget("SizeLayout.Overlay.m_wBackground"));
		m_wText = TextWidget.Cast(root.FindWidget("SizeLayout.Overlay.m_wText"));

		return true;
	}

	//------------------------------------------------------------------------------------------------
	ResourceName GetLayout()
	{
		return LAYOUT;
	}
}
