// Autogenerated by the Generate Class from Layout plugin v0.5.1
// Layout file: UI/layouts/Task/TaskAssignGroupListEntry.layout
class SCR_TaskAssignGroupListEntryWidgets
{
	protected static const ResourceName LAYOUT = "{4178951F3767082E}UI/layouts/Task/TaskAssignGroupListEntry.layout";

	ImageWidget m_wGroupIcon;
	TextWidget m_wGroupName;
	TextWidget m_wGroupRoleName;
	OverlayWidget m_wAssignedTaskOverlay;
	ImageWidget m_wAssignedTaskIcon;

	//------------------------------------------------------------------------------------------------
	bool Init(notnull Widget root)
	{
		m_wGroupIcon = ImageWidget.Cast(root.FindWidget("SizeLayout0.Overlay0.ContentWrapper.SizeLayout0.m_wGroupIcon"));
		m_wGroupName = TextWidget.Cast(root.FindWidget("SizeLayout0.Overlay0.ContentWrapper.SizeLayout1.FrameName.ContentWrapper.m_wGroupName"));
		m_wGroupRoleName = TextWidget.Cast(root.FindWidget("SizeLayout0.Overlay0.ContentWrapper.m_wGroupRoleName"));
		m_wAssignedTaskOverlay = OverlayWidget.Cast(root.FindWidget("SizeLayout0.Overlay0.ContentWrapper.HorizontalLayout0.m_wAssignedTaskOverlay"));
		m_wAssignedTaskIcon = ImageWidget.Cast(root.FindWidget("SizeLayout0.Overlay0.ContentWrapper.HorizontalLayout0.m_wAssignedTaskOverlay.m_wAssignedTaskIcon"));

		return true;
	}

	//------------------------------------------------------------------------------------------------
	ResourceName GetLayout()
	{
		return LAYOUT;
	}
}
