// Autogenerated by the Generate Class from Layout plugin v0.5.1
// Layout file: UI/layouts/Task/TaskListEntry.layout
class SCR_TaskListEntryWidgets
{
	protected static const ResourceName LAYOUT = "{B71975032150BAFB}UI/layouts/Task/TaskListEntry.layout";

	ButtonWidget m_wButton;
	SCR_ModularButtonComponent m_ButtonComponent;


	SizeLayoutWidget m_wProgressBar;
	SCR_WLibProgressBarComponent m_ProgressBarComponent;


	ButtonWidget m_wTaskIconButton;
	SCR_ModularButtonComponent m_TaskIconButtonComponent;

	SizeLayoutWidget m_wTaskIcon;
	OverlayWidget m_wIconOverlay;
	ImageWidget m_wTaskIconBackground;
	ImageWidget m_wTaskIconOutline;
	ImageWidget m_wTaskIconSymbol;
	OverlayWidget m_wOverlayTaskStates;
	OverlayWidget m_wIconOverlayFailed;
	ImageWidget m_wTaskIconFailedBG;
	ImageWidget m_wTaskIconFailed;
	OverlayWidget m_wIconOverlayFinished;
	ImageWidget m_wTaskIconFinishedBG;
	ImageWidget m_wTaskIconFinished;
	OverlayWidget m_wIconOverlayCancelled;
	ImageWidget m_wTaskIconCancelledBG;
	ImageWidget m_wTaskIconCancelled;

	FrameWidget m_wTitleFrame;
	SCR_HorizontalScrollAnimationComponent m_TitleFrameComponent;

	RichTextWidget m_wTaskTitle;
	SizeLayoutWidget m_wChildTasksCount;
	TextWidget m_wChildTasksCountText;
	HorizontalLayoutWidget m_wAssigneesLayout;
	TextWidget m_wAssigneesAmountText;
	SizeLayoutWidget m_wSizeFoldButton;

	ButtonWidget m_wButtonFold;
	SCR_ModularButtonComponent m_ButtonFoldComponent;

	ImageWidget m_wIconFold;
	VerticalLayoutWidget m_wChildTaskWrapper;

	//------------------------------------------------------------------------------------------------
	bool Init(notnull Widget root)
	{
		m_wButton = ButtonWidget.Cast(root.FindWidget("SizeLayout.VerticalLayout.m_wButton"));
		m_ButtonComponent = SCR_ModularButtonComponent.Cast(m_wButton.FindHandler(SCR_ModularButtonComponent));


		m_wProgressBar = SizeLayoutWidget.Cast(root.FindWidget("SizeLayout.VerticalLayout.m_wButton.SizeLayout.Overlay.m_wProgressBar"));
		m_ProgressBarComponent = SCR_WLibProgressBarComponent.Cast(m_wProgressBar.FindHandler(SCR_WLibProgressBarComponent));


		m_wTaskIconButton = ButtonWidget.Cast(root.FindWidget("SizeLayout.VerticalLayout.m_wButton.SizeLayout.Overlay.HorizontalLayout.m_wTaskIconButton"));
		m_TaskIconButtonComponent = SCR_ModularButtonComponent.Cast(m_wTaskIconButton.FindHandler(SCR_ModularButtonComponent));

		m_wTaskIcon = SizeLayoutWidget.Cast(root.FindWidget("SizeLayout.VerticalLayout.m_wButton.SizeLayout.Overlay.HorizontalLayout.m_wTaskIconButton.m_wTaskIcon"));
		m_wIconOverlay = OverlayWidget.Cast(root.FindWidget("SizeLayout.VerticalLayout.m_wButton.SizeLayout.Overlay.HorizontalLayout.m_wTaskIconButton.m_wTaskIcon.OverlayTaskIcon.m_wIconOverlay"));
		m_wTaskIconBackground = ImageWidget.Cast(root.FindWidget("SizeLayout.VerticalLayout.m_wButton.SizeLayout.Overlay.HorizontalLayout.m_wTaskIconButton.m_wTaskIcon.OverlayTaskIcon.m_wIconOverlay.m_wTaskIconBackground"));
		m_wTaskIconOutline = ImageWidget.Cast(root.FindWidget("SizeLayout.VerticalLayout.m_wButton.SizeLayout.Overlay.HorizontalLayout.m_wTaskIconButton.m_wTaskIcon.OverlayTaskIcon.m_wIconOverlay.m_wTaskIconOutline"));
		m_wTaskIconSymbol = ImageWidget.Cast(root.FindWidget("SizeLayout.VerticalLayout.m_wButton.SizeLayout.Overlay.HorizontalLayout.m_wTaskIconButton.m_wTaskIcon.OverlayTaskIcon.m_wIconOverlay.m_wTaskIconSymbol"));
		m_wOverlayTaskStates = OverlayWidget.Cast(root.FindWidget("SizeLayout.VerticalLayout.m_wButton.SizeLayout.Overlay.HorizontalLayout.m_wTaskIconButton.m_wTaskIcon.OverlayTaskIcon.m_wOverlayTaskStates"));
		m_wIconOverlayFailed = OverlayWidget.Cast(root.FindWidget("SizeLayout.VerticalLayout.m_wButton.SizeLayout.Overlay.HorizontalLayout.m_wTaskIconButton.m_wTaskIcon.OverlayTaskIcon.m_wOverlayTaskStates.m_wIconOverlayFailed"));
		m_wTaskIconFailedBG = ImageWidget.Cast(root.FindWidget("SizeLayout.VerticalLayout.m_wButton.SizeLayout.Overlay.HorizontalLayout.m_wTaskIconButton.m_wTaskIcon.OverlayTaskIcon.m_wOverlayTaskStates.m_wIconOverlayFailed.m_wTaskIconFailedBG"));
		m_wTaskIconFailed = ImageWidget.Cast(root.FindWidget("SizeLayout.VerticalLayout.m_wButton.SizeLayout.Overlay.HorizontalLayout.m_wTaskIconButton.m_wTaskIcon.OverlayTaskIcon.m_wOverlayTaskStates.m_wIconOverlayFailed.m_wTaskIconFailed"));
		m_wIconOverlayFinished = OverlayWidget.Cast(root.FindWidget("SizeLayout.VerticalLayout.m_wButton.SizeLayout.Overlay.HorizontalLayout.m_wTaskIconButton.m_wTaskIcon.OverlayTaskIcon.m_wOverlayTaskStates.m_wIconOverlayFinished"));
		m_wTaskIconFinishedBG = ImageWidget.Cast(root.FindWidget("SizeLayout.VerticalLayout.m_wButton.SizeLayout.Overlay.HorizontalLayout.m_wTaskIconButton.m_wTaskIcon.OverlayTaskIcon.m_wOverlayTaskStates.m_wIconOverlayFinished.m_wTaskIconFinishedBG"));
		m_wTaskIconFinished = ImageWidget.Cast(root.FindWidget("SizeLayout.VerticalLayout.m_wButton.SizeLayout.Overlay.HorizontalLayout.m_wTaskIconButton.m_wTaskIcon.OverlayTaskIcon.m_wOverlayTaskStates.m_wIconOverlayFinished.m_wTaskIconFinished"));
		m_wIconOverlayCancelled = OverlayWidget.Cast(root.FindWidget("SizeLayout.VerticalLayout.m_wButton.SizeLayout.Overlay.HorizontalLayout.m_wTaskIconButton.m_wTaskIcon.OverlayTaskIcon.m_wOverlayTaskStates.m_wIconOverlayCancelled"));
		m_wTaskIconCancelledBG = ImageWidget.Cast(root.FindWidget("SizeLayout.VerticalLayout.m_wButton.SizeLayout.Overlay.HorizontalLayout.m_wTaskIconButton.m_wTaskIcon.OverlayTaskIcon.m_wOverlayTaskStates.m_wIconOverlayCancelled.m_wTaskIconCancelledBG"));
		m_wTaskIconCancelled = ImageWidget.Cast(root.FindWidget("SizeLayout.VerticalLayout.m_wButton.SizeLayout.Overlay.HorizontalLayout.m_wTaskIconButton.m_wTaskIcon.OverlayTaskIcon.m_wOverlayTaskStates.m_wIconOverlayCancelled.m_wTaskIconCancelled"));

		m_wTitleFrame = FrameWidget.Cast(root.FindWidget("SizeLayout.VerticalLayout.m_wButton.SizeLayout.Overlay.HorizontalLayout.SizeLayoutTitle.OverlayWidget.HorizontalLayout.SizeLayout.m_wTitleFrame"));
		m_TitleFrameComponent = SCR_HorizontalScrollAnimationComponent.Cast(m_wTitleFrame.FindHandler(SCR_HorizontalScrollAnimationComponent));

		m_wTaskTitle = RichTextWidget.Cast(root.FindWidget("SizeLayout.VerticalLayout.m_wButton.SizeLayout.Overlay.HorizontalLayout.SizeLayoutTitle.OverlayWidget.HorizontalLayout.SizeLayout.m_wTitleFrame.ContentWrapper.m_wTaskTitle"));
		m_wChildTasksCount = SizeLayoutWidget.Cast(root.FindWidget("SizeLayout.VerticalLayout.m_wButton.SizeLayout.Overlay.HorizontalLayout.SizeLayoutTitle.OverlayWidget.HorizontalLayout.m_wChildTasksCount"));
		m_wChildTasksCountText = TextWidget.Cast(root.FindWidget("SizeLayout.VerticalLayout.m_wButton.SizeLayout.Overlay.HorizontalLayout.SizeLayoutTitle.OverlayWidget.HorizontalLayout.m_wChildTasksCount.Overlay.m_wChildTasksCountText"));
		m_wAssigneesLayout = HorizontalLayoutWidget.Cast(root.FindWidget("SizeLayout.VerticalLayout.m_wButton.SizeLayout.Overlay.HorizontalLayout.OverlayAssignees.m_wAssigneesLayout"));
		m_wAssigneesAmountText = TextWidget.Cast(root.FindWidget("SizeLayout.VerticalLayout.m_wButton.SizeLayout.Overlay.HorizontalLayout.OverlayAssignees.m_wAssigneesLayout.m_wAssigneesAmountText"));
		m_wSizeFoldButton = SizeLayoutWidget.Cast(root.FindWidget("SizeLayout.VerticalLayout.m_wButton.SizeLayout.Overlay.HorizontalLayout.m_wSizeFoldButton"));

		m_wButtonFold = ButtonWidget.Cast(root.FindWidget("SizeLayout.VerticalLayout.m_wButton.SizeLayout.Overlay.HorizontalLayout.m_wSizeFoldButton.m_wButtonFold"));
		m_ButtonFoldComponent = SCR_ModularButtonComponent.Cast(m_wButtonFold.FindHandler(SCR_ModularButtonComponent));

		m_wIconFold = ImageWidget.Cast(root.FindWidget("SizeLayout.VerticalLayout.m_wButton.SizeLayout.Overlay.HorizontalLayout.m_wSizeFoldButton.m_wButtonFold.m_wIconFold"));
		m_wChildTaskWrapper = VerticalLayoutWidget.Cast(root.FindWidget("SizeLayout.VerticalLayout.m_wChildTaskWrapper"));

		return true;
	}

	//------------------------------------------------------------------------------------------------
	ResourceName GetLayout()
	{
		return LAYOUT;
	}
}
