// Autogenerated by the Generate Class from Layout plugin v0.5.1
// Layout file: UI/layouts/Task/TaskMap.layout
class SCR_TaskMapWidgets
{
	protected static const ResourceName LAYOUT = "{8CA518E4D3AE9F28}UI/layouts/Task/TaskMap.layout";

	HorizontalLayoutWidget m_wHorizontalLayout;

	ButtonWidget m_wTaskIconButton;
	SCR_ModularButtonComponent m_TaskIconButtonComponent;

	SizeLayoutWidget m_wTaskIcon;
	OverlayWidget m_wIconOverlay;
	ImageWidget m_wTaskIconBackground;
	ImageWidget m_wTaskIconOutline;
	ImageWidget m_wTaskIconSymbol;
	OverlayWidget m_wOverlayTaskStates;
	OverlayWidget m_wIconOverlayFailed;
	ImageWidget m_wTaskIconFailedBG;
	ImageWidget m_wTaskIconFailed;
	OverlayWidget m_wIconOverlayFinished;
	ImageWidget m_wTaskIconFinishedBG;
	ImageWidget m_wTaskIconFinished;
	OverlayWidget m_wIconOverlayCancelled;
	ImageWidget m_wTaskIconCancelledBG;
	ImageWidget m_wTaskIconCancelled;

	ButtonWidget m_wTaskTitleButton;
	SCR_ModularButtonComponent m_TaskTitleButtonComponent;

	SizeLayoutWidget m_wTitleSize;
	SizeLayoutWidget m_wTitleSizeLayout;

	FrameWidget m_wTitleFrame;
	SCR_HorizontalScrollAnimationComponent m_TitleFrameComponent;

	RichTextWidget m_wTaskTitle;
	HorizontalLayoutWidget m_wAssignedPlayers;
	TextWidget m_wAssigneesCount;
	HorizontalLayoutWidget m_wAuthorLayout;
	ImageWidget m_wPlatformIcon;
	TextWidget m_wMarkerAuthor;

	//------------------------------------------------------------------------------------------------
	bool Init(notnull Widget root)
	{
		m_wHorizontalLayout = HorizontalLayoutWidget.Cast(root.FindWidget("m_wHorizontalLayout"));

		m_wTaskIconButton = ButtonWidget.Cast(root.FindWidget("m_wHorizontalLayout.m_wTaskIconButton"));
		m_TaskIconButtonComponent = SCR_ModularButtonComponent.Cast(m_wTaskIconButton.FindHandler(SCR_ModularButtonComponent));

		m_wTaskIcon = SizeLayoutWidget.Cast(root.FindWidget("m_wHorizontalLayout.m_wTaskIconButton.m_wTaskIcon"));
		m_wIconOverlay = OverlayWidget.Cast(root.FindWidget("m_wHorizontalLayout.m_wTaskIconButton.m_wTaskIcon.OverlayTaskIcon.m_wIconOverlay"));
		m_wTaskIconBackground = ImageWidget.Cast(root.FindWidget("m_wHorizontalLayout.m_wTaskIconButton.m_wTaskIcon.OverlayTaskIcon.m_wIconOverlay.m_wTaskIconBackground"));
		m_wTaskIconOutline = ImageWidget.Cast(root.FindWidget("m_wHorizontalLayout.m_wTaskIconButton.m_wTaskIcon.OverlayTaskIcon.m_wIconOverlay.m_wTaskIconOutline"));
		m_wTaskIconSymbol = ImageWidget.Cast(root.FindWidget("m_wHorizontalLayout.m_wTaskIconButton.m_wTaskIcon.OverlayTaskIcon.m_wIconOverlay.m_wTaskIconSymbol"));
		m_wOverlayTaskStates = OverlayWidget.Cast(root.FindWidget("m_wHorizontalLayout.m_wTaskIconButton.m_wTaskIcon.OverlayTaskIcon.m_wOverlayTaskStates"));
		m_wIconOverlayFailed = OverlayWidget.Cast(root.FindWidget("m_wHorizontalLayout.m_wTaskIconButton.m_wTaskIcon.OverlayTaskIcon.m_wOverlayTaskStates.m_wIconOverlayFailed"));
		m_wTaskIconFailedBG = ImageWidget.Cast(root.FindWidget("m_wHorizontalLayout.m_wTaskIconButton.m_wTaskIcon.OverlayTaskIcon.m_wOverlayTaskStates.m_wIconOverlayFailed.m_wTaskIconFailedBG"));
		m_wTaskIconFailed = ImageWidget.Cast(root.FindWidget("m_wHorizontalLayout.m_wTaskIconButton.m_wTaskIcon.OverlayTaskIcon.m_wOverlayTaskStates.m_wIconOverlayFailed.m_wTaskIconFailed"));
		m_wIconOverlayFinished = OverlayWidget.Cast(root.FindWidget("m_wHorizontalLayout.m_wTaskIconButton.m_wTaskIcon.OverlayTaskIcon.m_wOverlayTaskStates.m_wIconOverlayFinished"));
		m_wTaskIconFinishedBG = ImageWidget.Cast(root.FindWidget("m_wHorizontalLayout.m_wTaskIconButton.m_wTaskIcon.OverlayTaskIcon.m_wOverlayTaskStates.m_wIconOverlayFinished.m_wTaskIconFinishedBG"));
		m_wTaskIconFinished = ImageWidget.Cast(root.FindWidget("m_wHorizontalLayout.m_wTaskIconButton.m_wTaskIcon.OverlayTaskIcon.m_wOverlayTaskStates.m_wIconOverlayFinished.m_wTaskIconFinished"));
		m_wIconOverlayCancelled = OverlayWidget.Cast(root.FindWidget("m_wHorizontalLayout.m_wTaskIconButton.m_wTaskIcon.OverlayTaskIcon.m_wOverlayTaskStates.m_wIconOverlayCancelled"));
		m_wTaskIconCancelledBG = ImageWidget.Cast(root.FindWidget("m_wHorizontalLayout.m_wTaskIconButton.m_wTaskIcon.OverlayTaskIcon.m_wOverlayTaskStates.m_wIconOverlayCancelled.m_wTaskIconCancelledBG"));
		m_wTaskIconCancelled = ImageWidget.Cast(root.FindWidget("m_wHorizontalLayout.m_wTaskIconButton.m_wTaskIcon.OverlayTaskIcon.m_wOverlayTaskStates.m_wIconOverlayCancelled.m_wTaskIconCancelled"));

		m_wTaskTitleButton = ButtonWidget.Cast(root.FindWidget("m_wHorizontalLayout.m_wTaskTitleButton"));
		m_TaskTitleButtonComponent = SCR_ModularButtonComponent.Cast(m_wTaskTitleButton.FindHandler(SCR_ModularButtonComponent));

		m_wTitleSize = SizeLayoutWidget.Cast(root.FindWidget("m_wHorizontalLayout.m_wTaskTitleButton.m_wTitleSize"));
		m_wTitleSizeLayout = SizeLayoutWidget.Cast(root.FindWidget("m_wHorizontalLayout.m_wTaskTitleButton.m_wTitleSize.Overlay.HorizontalLayout.m_wTitleSizeLayout"));

		m_wTitleFrame = FrameWidget.Cast(root.FindWidget("m_wHorizontalLayout.m_wTaskTitleButton.m_wTitleSize.Overlay.HorizontalLayout.m_wTitleSizeLayout.m_wTitleFrame"));
		m_TitleFrameComponent = SCR_HorizontalScrollAnimationComponent.Cast(m_wTitleFrame.FindHandler(SCR_HorizontalScrollAnimationComponent));

		m_wTaskTitle = RichTextWidget.Cast(root.FindWidget("m_wHorizontalLayout.m_wTaskTitleButton.m_wTitleSize.Overlay.HorizontalLayout.m_wTitleSizeLayout.m_wTitleFrame.ContentWrapper.m_wTaskTitle"));
		m_wAssignedPlayers = HorizontalLayoutWidget.Cast(root.FindWidget("m_wHorizontalLayout.m_wTaskTitleButton.m_wTitleSize.Overlay.HorizontalLayout.m_wAssignedPlayers"));
		m_wAssigneesCount = TextWidget.Cast(root.FindWidget("m_wHorizontalLayout.m_wTaskTitleButton.m_wTitleSize.Overlay.HorizontalLayout.m_wAssignedPlayers.m_wAssigneesCount"));
		m_wAuthorLayout = HorizontalLayoutWidget.Cast(root.FindWidget("m_wAuthorLayout"));
		m_wPlatformIcon = ImageWidget.Cast(root.FindWidget("m_wAuthorLayout.m_wPlatformIcon"));
		m_wMarkerAuthor = TextWidget.Cast(root.FindWidget("m_wAuthorLayout.m_wMarkerAuthor"));

		return true;
	}

	//------------------------------------------------------------------------------------------------
	ResourceName GetLayout()
	{
		return LAYOUT;
	}
}
