// Autogenerated by the Layout Class Generator plugin
// Layout file: UI/layouts/Menus/Common/LoadingOverlay.layout

class SCR_LoadingOverlayWidgets
{
	static const ResourceName s_sLayout = "{3245B690D1E28B4F}UI/layouts/Menus/Common/LoadingOverlay.layout";
	ResourceName GetLayout() { return s_sLayout; }

	BlurWidget m_Blur;

	ImageWidget m_BackgroundImage;

	ImageWidget m_AnimationImage;

	TextWidget m_Text;

	bool Init(Widget root)
	{
		m_Blur = BlurWidget.Cast(root.FindAnyWidget("m_Blur"));

		m_BackgroundImage = ImageWidget.Cast(root.FindAnyWidget("m_BackgroundImage"));

		m_AnimationImage = ImageWidget.Cast(root.FindAnyWidget("m_AnimationImage"));

		m_Text = TextWidget.Cast(root.FindAnyWidget("m_Text"));

		return true;
	}
};
