// Autogenerated by the Generate Class from Layout plugin, version 0.3.0
// Layout file: UI/layouts/Menus/ContentBrowser/ScenariosMenu/ContentBrowser_ScenarioSubMenu.layout

class SCR_ContentBrowser_ScenarioSubMenuWidgets
{
	static const ResourceName s_sLayout = "{7B1ED366AEC5F761}UI/layouts/Menus/ContentBrowser/ScenariosMenu/ContentBrowser_ScenarioSubMenu.layout";
	ResourceName GetLayout() { return s_sLayout; }

	SizeLayoutWidget m_LeftPanel;

	HorizontalLayoutWidget m_SortingHeader;
	SCR_SortHeaderComponent m_SortingHeaderComponent;

	ScrollLayoutWidget m_ScenarioScroll;
	SCR_GamepadScrollComponent m_ScenarioScrollComponent;

	VerticalLayoutWidget m_ScenarioList;

	OverlayWidget m_MainPanelMessage;
	SCR_SimpleMessageComponent m_MainPanelMessageComponent;

	OverlayWidget m_FilterPanel;
	SCR_FilterPanelComponent m_FilterPanelComponent;

	OverlayWidget m_MainContent;

	OverlayWidget m_ScenarioDetailsPanel;
	SCR_ScenarioDetailsPanelComponent m_ScenarioDetailsPanelComponent;
	
	OverlayWidget m_AddonDetailsPanel;
	SCR_AddonDetailsPanelComponent m_AddonDetailsPanelComponent;

	SizeLayoutWidget m_EmptyPanel;

	OverlayWidget m_EmptyPanelMessage;
	SCR_SimpleMessageComponent m_EmptyPanelMessageComponent;

	bool Init(Widget root)
	{
		m_LeftPanel = SizeLayoutWidget.Cast(root.FindWidget("Panels.m_LeftPanel"));

		m_SortingHeader = HorizontalLayoutWidget.Cast(root.FindWidget("Panels.m_LeftPanel.VerticalLayout0.TopBarHeight.TopBar.Content.m_SortingHeader"));
		m_SortingHeaderComponent = SCR_SortHeaderComponent.Cast(m_SortingHeader.FindHandler(SCR_SortHeaderComponent));

		m_ScenarioScroll = ScrollLayoutWidget.Cast(root.FindWidget("Panels.m_LeftPanel.VerticalLayout0.Content.m_ScenarioScroll"));
		m_ScenarioScrollComponent = SCR_GamepadScrollComponent.Cast(m_ScenarioScroll.FindHandler(SCR_GamepadScrollComponent));

		m_ScenarioList = VerticalLayoutWidget.Cast(root.FindWidget("Panels.m_LeftPanel.VerticalLayout0.Content.m_ScenarioScroll.m_ScenarioList"));

		m_MainPanelMessage = OverlayWidget.Cast(root.FindWidget("Panels.m_LeftPanel.VerticalLayout0.Content.m_MainPanelMessage"));
		m_MainPanelMessageComponent = SCR_SimpleMessageComponent.Cast(m_MainPanelMessage.FindHandler(SCR_SimpleMessageComponent));

		m_FilterPanel = OverlayWidget.Cast(root.FindWidget("Panels.m_FilterPanel"));
		m_FilterPanelComponent = SCR_FilterPanelComponent.Cast(m_FilterPanel.FindHandler(SCR_FilterPanelComponent));

		m_MainContent = OverlayWidget.Cast(root.FindWidget("Panels.m_FilterPanel.MenuPanel0.VerticalLayout0.Content.m_MainContent"));

		m_ScenarioDetailsPanel = OverlayWidget.Cast(root.FindWidget("Panels.m_FilterPanel.MenuPanel0.VerticalLayout0.Content.m_MainContent.m_ScenarioDetailsPanel"));
		m_ScenarioDetailsPanelComponent = SCR_ScenarioDetailsPanelComponent.Cast(m_ScenarioDetailsPanel.FindHandler(SCR_ScenarioDetailsPanelComponent));

		m_AddonDetailsPanel = OverlayWidget.Cast(root.FindWidget("Panels.m_FilterPanel.MenuPanel0.VerticalLayout0.Content.m_MainContent.m_AddonDetailsPanel"));
		m_AddonDetailsPanelComponent = SCR_AddonDetailsPanelComponent.Cast(m_AddonDetailsPanel.FindHandler(SCR_AddonDetailsPanelComponent));
		
		m_EmptyPanel = SizeLayoutWidget.Cast(root.FindWidget("Panels.m_EmptyPanel"));

		m_EmptyPanelMessage = OverlayWidget.Cast(root.FindWidget("Panels.m_EmptyPanel.VerticalLayout0.Content.m_EmptyPanelMessage"));
		m_EmptyPanelMessageComponent = SCR_SimpleMessageComponent.Cast(m_EmptyPanelMessage.FindHandler(SCR_SimpleMessageComponent));

		return true;
	}
};
