// Autogenerated by the Generate Class from Layout plugin v0.5.0
// Layout file: UI/layouts/Menus/ContentBrowser/ScenariosMenu/ContentBrowser_GMSaveLine.layout
class SCR_ContentBrowser_GMSaveLineWidgets
{
	protected static const ResourceName LAYOUT = "{723ED8FDA27DD0BA}UI/layouts/Menus/ContentBrowser/ScenariosMenu/ContentBrowser_GMSaveLine.layout";

	SizeLayoutWidget m_wFavouriteButtonOverlay;

	ButtonWidget m_wFavouriteButton;
	SCR_ModularButtonComponent m_FavouriteButtonComponent0;
	SCR_DynamicIconComponent m_FavouriteButtonComponent1;

	TextWidget m_wNameText;
	SizeLayoutWidget m_wLastPlayedTextSize;
	TextWidget m_wLastPlayedText;

	ButtonWidget m_wRestart;
	SCR_ModularButtonComponent m_RestartComponent0;
	SCR_DynamicIconComponent m_RestartComponent1;

	HorizontalLayoutWidget m_wPlayerCount;
	ImageWidget m_wSinglePlayerImage;
	ImageWidget m_wMultiPlayerImage;

	ButtonWidget m_wHost;
	SCR_ModularButtonComponent m_HostComponent0;
	SCR_DynamicIconComponent m_HostComponent1;


	ButtonWidget m_wPlay;
	SCR_ModularButtonComponent m_PlayComponent0;
	SCR_DynamicIconComponent m_PlayComponent1;


	ButtonWidget m_wContinue;
	SCR_ModularButtonComponent m_ContinueComponent0;
	SCR_DynamicIconComponent m_ContinueComponent1;

	HorizontalLayoutWidget m_wSource;
	ImageWidget m_wSourceImageCommunity;
	ImageWidget m_wSourceImageOfficial;
	TextWidget m_wSourceNameTextOfficial;
	TextWidget m_wSourceNameTextCommunity;

	//------------------------------------------------------------------------------------------------
	bool Init(Widget root)
	{
		m_wFavouriteButtonOverlay = SizeLayoutWidget.Cast(root.FindWidget("LineHeight.OverlayMain.LineContent.LineElements.m_wFavouriteButtonOverlay"));

		m_wFavouriteButton = ButtonWidget.Cast(root.FindWidget("LineHeight.OverlayMain.LineContent.LineElements.m_wFavouriteButtonOverlay.m_wFavouriteButton"));
		m_FavouriteButtonComponent0 = SCR_ModularButtonComponent.Cast(m_wFavouriteButton.FindHandler(SCR_ModularButtonComponent));
		m_FavouriteButtonComponent1 = SCR_DynamicIconComponent.Cast(m_wFavouriteButton.FindHandler(SCR_DynamicIconComponent));

		m_wNameText = TextWidget.Cast(root.FindWidget("LineHeight.OverlayMain.LineContent.LineElements.NameSize.NameOverlay.m_wNameText"));
		m_wLastPlayedTextSize = SizeLayoutWidget.Cast(root.FindWidget("LineHeight.OverlayMain.LineContent.LineElements.m_wLastPlayedTextSize"));
		m_wLastPlayedText = TextWidget.Cast(root.FindWidget("LineHeight.OverlayMain.LineContent.LineElements.m_wLastPlayedTextSize.LastPlayedOverlay.m_wLastPlayedText"));

		m_wRestart = ButtonWidget.Cast(root.FindWidget("LineHeight.OverlayMain.LineContent.LineElements.m_wLastPlayedTextSize.LastPlayedOverlay.RestartButtonArea.m_wRestart"));
		m_RestartComponent0 = SCR_ModularButtonComponent.Cast(m_wRestart.FindHandler(SCR_ModularButtonComponent));
		m_RestartComponent1 = SCR_DynamicIconComponent.Cast(m_wRestart.FindHandler(SCR_DynamicIconComponent));

		m_wPlayerCount = HorizontalLayoutWidget.Cast(root.FindWidget("LineHeight.OverlayMain.LineContent.LineElements.PlayerCountSize.m_wPlayerCount"));
		m_wSinglePlayerImage = ImageWidget.Cast(root.FindWidget("LineHeight.OverlayMain.LineContent.LineElements.PlayerCountSize.m_wPlayerCount.m_wSinglePlayerImage"));
		m_wMultiPlayerImage = ImageWidget.Cast(root.FindWidget("LineHeight.OverlayMain.LineContent.LineElements.PlayerCountSize.m_wPlayerCount.m_wMultiPlayerImage"));

		m_wHost = ButtonWidget.Cast(root.FindWidget("LineHeight.OverlayMain.LineContent.LineElements.PlayerCountSize.m_wPlayerCount.m_wHost"));
		m_HostComponent0 = SCR_ModularButtonComponent.Cast(m_wHost.FindHandler(SCR_ModularButtonComponent));
		m_HostComponent1 = SCR_DynamicIconComponent.Cast(m_wHost.FindHandler(SCR_DynamicIconComponent));


		m_wPlay = ButtonWidget.Cast(root.FindWidget("LineHeight.OverlayMain.LineContent.LineElements.PlayerCountSize.m_wPlayerCount.m_wPlay"));
		m_PlayComponent0 = SCR_ModularButtonComponent.Cast(m_wPlay.FindHandler(SCR_ModularButtonComponent));
		m_PlayComponent1 = SCR_DynamicIconComponent.Cast(m_wPlay.FindHandler(SCR_DynamicIconComponent));


		m_wContinue = ButtonWidget.Cast(root.FindWidget("LineHeight.OverlayMain.LineContent.LineElements.PlayerCountSize.m_wPlayerCount.m_wContinue"));
		m_ContinueComponent0 = SCR_ModularButtonComponent.Cast(m_wContinue.FindHandler(SCR_ModularButtonComponent));
		m_ContinueComponent1 = SCR_DynamicIconComponent.Cast(m_wContinue.FindHandler(SCR_DynamicIconComponent));

		m_wSource = HorizontalLayoutWidget.Cast(root.FindWidget("LineHeight.OverlayMain.LineContent.LineElements.SourceSize.m_wSource"));
		m_wSourceImageCommunity = ImageWidget.Cast(root.FindWidget("LineHeight.OverlayMain.LineContent.LineElements.SourceSize.m_wSource.SourceImagesSize.SourceImagesOverlay.m_wSourceImageCommunity"));
		m_wSourceImageOfficial = ImageWidget.Cast(root.FindWidget("LineHeight.OverlayMain.LineContent.LineElements.SourceSize.m_wSource.SourceImagesSize.SourceImagesOverlay.m_SourceImageOfficial"));
		m_wSourceNameTextOfficial = TextWidget.Cast(root.FindWidget("LineHeight.OverlayMain.LineContent.LineElements.SourceSize.m_wSource.SourceNameTextOverlay.m_SourceNameTextOfficial"));
		m_wSourceNameTextCommunity = TextWidget.Cast(root.FindWidget("LineHeight.OverlayMain.LineContent.LineElements.SourceSize.m_wSource.SourceNameTextOverlay.m_wSourceNameTextCommunity"));

		return true;
	}

	//------------------------------------------------------------------------------------------------
	ResourceName GetLayout()
	{
		return LAYOUT;
	}
}
