// Autogenerated by the Generate Class from Layout plugin v0.5.0
// Layout file: UI/layouts/HUD/MortarInfo/MortarInfo.layout
class SCR_MortarInfoWidgets
{
	protected static const ResourceName LAYOUT = "{A4E55F8F1768865F}UI/layouts/HUD/MortarInfo/MortarInfo.layout";

	OverlayWidget m_wElevation;
	OverlayWidget m_wAzimuth;
	OverlayWidget m_wRange;

	//------------------------------------------------------------------------------------------------
	bool Init(Widget root)
	{
		m_wElevation = OverlayWidget.Cast(root.FindWidget("Overlay.m_Elevation"));
		m_wAzimuth = OverlayWidget.Cast(root.FindWidget("Overlay.m_Azimuth"));
		m_wRange = OverlayWidget.Cast(root.FindWidget("Overlay.m_Range"));

		return true;
	}

	//------------------------------------------------------------------------------------------------
	ResourceName GetLayout()
	{
		return LAYOUT;
	}
}
