//! Objective and request notifications types
enum SCR_ETaskNotification
{
	NONE,
	OBJECTIVE_ATTACK,
	OBJECTIVE_BUILDING,
	OBJECTIVE_DISMANTLE,
	OBJECTIVE_ESTABLISH_BASE,
	OBJECTIVE_HOLD,
	OBJECTIVE_RECON,
	OBJECTIVE_RESUPPLY,
	OBJECTIVE_SEIZE,
	OBJECTIVE_TRANSPORT_UNIT,
	REQUEST_ESTABLISH_BASE,
	REQUEST_FIRESUPPORT,
	REQUEST_PICKUP,
	REQUEST_REARM,
	REQUEST_REINFORCE,
	REQUEST_REPAIR,
}
