// Obsolete, don't use, instead use autogenerated SCR_AISendInfoMessage_... nodes
class SCR_AISendInfoMessage: SCR_AISendMessageGeneric
{
	[Attribute("0", UIWidgets.ComboBox, "Message type", "", ParamEnumArray.FromEnum(EMessageType_Info) )]
	private EMessageType_Info m_messageType;


	override ENodeResult EOnTaskSimulate(AIAgent owner, float dt)
	{
		Print("SCR_AISendInfoMessage is obsolete!", LogLevel.WARNING);
		return ENodeResult.FAIL;
	}

	static override string GetOnHoverDescription()
	{
		return "Obsolete! Use autogenerated SCR_AISendInfoMessage_... nodes instead!";
	};
};

class SCR_AISendMessage_ActionFailed : SCR_AISendMessageBase
{
	[Attribute("", UIWidgets.EditBox, "Related action type name")]
	string m_sActionTypename;

	override ENodeResult EOnTaskSimulate(AIAgent owner, float dt)
	{
		if (!InitSendMessageInputs(owner))
			return false;

		SCR_AIMessage_ActionFailed msg = new SCR_AIMessage_ActionFailed();
		msg.SetMessageParameters(this);
		msg.m_ActionTypename = m_sActionTypename.ToType();
		if (!msg.m_ActionTypename)		
			return NodeError(this, owner, "Invalid type provided!");
				
		return SendMessage(owner, msg);
	}

	static override bool VisibleInPalette()
	{
		return true;
	}
};

class SCR_AISendMessage_HealFailed : SCR_AISendMessageBase
{
	const static string PORT_TARGET_ENTITY = "TargetEntity";

	protected static const ref TStringArray s_aVarsIn2 = {PORT_RECEIVER, PORT_TARGET_ENTITY};
	override TStringArray GetVariablesIn()
	{
		return s_aVarsIn2;
	}

	override ENodeResult EOnTaskSimulate(AIAgent owner, float dt)
	{
		if (!InitSendMessageInputs(owner))
			return false;

		SCR_AIMessage_HealFailed msg = new SCR_AIMessage_HealFailed();
		msg.SetMessageParameters(this);

		IEntity targetEntity;
		GetVariableIn(PORT_TARGET_ENTITY, targetEntity);

		msg.m_TargetEntity = targetEntity;

		return SendMessage(owner, msg);
	}

	static override bool VisibleInPalette()
	{
		return true;
	}
};
