enum SCR_ETutorialCourses
{
	FREE_ROAM = 1 << 1,
	OBSTACLE_COURSE = 1 << 2,
	SHOOTING_RANGE = 1 << 3,
	COMBAT_ENGINEERING = 1 << 4,
	CONFLICT = 1 << 5,
	FIRST_AID = 1 << 6,
	DRIVING = 1 << 7,
	NAVIGATION = 1 << 8,
	HELICOPTERS = 1 << 9,
	SPECIAL_WEAPONS = 1 << 10,
	LONG_RANGE_SHOOTING = 1 << 11,
	FIRE_SUPPORT = 1 << 12,
	SQUAD_LEADERSHIP = 1 << 13,
	VEHICLE_MAINTENANCE = 1 << 14,
	INTRO = 1 << 15,
	OUTRO = 1 << 16,
}