enum SCR_ETutorialArlandStageMasters
{
	HUB,
	BASIC_TUTORIAL_SIMPLE,
	WEAPONS_TUTORIAL_SIMPLE,
	CONFLICT_TUTORIAL_BASE_BUILDING,
	CONFLICT_TUTORIAL_BESIEGING,
	CONFLICT_TUTORIAL_BASE_TOUR,
	MEDICAL,
	HELICOPTERS_SIMPLE,
	HELICOPTERS_ADVANCED,
	DRIVING_SIMPLE,
	DRIVING_ADVANCED,
	WEAPONS_ARSENAL,
	NAVIGATION,
	HELICOPTERS,
	FALLBACKS,
}