// Autogenerated by the Generate Class from Layout plugin v0.5.0
// Layout file: UI/layouts/Menus/ContentBrowser/Dialogs/ModDetailsAdditionalInfoDialogContent.layout
class SCR_ModDetailsAdditionalInfoDialogContentWidgets
{
	protected static const ResourceName LAYOUT = "{9C94E0B41C8EE124}UI/layouts/Menus/ContentBrowser/Dialogs/ModDetailsAdditionalInfoDialogContent.layout";

	VerticalLayoutWidget m_wVerticalLayoutLicense;
	RichTextWidget m_wLicenseName;
	OverlayWidget m_wLicenseContentOverlay;
	RichTextWidget m_wLicenseContent;
	VerticalLayoutWidget m_wVerticalLayoutContributors;
	OverlayWidget m_wContributorsContentOverlay;
	RichTextWidget m_wContributorsContent;

	OverlayWidget m_wLoadingOverlay;
	SCR_LoadingOverlay m_LoadingOverlayComponent;

	BlurWidget m_wBlur;
	ImageWidget m_wBackgroundImage;

	ImageWidget m_wAnimationImage;
	SCR_SpinningWidgetComponent m_AnimationImageComponent;

	TextWidget m_wText;

	//------------------------------------------------------------------------------------------------
	bool Init(Widget root)
	{
		m_wVerticalLayoutLicense = VerticalLayoutWidget.Cast(root.FindWidget("ScrollLayoutMain.VerticalLayoutMain.m_VerticalLayoutLicense"));
		m_wLicenseName = RichTextWidget.Cast(root.FindWidget("ScrollLayoutMain.VerticalLayoutMain.m_VerticalLayoutLicense.LicenseContent.m_wLicenseName"));
		m_wLicenseContentOverlay = OverlayWidget.Cast(root.FindWidget("ScrollLayoutMain.VerticalLayoutMain.m_VerticalLayoutLicense.LicenseContent.m_wLicenseContentOverlay"));
		m_wLicenseContent = RichTextWidget.Cast(root.FindWidget("ScrollLayoutMain.VerticalLayoutMain.m_VerticalLayoutLicense.LicenseContent.m_wLicenseContentOverlay.m_wLicenseContent"));
		m_wVerticalLayoutContributors = VerticalLayoutWidget.Cast(root.FindWidget("ScrollLayoutMain.VerticalLayoutMain.m_VerticalLayoutContributors"));
		m_wContributorsContentOverlay = OverlayWidget.Cast(root.FindWidget("ScrollLayoutMain.VerticalLayoutMain.m_VerticalLayoutContributors.ContributorsContent.m_wContributorsContentOverlay"));
		m_wContributorsContent = RichTextWidget.Cast(root.FindWidget("ScrollLayoutMain.VerticalLayoutMain.m_VerticalLayoutContributors.ContributorsContent.m_wContributorsContentOverlay.m_wContributorsContent"));

		m_wLoadingOverlay = OverlayWidget.Cast(root.FindWidget("m_LoadingOverlay"));
		m_LoadingOverlayComponent = SCR_LoadingOverlay.Cast(m_wLoadingOverlay.FindHandler(SCR_LoadingOverlay));

		m_wBlur = BlurWidget.Cast(root.FindWidget("m_LoadingOverlay.rootFrame0.m_Blur"));
		m_wBackgroundImage = ImageWidget.Cast(root.FindWidget("m_LoadingOverlay.rootFrame0.m_BackgroundImage"));

		m_wAnimationImage = ImageWidget.Cast(root.FindWidget("m_LoadingOverlay.rootFrame0.m_AnimationImage"));
		m_AnimationImageComponent = SCR_SpinningWidgetComponent.Cast(m_wAnimationImage.FindHandler(SCR_SpinningWidgetComponent));

		m_wText = TextWidget.Cast(root.FindWidget("m_LoadingOverlay.rootFrame0.m_Text"));

		return true;
	}

	//------------------------------------------------------------------------------------------------
	ResourceName GetLayout()
	{
		return LAYOUT;
	}
}
