// Autogenerated by the Generate Class from Layout plugin v0.5.1
// Layout file: UI/layouts/Menus/Dialogs/FeedbackDialogContent.layout
class SCR_FeedbackDialogContentWidgets
{
	protected static const ResourceName LAYOUT = "{6A295DBEDD4EC025}UI/layouts/Menus/Dialogs/FeedbackDialogContent.layout";

	ButtonWidget m_wFeedbackType;
	SCR_ComboBoxComponent m_FeedbackTypeComponent0;
	SCR_ModularButtonComponent m_FeedbackTypeComponent1;


	ButtonWidget m_wFeedbackCategory;
	SCR_ComboBoxComponent m_FeedbackCategoryComponent0;
	SCR_ModularButtonComponent m_FeedbackCategoryComponent1;


	ButtonWidget m_wConsoleFeedbackTopic;
	SCR_ComboBoxComponent m_ConsoleFeedbackTopicComponent0;
	SCR_ModularButtonComponent m_ConsoleFeedbackTopicComponent1;


	ButtonWidget m_wFeedbackEditBox;
	SCR_EditBoxComponent m_FeedbackEditBoxComponent;

	VerticalLayoutWidget m_wAttachFileVertialLayout;

	ButtonWidget m_wAttachFileButton;
	SCR_ModularButtonComponent m_AttachFileButtonComponent;


	ButtonWidget m_wAttachLogsButton;
	SCR_ButtonCheckerComponent m_AttachLogsButtonComponent;


	//------------------------------------------------------------------------------------------------
	bool Init(notnull Widget root)
	{
		m_wFeedbackType = ButtonWidget.Cast(root.FindWidget("FeedBackVerticalLayout.m_wFeedbackType"));
		m_FeedbackTypeComponent0 = SCR_ComboBoxComponent.Cast(m_wFeedbackType.FindHandler(SCR_ComboBoxComponent));
		m_FeedbackTypeComponent1 = SCR_ModularButtonComponent.Cast(m_wFeedbackType.FindHandler(SCR_ModularButtonComponent));


		m_wFeedbackCategory = ButtonWidget.Cast(root.FindWidget("FeedBackVerticalLayout.m_wFeedbackCategory"));
		m_FeedbackCategoryComponent0 = SCR_ComboBoxComponent.Cast(m_wFeedbackCategory.FindHandler(SCR_ComboBoxComponent));
		m_FeedbackCategoryComponent1 = SCR_ModularButtonComponent.Cast(m_wFeedbackCategory.FindHandler(SCR_ModularButtonComponent));


		m_wConsoleFeedbackTopic = ButtonWidget.Cast(root.FindWidget("FeedBackVerticalLayout.m_wConsoleFeedbackTopic"));
		m_ConsoleFeedbackTopicComponent0 = SCR_ComboBoxComponent.Cast(m_wConsoleFeedbackTopic.FindHandler(SCR_ComboBoxComponent));
		m_ConsoleFeedbackTopicComponent1 = SCR_ModularButtonComponent.Cast(m_wConsoleFeedbackTopic.FindHandler(SCR_ModularButtonComponent));


		m_wFeedbackEditBox = ButtonWidget.Cast(root.FindWidget("FeedBackVerticalLayout.m_wFeedbackEditBox"));
		m_FeedbackEditBoxComponent = SCR_EditBoxComponent.Cast(m_wFeedbackEditBox.FindHandler(SCR_EditBoxComponent));

		m_wAttachFileVertialLayout = VerticalLayoutWidget.Cast(root.FindWidget("m_wAttachFileVertialLayout"));

		m_wAttachFileButton = ButtonWidget.Cast(root.FindWidget("m_wAttachFileVertialLayout.AttachFileButtonSize.m_wAttachFileButton"));
		m_AttachFileButtonComponent = SCR_ModularButtonComponent.Cast(m_wAttachFileButton.FindHandler(SCR_ModularButtonComponent));


		m_wAttachLogsButton = ButtonWidget.Cast(root.FindWidget("m_wAttachFileVertialLayout.SizeLayout0.m_wAttachLogsButton"));
		m_AttachLogsButtonComponent = SCR_ButtonCheckerComponent.Cast(m_wAttachLogsButton.FindHandler(SCR_ButtonCheckerComponent));


		return true;
	}

	//------------------------------------------------------------------------------------------------
	ResourceName GetLayout()
	{
		return LAYOUT;
	}
}
