// Autogenerated by the Generate Class from Layout plugin, version 0.3.0
// Layout file: UI/layouts/Menus/ContentBrowser/MainMenu/ContentBrowser_AddonsSubMenuBase.layout

class SCR_ContentBrowser_AddonsSubMenuBaseWidgets
{
	static const ResourceName s_sLayout = "{FACCFE81F2C2C1FD}UI/layouts/Menus/ContentBrowser/MainMenu/ContentBrowser_AddonsSubMenuBase.layout";
	ResourceName GetLayout() { return s_sLayout; }

	OverlayWidget m_LeftPanelArea;

	SizeLayoutWidget m_LeftPanel;

	HorizontalLayoutWidget m_SortingHeader;
	SCR_SortHeaderComponent m_SortingHeaderComponent;

	GridLayoutWidget m_Grid;

	HorizontalLayoutWidget m_PagingButtons;

	ButtonWidget m_PrevPageButton;
	SCR_InputButtonComponent m_PrevPageButtonComponent;

	ButtonWidget m_PrevPageButton_NoScroll;
	SCR_InputButtonComponent m_PrevPageButton_NoScrollComponent;

	TextWidget m_PageIndicatorText;

	ButtonWidget m_NextPageButton;
	SCR_InputButtonComponent m_NextPageButtonComponent;

	ButtonWidget m_NextPageButton_NoScroll;
	SCR_InputButtonComponent m_NextPageButton_NoScrollComponent;

	OverlayWidget m_MainPanelMessage;
	SCR_SimpleMessageComponent m_MainPanelMessageComponent;

	OverlayWidget m_FilterPanel;
	SCR_FilterPanelComponent m_FilterPanelComponent;

	OverlayWidget m_MainContent;

	OverlayWidget m_AddonDetailsPanel;
	SCR_AddonDetailsPanelComponent m_AddonDetailsPanelComponent;

	SizeLayoutWidget m_EmptyPanel;

	OverlayWidget m_EmptyPanelMessage;
	SCR_SimpleMessageComponent m_EmptyPanelMessageComponent;

	bool Init(Widget root)
	{
		m_LeftPanelArea = OverlayWidget.Cast(root.FindWidget("Size.PanelsHorizontal.m_LeftPanelArea"));

		m_LeftPanel = SizeLayoutWidget.Cast(root.FindWidget("Size.PanelsHorizontal.m_LeftPanelArea.m_LeftPanel"));

		m_SortingHeader = HorizontalLayoutWidget.Cast(root.FindWidget("Size.PanelsHorizontal.m_LeftPanelArea.m_LeftPanel.VerticalLayout0.TopBarHeight.TopBar.Content.m_SortingHeader"));
		m_SortingHeaderComponent = SCR_SortHeaderComponent.Cast(m_SortingHeader.FindHandler(SCR_SortHeaderComponent));

		m_Grid = GridLayoutWidget.Cast(root.FindWidget("Size.PanelsHorizontal.m_LeftPanelArea.m_LeftPanel.VerticalLayout0.Content.GridAndPagingButtons.m_Grid"));

		m_PagingButtons = HorizontalLayoutWidget.Cast(root.FindWidget("Size.PanelsHorizontal.m_LeftPanelArea.m_LeftPanel.VerticalLayout0.Content.GridAndPagingButtons.m_PagingButtons"));

		m_PrevPageButton = ButtonWidget.Cast(root.FindWidget("Size.PanelsHorizontal.m_LeftPanelArea.m_LeftPanel.VerticalLayout0.Content.GridAndPagingButtons.m_PagingButtons.PrevButton"));
		m_PrevPageButtonComponent = SCR_InputButtonComponent.Cast(m_PrevPageButton.FindHandler(SCR_InputButtonComponent));

		m_PrevPageButton_NoScroll = ButtonWidget.Cast(root.FindWidget("Size.PanelsHorizontal.m_LeftPanelArea.m_LeftPanel.VerticalLayout0.Content.GridAndPagingButtons.m_PagingButtons.PrevButton_NoScroll"));
		m_PrevPageButton_NoScrollComponent = SCR_InputButtonComponent.Cast(m_PrevPageButton_NoScroll.FindHandler(SCR_InputButtonComponent));

		m_PageIndicatorText = TextWidget.Cast(root.FindWidget("Size.PanelsHorizontal.m_LeftPanelArea.m_LeftPanel.VerticalLayout0.Content.GridAndPagingButtons.m_PagingButtons.Pages"));

		m_NextPageButton = ButtonWidget.Cast(root.FindWidget("Size.PanelsHorizontal.m_LeftPanelArea.m_LeftPanel.VerticalLayout0.Content.GridAndPagingButtons.m_PagingButtons.NextButton"));
		m_NextPageButtonComponent = SCR_InputButtonComponent.Cast(m_NextPageButton.FindHandler(SCR_InputButtonComponent));

		m_NextPageButton_NoScroll = ButtonWidget.Cast(root.FindWidget("Size.PanelsHorizontal.m_LeftPanelArea.m_LeftPanel.VerticalLayout0.Content.GridAndPagingButtons.m_PagingButtons.NextButton_NoScroll"));
		m_NextPageButton_NoScrollComponent = SCR_InputButtonComponent.Cast(m_NextPageButton_NoScroll.FindHandler(SCR_InputButtonComponent));

		m_MainPanelMessage = OverlayWidget.Cast(root.FindWidget("Size.PanelsHorizontal.m_LeftPanelArea.m_LeftPanel.VerticalLayout0.Content.m_MainPanelMessage"));
		m_MainPanelMessageComponent = SCR_SimpleMessageComponent.Cast(m_MainPanelMessage.FindHandler(SCR_SimpleMessageComponent));

		m_FilterPanel = OverlayWidget.Cast(root.FindWidget("Size.PanelsHorizontal.m_FilterPanel"));
		m_FilterPanelComponent = SCR_FilterPanelComponent.Cast(m_FilterPanel.FindHandler(SCR_FilterPanelComponent));

		m_MainContent = OverlayWidget.Cast(root.FindWidget("Size.PanelsHorizontal.m_FilterPanel.MenuPanel0.VerticalLayout0.Content.m_MainContent"));

		m_AddonDetailsPanel = OverlayWidget.Cast(root.FindWidget("Size.PanelsHorizontal.m_FilterPanel.MenuPanel0.VerticalLayout0.Content.m_MainContent.m_AddonDetailsPanel"));
		m_AddonDetailsPanelComponent = SCR_AddonDetailsPanelComponent.Cast(m_AddonDetailsPanel.FindHandler(SCR_AddonDetailsPanelComponent));

		m_EmptyPanel = SizeLayoutWidget.Cast(root.FindWidget("Size.PanelsHorizontal.m_EmptyPanel"));

		m_EmptyPanelMessage = OverlayWidget.Cast(root.FindWidget("Size.PanelsHorizontal.m_EmptyPanel.VerticalLayout0.Content.m_EmptyPanelMessage"));
		m_EmptyPanelMessageComponent = SCR_SimpleMessageComponent.Cast(m_EmptyPanelMessage.FindHandler(SCR_SimpleMessageComponent));

		return true;
	}
};
