// Autogenerated by the Generate Class from Layout plugin v0.5.1
// Layout file: UI/layouts/Menus/ContentBrowser/ScenariosMenu/HeaderNavigation.layout
class SCR_HeaderNavigationWidgets
{
	protected static const ResourceName LAYOUT = "{4C3FA7E7A3A293FE}UI/layouts/Menus/ContentBrowser/ScenariosMenu/HeaderNavigation.layout";

	ButtonWidget m_wNavButtonLeft;
	SCR_InputButtonComponent m_NavButtonLeftComponent;

	HorizontalLayoutWidget m_wHorizontalItems;

	ButtonWidget m_wNavButtonRight;
	SCR_InputButtonComponent m_NavButtonRightComponent;

	//------------------------------------------------------------------------------------------------
	bool Init(notnull Widget root)
	{
		m_wNavButtonLeft = ButtonWidget.Cast(root.FindWidget("horizontalHeader.m_wNavButtonLeft"));
		m_NavButtonLeftComponent = SCR_InputButtonComponent.Cast(m_wNavButtonLeft.FindHandler(SCR_InputButtonComponent));

		m_wHorizontalItems = HorizontalLayoutWidget.Cast(root.FindWidget("horizontalHeader.m_wHorizontalItems"));

		m_wNavButtonRight = ButtonWidget.Cast(root.FindWidget("horizontalHeader.m_wNavButtonRight"));
		m_NavButtonRightComponent = SCR_InputButtonComponent.Cast(m_wNavButtonRight.FindHandler(SCR_InputButtonComponent));

		return true;
	}

	//------------------------------------------------------------------------------------------------
	ResourceName GetLayout()
	{
		return LAYOUT;
	}
}
