// Autogenerated by the Generate Class from Layout plugin v0.5.1
// Layout file: UI/layouts/HUD/InteractionSystem/ActionMenuSnackBar.layout
class SCR_ActionMenuSnackBarWidgets
{
	protected static const ResourceName LAYOUT = "{1D3B10902C8F8FEA}UI/layouts/HUD/InteractionSystem/ActionMenuSnackBar.layout";

	OverlayWidget m_wSnackBarOverlay;
	ImageWidget m_wSnackBarBackgroundImgLeft;
	ImageWidget m_wSnackBarBackgroundImgMid;
	ImageWidget m_wSnackBarBackgroundImgRight;
	ImageWidget m_wSnackBarIconGlow;
	ImageWidget m_wSnackBarIcon;
	TextWidget m_wSnackBarText;

	//------------------------------------------------------------------------------------------------
	bool Init(notnull Widget root)
	{
		m_wSnackBarOverlay = OverlayWidget.Cast(root.FindWidget("m_wSnackBarOverlay"));
		m_wSnackBarBackgroundImgLeft = ImageWidget.Cast(root.FindWidget("m_wSnackBarOverlay.BackgroundOverlay.BackgroundHorizontalLayout.m_wSnackBarBackgroundImgLeft"));
		m_wSnackBarBackgroundImgMid = ImageWidget.Cast(root.FindWidget("m_wSnackBarOverlay.BackgroundOverlay.BackgroundHorizontalLayout.m_wSnackBarBackgroundImgMid"));
		m_wSnackBarBackgroundImgRight = ImageWidget.Cast(root.FindWidget("m_wSnackBarOverlay.BackgroundOverlay.BackgroundHorizontalLayout.m_wSnackBarBackgroundImgRight"));
		m_wSnackBarIconGlow = ImageWidget.Cast(root.FindWidget("m_wSnackBarOverlay.SnackBarHorizontalLayout.IconOverlay.m_wSnackBarIconGlow"));
		m_wSnackBarIcon = ImageWidget.Cast(root.FindWidget("m_wSnackBarOverlay.SnackBarHorizontalLayout.IconOverlay.m_wSnackBarIcon"));
		m_wSnackBarText = TextWidget.Cast(root.FindWidget("m_wSnackBarOverlay.SnackBarHorizontalLayout.m_wSnackBarText"));

		return true;
	}

	//------------------------------------------------------------------------------------------------
	ResourceName GetLayout()
	{
		return LAYOUT;
	}
}
