// Autogenerated by the Generate Class from Layout plugin v0.5.1
// Layout file: UI/layouts/HUD/InteractionSystem/ActionMenuLayout.layout
class SCR_ActionMenuLayoutWidgets
{
	protected static const ResourceName LAYOUT = "{F2B2EB0B4DB2ADB1}UI/layouts/HUD/InteractionSystem/ActionMenuLayout.layout";

	FrameWidget m_wActionMenuRoot;

	FrameWidget m_wIconOverlay;
	SCR_NearbyContextWidgetComponentInteract m_IconOverlayComponent;

	OverlayWidget m_wOverlayBackground;
	ImageWidget m_wBackgroundShadowInner;
	ImageWidget m_wBackground;
	ImageWidget m_wBackgroundShadowOuter;
	ImageWidget m_wBackgroundOuter;
	ImageWidget m_wIconGlow;
	ImageWidget m_wIcon;
	OverlayWidget m_wOutlineOverlay;
	ImageWidget m_wOutlineBackgroundGlow;
	ImageWidget m_wOutlineBackground;
	ImageWidget m_wOutlineProgressGlow;
	ImageWidget m_wOutlineProgress;

	OverlayWidget m_wButtonOverlay;
	SCR_ActionMenuInputButtonComponent m_ButtonOverlayComponent;


	SizeLayoutWidget m_wInputButtonDisplayRoot;
	SCR_InputButtonDisplay m_InputButtonDisplayRootComponent;

	OverlayWidget m_wOverlay;
	ImageWidget m_wGlow;
	ImageWidget m_wOutlineClear;
	ImageWidget m_wOutline;
	ImageWidget m_wButtonImgGlow;
	ImageWidget m_wKeyBG;
	ImageWidget m_wDoubleTabIndicator;
	ImageWidget m_wHoldIndicator;
	ImageWidget m_wButtonImg;
	VerticalLayoutWidget m_wVerticalLayout0;
	RichTextWidget m_wButtonText;
	VerticalLayoutWidget m_wActionMenu;

	//------------------------------------------------------------------------------------------------
	bool Init(notnull Widget root)
	{
		m_wActionMenuRoot = FrameWidget.Cast(root.FindWidget("_error_"));

		m_wIconOverlay = FrameWidget.Cast(root.FindWidget("m_wIconOverlay"));
		m_IconOverlayComponent = SCR_NearbyContextWidgetComponentInteract.Cast(m_wIconOverlay.FindHandler(SCR_NearbyContextWidgetComponentInteract));

		m_wOverlayBackground = OverlayWidget.Cast(root.FindWidget("m_wIconOverlay.m_wOverlayBackground"));
		m_wBackgroundShadowInner = ImageWidget.Cast(root.FindWidget("m_wIconOverlay.m_wOverlayBackground.m_wBackgroundShadowInner"));
		m_wBackground = ImageWidget.Cast(root.FindWidget("m_wIconOverlay.m_wOverlayBackground.m_wBackground"));
		m_wBackgroundShadowOuter = ImageWidget.Cast(root.FindWidget("m_wIconOverlay.m_wOverlayBackground.m_wBackgroundShadowOuter"));
		m_wBackgroundOuter = ImageWidget.Cast(root.FindWidget("m_wIconOverlay.m_wOverlayBackground.m_wBackgroundOuter"));
		m_wIconGlow = ImageWidget.Cast(root.FindWidget("m_wIconOverlay.m_wOverlayBackground.IconSize.Overlay_Icon.m_wIconGlow"));
		m_wIcon = ImageWidget.Cast(root.FindWidget("m_wIconOverlay.m_wOverlayBackground.IconSize.Overlay_Icon.m_wIcon"));
		m_wOutlineOverlay = OverlayWidget.Cast(root.FindWidget("m_wOutlineOverlay"));
		m_wOutlineBackgroundGlow = ImageWidget.Cast(root.FindWidget("m_wOutlineOverlay.m_wOutlineBackgroundGlow"));
		m_wOutlineBackground = ImageWidget.Cast(root.FindWidget("m_wOutlineOverlay.m_wOutlineBackground"));
		m_wOutlineProgressGlow = ImageWidget.Cast(root.FindWidget("m_wOutlineOverlay.m_wOutlineProgressGlow"));
		m_wOutlineProgress = ImageWidget.Cast(root.FindWidget("m_wOutlineOverlay.m_wOutlineProgress"));

		m_wButtonOverlay = OverlayWidget.Cast(root.FindWidget("m_wButtonOverlay"));
		m_ButtonOverlayComponent = SCR_ActionMenuInputButtonComponent.Cast(m_wButtonOverlay.FindHandler(SCR_ActionMenuInputButtonComponent));


		m_wInputButtonDisplayRoot = SizeLayoutWidget.Cast(root.FindWidget("m_wButtonOverlay.m_wInputButtonDisplayRoot"));
		m_InputButtonDisplayRootComponent = SCR_InputButtonDisplay.Cast(m_wInputButtonDisplayRoot.FindHandler(SCR_InputButtonDisplay));

		m_wOverlay = OverlayWidget.Cast(root.FindWidget("m_wButtonOverlay.m_wInputButtonDisplayRoot.m_Overlay"));
		m_wGlow = ImageWidget.Cast(root.FindWidget("m_wButtonOverlay.m_wInputButtonDisplayRoot.m_Overlay.m_Glow"));
		m_wOutlineClear = ImageWidget.Cast(root.FindWidget("m_wButtonOverlay.m_wInputButtonDisplayRoot.m_Overlay.m_OutlineClear"));
		m_wOutline = ImageWidget.Cast(root.FindWidget("m_wButtonOverlay.m_wInputButtonDisplayRoot.m_Overlay.m_Outline"));
		m_wButtonImgGlow = ImageWidget.Cast(root.FindWidget("m_wButtonOverlay.m_wInputButtonDisplayRoot.m_Overlay.Shadow_Overlay.m_ButtonImgGlow"));
		m_wKeyBG = ImageWidget.Cast(root.FindWidget("m_wButtonOverlay.m_wInputButtonDisplayRoot.m_Overlay.Overlay0.m_KeyBG"));
		m_wDoubleTabIndicator = ImageWidget.Cast(root.FindWidget("m_wButtonOverlay.m_wInputButtonDisplayRoot.m_Overlay.Overlay0.m_DoubleTabIndicator"));
		m_wHoldIndicator = ImageWidget.Cast(root.FindWidget("m_wButtonOverlay.m_wInputButtonDisplayRoot.m_Overlay.Frame0.m_HoldIndicator"));
		m_wButtonImg = ImageWidget.Cast(root.FindWidget("m_wButtonOverlay.m_wInputButtonDisplayRoot.m_Overlay.m_ButtonImg"));
		m_wVerticalLayout0 = VerticalLayoutWidget.Cast(root.FindWidget("m_wButtonOverlay.m_wInputButtonDisplayRoot.m_Overlay.SizeLayout0.m_VerticalLayout0"));
		m_wButtonText = RichTextWidget.Cast(root.FindWidget("m_wButtonOverlay.m_wInputButtonDisplayRoot.m_Overlay.SizeLayout0.m_VerticalLayout0.m_ButtonText"));
		m_wActionMenu = VerticalLayoutWidget.Cast(root.FindWidget("m_wActionMenu"));

		return true;
	}

	//------------------------------------------------------------------------------------------------
	ResourceName GetLayout()
	{
		return LAYOUT;
	}
}
