// Autogenerated by the Generate Class from Layout plugin v0.5.1
// Layout file: UI/layouts/HUD/InteractionSystem/ActionMenuElement.layout
class SCR_ActionMenuElementWidgets
{
	protected static const ResourceName LAYOUT = "{C80DEB58AA948E59}UI/layouts/HUD/InteractionSystem/ActionMenuElement.layout";

	FrameWidget m_wIconOverlay;
	SCR_NearbyContextWidgetComponentInteract m_IconOverlayComponent;

	OverlayWidget m_wOverlayBackground;
	ImageWidget m_wBackgroundShadowInner;
	ImageWidget m_wBackground;
	ImageWidget m_wBackgroundShadowOuter;
	ImageWidget m_wBackgroundOuter;
	ImageWidget m_wIconGlow;
	ImageWidget m_wIcon;
	OverlayWidget m_wActionBackground;
	SmartPanelWidget m_wBackgroundShadow;
	BlurWidget m_wBackgroundBlur;
	TextWidget m_wActionText;
	TextWidget m_wActionContext;

	//------------------------------------------------------------------------------------------------
	bool Init(notnull Widget root)
	{
		m_wIconOverlay = FrameWidget.Cast(root.FindWidget("SizeLayoutMain.ActionHorizontalElement.m_wIconOverlay"));
		m_IconOverlayComponent = SCR_NearbyContextWidgetComponentInteract.Cast(m_wIconOverlay.FindHandler(SCR_NearbyContextWidgetComponentInteract));

		m_wOverlayBackground = OverlayWidget.Cast(root.FindWidget("SizeLayoutMain.ActionHorizontalElement.m_wIconOverlay.m_wOverlayBackground"));
		m_wBackgroundShadowInner = ImageWidget.Cast(root.FindWidget("SizeLayoutMain.ActionHorizontalElement.m_wIconOverlay.m_wOverlayBackground.m_wBackgroundShadowInner"));
		m_wBackground = ImageWidget.Cast(root.FindWidget("SizeLayoutMain.ActionHorizontalElement.m_wIconOverlay.m_wOverlayBackground.m_wBackground"));
		m_wBackgroundShadowOuter = ImageWidget.Cast(root.FindWidget("SizeLayoutMain.ActionHorizontalElement.m_wIconOverlay.m_wOverlayBackground.m_wBackgroundShadowOuter"));
		m_wBackgroundOuter = ImageWidget.Cast(root.FindWidget("SizeLayoutMain.ActionHorizontalElement.m_wIconOverlay.m_wOverlayBackground.m_wBackgroundOuter"));
		m_wIconGlow = ImageWidget.Cast(root.FindWidget("SizeLayoutMain.ActionHorizontalElement.m_wIconOverlay.m_wOverlayBackground.IconSize.Overlay_Icon.m_wIconGlow"));
		m_wIcon = ImageWidget.Cast(root.FindWidget("SizeLayoutMain.ActionHorizontalElement.m_wIconOverlay.m_wOverlayBackground.IconSize.Overlay_Icon.m_wIcon"));
		m_wActionBackground = OverlayWidget.Cast(root.FindWidget("SizeLayoutMain.ActionHorizontalElement.TextOverlay.SizeLayout0.m_wActionBackground"));
		m_wBackgroundShadow = SmartPanelWidget.Cast(root.FindWidget("SizeLayoutMain.ActionHorizontalElement.TextOverlay.SizeLayout0.m_wActionBackground.m_wBackgroundShadow"));
		m_wBackgroundBlur = BlurWidget.Cast(root.FindWidget("SizeLayoutMain.ActionHorizontalElement.TextOverlay.SizeLayout0.m_wActionBackground.m_wBackgroundBlur"));
		m_wActionText = TextWidget.Cast(root.FindWidget("SizeLayoutMain.ActionHorizontalElement.TextOverlay.TextHorizontalLayout.m_wActionText"));
		m_wActionContext = TextWidget.Cast(root.FindWidget("SizeLayoutMain.ActionHorizontalElement.TextOverlay.TextHorizontalLayout.m_wActionContext"));

		return true;
	}

	//------------------------------------------------------------------------------------------------
	ResourceName GetLayout()
	{
		return LAYOUT;
	}
}
