//------------------------------------------------------------------------------------------------
//! This enum contains all IDs for DiagMenu entries added in script.
enum SCR_DebugMenuID
{
	// Camera
	DEBUGUI_DRAW_CAMERA_COLLISION_SOLVER = 0,

	// Character
	DEBUGUI_CHARACTER_MENU,
	DEBUGUI_CHARACTER_NOBANKING,
	DEBUGUI_CHARACTER_MUZZLE_CROSSHAIR,
	DEBUGUI_CHARACTER_DEBUG_VIEW,
	DEBUGUI_CHARACTER_ADS_CAMERA,
	//DEBUGUI_CHARACTER_WEAPON_MECHANICS,
	//DEBUGUI_CHARACTER_HEAD_HACK,
	DEBUGUI_CHARACTER_DAMAGE,
	DEBUGUI_CHARACTER_POSTPROCESSING_EFFECTS,
	DEBUGUI_CHARACTER_TRANSFORMATION,
	DEBUGUI_CHARACTER_HITREACTION_AIMMODIFIER,
	DEBUGUI_CHARACTER_RECOIL_CAMERASHAKE_DISABLE,
	DEBUGUI_CHARACTER_ADDITIONAL_CAMERASHAKE_DISABLE,
	DEBUGUI_CHARACTER_CAMERASHAKE_TEST_WINDOW,
	DEBUGUI_CHARACTER_LOG_PLAYER_DAMAGE,
	DEBUGUI_CHARACTER_SHOW_FACTION_OUTFIT,
	DEBUGUI_CHARACTER_SHOW_XP,

	// Interactions
	DEBUGUI_INTERACTION_MENU,
	DEBUGUI_INTERACTION_HANDLER,
	DEBUGUI_INTERACTION_ADVANCED,
	DEBUGUI_INTERACTION_ENTITY,
	DEBUGUI_INTERACTION_NEARBY_CONTEXTS,
	DEBUGUI_INTERACTION_CONTEXT_DISTANCE,
	DEBUGUI_INTERACTION_CONTEXT_GIZMO_SCALE,
	DEBUGUI_INTERACTION_CONTEXT_DISTANCE_SCALE,
	DEBUGUI_INTERACTION_ALL_INSTANT,
	DEBUGUI_INTERACTION_SKIP_DURATION,
	DEBUGUI_ITEM_PLACEMENT_VISUALIZATION,

	// Radial menu
	DEBUGUI_RADIALMENU_MENU,
	DEBUGUI_RADIALMENU_DIAGNOSTICS,
	DEBUGUI_RADIALMENU_LOGGING,
	DEBUGUI_RADIALMENU_CONFIG_DEBUG,
	DEBUGUI_RADIALMENU_CLOSE_ON_RELEASE_OPEN,
	DEBUGUI_RADIALMENU_PERFORM_ON_CLOSE,
	DEBUGUI_RADIALMENU_CLOSE_ON_PERFORM,
	DEBUGUI_RADIALMENU_DESELECT_IN_CENTER,
	DEBUGUI_RADIALMENU_USE_LARGE_SIZE,
	DEBUGUI_RADIALMENU_CUSTOM_SIZE_ENABLE,
	DEBUGUI_RADIALMENU_CUSTOM_SIZE,
	DEBUGUI_RADIALMENU_ENTRY_COUNT_ENABLE,
	DEBUGUI_RADIALMENU_ENTRY_COUNT,

	// Inventory
	DEBUGUI_INVENTORY,

	// Nametags
	DEBUGUI_NAMETAGS,

	// GameMode
	DEBUGUI_GAME_MODE_MENU,
	DEBUGUI_GAME_MODE,
	DEBUGUI_SCORING_SYSTEM,
	DEBUGUI_RESPAWN_TIMER_COMPONENT,
	DEBUGUI_CHARACTER_KILLED_LOG,

	// Survival
	DEBUGUI_SURVIVAL_MENU,
	DEBUGUI_SURVIVAL_SHOW_DEBUG_HUD,

	// Sounds
	DEBUGUI_SOUNDS_RANDOM_POSITIONAL_SOUNDS,
	DEBUGUI_SOUNDS_RELOAD_AMBIENT_SOUNDS_CONFIGS,
	DEBUGUI_SOUNDS_MPDESTRUCTION_SHOW_IMPULSEVALUES,
	DEBUGUI_SOUNDS_PRINT_MELEESURFACE,
	DEBUGUI_SOUNDS_SOUND_MANAGER,
	DEBUGUI_SOUNDS_GLOBAL_VARIABLES,

	// Input manager
	DEBUGUI_INPUT_MANAGER,

	// Editor
	DEBUGUI_EDITOR,
	DEBUGUI_EDITOR_SHOW_DEBUG,
	DEBUGUI_EDITOR_IS_OPENED,
	DEBUGUI_EDITOR_CAN_OPEN,
	DEBUGUI_EDITOR_CAN_CLOSE,
	DEBUGUI_EDITOR_FORCE_LIMITED,
	DEBUGUI_EDITOR_LOG_GLOBAL_ATTRIBUTES,
	DEBUGUI_EDITOR_MODE,
	DEBUGUI_EDITOR_ASYNC_LOAD_DEBUG,
	DEBUGUI_EDITOR_NETWORK_DELAY,
	DEBUGUI_EDITOR_SAVE_PHOTO_SCREENSHOT_SHOW,

	DEBUGUI_EDITOR_ENTITIES,
	DEBUGUI_EDITOR_ENTITIES_LOG_ALL,
	DEBUGUI_EDITOR_ENTITIES_LOG_TYPE,
	DEBUGUI_EDITOR_ENTITIES_LOG_AVAILABLE,
	DEBUGUI_EDITOR_ENTITIES_LOG_ACCESS_KEYS,
	DEBUGUI_EDITOR_ENTITIES_ACCESS_KEY,
	DEBUGUI_EDITOR_ENTITIES_ACCESS_KEY_TOGGLE,
	DEBUGUI_EDITOR_ENTITIES_ACCESS_KEY_ADMIN,
	DEBUGUI_EDITOR_ENTITIES_SELECT_LOG,
	DEBUGUI_EDITOR_ENTITIES_SELECT_ALL,
	DEBUGUI_EDITOR_ENTITIES_SELECT_NONE,
	DEBUGUI_EDITOR_ENTITIES_TEST_ENTITY_ACCESS_KEY,
	DEBUGUI_EDITOR_ENTITIES_TEST_ENTITY_ACCESS_KEY_TOGGLE,
	DEBUGUI_EDITOR_ENTITIES_TEST_ENTITY_LAYER,
	DEBUGUI_EDITOR_ENTITIES_TEST_ENTITY_SELECT,
	DEBUGUI_EDITOR_ENTITIES_TEST_ENTITY_FOCUS,
	DEBUGUI_EDITOR_ENTITIES_TEST_ENTITY_SHOW,
	DEBUGUI_EDITOR_ENTITIES_BUDGET_CAP,
	DEBUGUI_EDITOR_ENTITIES_LOG_BUDGET_CHANGES,
	DEBUGUI_EDITOR_SPECIFIC_LOG,
	DEBUGUI_EDITOR_ENTITIES_DISABLE,

	DEBUGUI_EDITOR_ACTIONS_MENU,
	DEBUGUI_EDITOR_ACTIONS_MENU_ICONS,
	DEBUGUI_EDITOR_ACTIONS_MENU_SHOWDISABLED,
	DEBUGUI_EDITOR_ACTIONS_MENU_WAYPOINTS_INPUT,

	DEBUGUI_EDITOR_TRANSFORM,
	DEBUGUI_EDITOR_TRANSFORM_START,
	DEBUGUI_EDITOR_TRANSFORM_CONFIRM,
	DEBUGUI_EDITOR_TRANSFORM_CANCEL,
	DEBUGUI_EDITOR_TRANSFORM_VERTICAL_MODE,
	DEBUGUI_EDITOR_TRANSFORM_VERTICAL_SNAP,

	DEBUGUI_SAVING,
	DEBUGUI_SAVING_TYPE,
	DEBUGUI_SAVING_SAVE,
	DEBUGUI_SAVING_LOG,
	DEBUGUI_SAVING_LOAD_LATEST,	
	DEBUGUI_SAVING_RESTART_AND_LOAD_LATEST,
	DEBUGUI_SAVING_LOG_LATEST,
	DEBUGUI_SAVING_UPLOAD_LATEST,
	DEBUGUI_SAVING_DOWNLOAD,
	DEBUGUI_SAVING_DELETE,

	DEBUGUI_EDITOR_GUI,
	DEBUGUI_EDITOR_GUI_TOOLBAR_FILL,
	DEBUGUI_EDITOR_GUI_TOOLTIP_DEBUG,

	// Manual Camera
	DEBUGUI_MANUAL_CAMERA,
	DEBUGUI_MANUAL_CAMERA_DEBUG,
	DEBUGUI_MANUAL_CAMERA_UNLIMITED,
	DEBUGUI_MANUAL_CAMERA_SPEED_BOOST_UP,
	DEBUGUI_MANUAL_CAMERA_FREE,
	DEBUGUI_MANUAL_CAMERA_CONTROL_PLAYER,
	DEBUGUI_MANUAL_CAMERA_VIEW_LINK,

	// Scripted AI debug
	DEBUGUI_AI_SCRIPT,
	DEBUGUI_AI_SET_BT_BREAKPOINT,
	DEBUGUI_AI_PRINT_DEBUG,
	DEBUGUI_AI_PRINT_GROUP_INFO,
	DEBUGUI_AI_FIRETEAMS,
	DEBUGUI_AI_SUBGROUPS,
	DEBUGUI_AI_TARGET_CLUSTERS,
	DEBUGUI_AI_PRINT_ACTIVITY,
	DEBUGUI_AI_PRINT_SHOT_STATISTICS,
	DEBUGUI_AI_DEBUG_CATEGORY,
	DEBUGUI_AI_SHOW_DEBUG_SHAPES,
	DEBUGUI_AI_SHOW_FRIENDLY_IN_AIM,
	DEBUGUI_AI_SHOW_TARGET_LASTSEEN,
	DEBUGUI_AI_SHOW_GRENADE_POSITIONS,
	DEBUGUI_AI_SHOW_ILLUM_FLARES_POSITIONS,
	DEBUGUI_AI_SHOW_SUPPRESS_DEBUG,
	DEBUGUI_AI_SHOW_AIM_LEAD_DEBUG,
	DEBUGUI_AI_SHOW_SECTOR_THREAT_FILTER,
	DEBUGUI_AI_CONFIGURE_STATISTICSDEBUG,
	DEBUGUI_AI_SELECT_FIXED_AGENT,
	DEBUGUI_AI_DEBUG_COVERS,
	DEBUGUI_AI_COMMS_HANDLERS,
	DEBUGUI_AI_SEND_MESSAGE,
	DEBUGUI_AI_OPEN_DEBUG_PANEL,
	DEBUGUI_AI_SHOW_GRENADE_TRACE,
	DEBUGUI_AI_SHOW_TARGET_AIMPOINT,
	DEBUGUI_AI_SHOW_TARGET_PROJECTED_SIZE,
	DEBUGUI_AI_SHOW_PERCEPTION_PANEL,
	DEBUGUI_AI_SHOW_SEARCH_AND_DESTROY,
	DEBUGUI_AI_SHOW_COMMANDING_WAYPOINT_POSITIONS,

	// Campaign
	DEBUGUI_CAMPAIGN_MENU,
	DEBUGUI_CAMPAIGN_RANK_UP,
	DEBUGUI_CAMPAIGN_RANK_DOWN,
	DEBUGUI_CAMPAIGN_INSTANT_BUILDING,
	DEBUGUI_CAMPAIGN_MILITARY_SUPPLY_ALLOCATION,
	DEBUGUI_CAMPAIGN_MILITARY_SUPPLY_ALLOCATION_ENABLE,
	DEBUGUI_CAMPAIGN_MILITARY_SUPPLY_ALLOCATION_DEBUG,
	DEBUGUI_CAMPAIGN_SHOW_SUPPLIES_TRANSPORT_SYSTEM_DEBUG,
	DEBUGUI_CAMPAIGN_BECOME_COMMANDER_DEBUG,
	DEBUGUI_CAMPAIGN_VICTORY_BLUFOR,
	DEBUGUI_CAMPAIGN_VICTORY_OPFOR,

	// Tasks
	DEBUGUI_TASKS,
	DEBUGUI_TASKS_LIST,
	DEBUGUI_TASKS_CREATE,

	// General
	DEBUGUI_GAME_BOUNDS_OVERLAP_PREFAB,
	DEBUGUI_GAME_CURSOR_TARGET_PREFAB,
	DEBUGUI_GAME_COPY_ENF_VIEW_LINK,

	// Aim modifier
	DEBUGUI_AIMMODIFIER_MENU,

	DEBUGUI_AIMMODIFIER_LIN_X,
	DEBUGUI_AIMMODIFIER_LIN_Y,
	DEBUGUI_AIMMODIFIER_LIN_Z,
	DEBUGUI_AIMMODIFIER_ANG_X,
	DEBUGUI_AIMMODIFIER_ANG_Y,
	DEBUGUI_AIMMODIFIER_ANG_Z,
	DEBUGUI_AIMMODIFIER_TURN_X,
	DEBUGUI_AIMMODIFIER_TURN_Y,

	DEBUGUI_AIMMODIFIER_RESET,

	// UI
	DEBUGUI_UI_CLOSE_ALL_MENUS,
	DEBUGUI_UI_OPEN_MAIN_MENU,
	DEBUGUI_UI_LOG_UNDER_CURSOR,
	DEBUGUI_UI_SHOW_ALL_SETTINGS,
	DEBUGUI_UI_MAP_DEBUG_OPTIONS,

	//Particles
	DEBUGUI_PARTICLES_VEHICLE_DUST,
	DEBUGUI_PARTICLES_CONTACT_COMPONENT,

	// Vehicles
	DEBUGUI_VEHICLES_FUEL_CONSUMPTION,
	DEBUGUI_VEHICLES_UNFLIP,
	DEBUGUI_VEHICLES_COLLISIONS,

	// Weapons
	DEBUGUI_WEAPONS_MELEE_MENU,
	DEBUGUI_WEAPONS_MELEE_SHOW_EDITOR,
	DEBUGUI_WEAPONS_MELEE_ENABLE_GAME,
	DEBUGUI_WEAPONS_MELEE_SHOW_GAME,
	DEBUGUI_WEAPONS_OPTICS_USE_2D,
	DEBUGUI_WEAPONS_OPTICS,
	DEBUGUI_WEAPONS_PIP_SIGHTS,
	DEBUGUI_WEAPONS_ALLOW_INSPECTION_LOOKAT,
	DEBUGUI_WEAPONS_BLAST,

	DEBUGUI_HINT_IGNORE_SHOWN,

	//Tutorial
	DEBUGUI_TUTORIAL_MENU,
	DEBUGUI_TUTORIAL_CONFIG,
	DEBUGUI_TUTORIAL_STAGE,

	// Voting
	DEBUGUI_VOTING,
	DEBUGUI_VOTING_ENABLE_ALL,

	// Destruction
	DEBUGUI_DESTRUCTION,
	DEBUGUI_DESTRUCTION_ENABLE_DIAG,

	//Physics helper
	DEBUGUI_SCRIPTS_MENU,
	DEBUGUI_SHOW_PHYSICS_HELPER_TRACE,
	DEBUGUI_SHOW_INTERIOR_BOUNDING_BOX,

	//Data Collector
	DEBUGUI_DATA_COLLECTION,
	DEBUGUI_DATA_COLLECTION_ENABLE_DIAG,
	DEBUGUI_ANALYTICS_DATA_COLLECTION,
	DEBUGUI_ANALYTICS_DATA_COLLECTION_ENABLE_DIAG,
	
	//Groups
	DEBUGUI_GROUPS,
	DEBUGUI_GROUPS_ENABLE_DIAG,
	
	// Respawn
	DEBUGUI_RESPAWN_PLAYER_FACTION_DIAG,
	DEBUGUI_RESPAWN_PLAYER_LOADOUT_DIAG,
	DEBUGUI_RESPAWN_COMPONENT_DIAG,
	DEBUGUI_RESPAWN_COMPONENT_TIME,
	
	// Ambient life
	DEBUGUI_AMBIENT_LIFE,
	
	// Deployable Spawnpoints
	DEBUGUI_DEPLOYABLE_SPAWNPOINTS,
	DEBUGUI_DEPLOYABLE_SPAWNPOINTS_ENABLE_DIAG,
	
	//ScenarioFramework
	DEBUGUI_SCENARIO_FRAMEWORK_MENU,
	DEBUGUI_SCENARIO_FRAMEWORK_TASKS,
	DEBUGUI_SCENARIO_FRAMEWORK_REGISTERED_AREAS,
	DEBUGUI_SCENARIO_FRAMEWORK_DEBUG_AREAS,
	DEBUGUI_SCENARIO_FRAMEWORK_LAYER_INSPECTOR,
	DEBUGUI_SCENARIO_FRAMEWORK_ACTION_INSPECTOR,
	DEBUGUI_SCENARIO_FRAMEWORK_LOGIC_INSPECTOR,
	DEBUGUI_SCENARIO_FRAMEWORK_PLUGIN_INSPECTOR,
	DEBUGUI_SCENARIO_FRAMEWORK_CONDITION_INSPECTOR,
	DEBUGUI_SCENARIO_FRAMEWORK_DEBUG_ACTIONS,
	
	//NEW TUTORIAL
	DEBUGUI_NEWTUTORIAL_MENU,
	DEBUGUI_NEWTUTORIAL_DISABLE_COURSE_REQUIREMENTS,
	DEBUGUI_NEWTUTORIAL_REGENERATE_TASKS,
	DEBUGUI_NEWTUTORIAL_COURSE_LOCATIONS,
	DEBUGUI_NEWTUTORIAL_SKIP_INTRO,
	DEBUGUI_NEWTUTORIAL_SET_EVENING_TIME,
	DEBUGUI_NEWTUTORIAL_DUMP_STAGES_INTO_LOG,
	DEBUGUI_NEWTUTORIAL_FINISH_EVERYTHING,
	DEBUGUI_NEWTUTORIAL_DRAW_AREA_RESTRICTIONS,
	
	DEBUGUI_NEWTUTORIAL_COURSE_LOCATION_OBSTACLE,
	DEBUGUI_NEWTUTORIAL_COURSE_LOCATION_FIRING,
	DEBUGUI_NEWTUTORIAL_COURSE_LOCATION_ENGINEERING,
	DEBUGUI_NEWTUTORIAL_COURSE_LOCATION_SEIZING,
	DEBUGUI_NEWTUTORIAL_COURSE_LOCATION_AID,
	DEBUGUI_NEWTUTORIAL_COURSE_LOCATION_DRIVING,
	DEBUGUI_NEWTUTORIAL_COURSE_LOCATION_NAVIGATION,
	DEBUGUI_NEWTUTORIAL_COURSE_LOCATION_HELICOPTERS,
	DEBUGUI_NEWTUTORIAL_COURSE_LOCATION_SPECIAL,
	DEBUGUI_NEWTUTORIAL_COURSE_LOCATION_LONGRANGE,
	DEBUGUI_NEWTUTORIAL_COURSE_LOCATION_FIRESUPPORT,
	DEBUGUI_NEWTUTORIAL_COURSE_LOCATION_LEADERSHIP,
	DEBUGUI_NEWTUTORIAL_COURSE_LOCATION_MAINTENANCE,
	
	DEBUGUI_NEWTUTORIAL_COURSE_SKIP_AI_DRIVING,
	DEBUGUI_NEWTUTORIAL_COURSE_FINISH_STAGE,
	DEBUGUI_NEWTUTORIAL_COURSE_MOVE_TO_WP,
	
	DEBUGUI_SINGLEPLAYER,
	DEBUGUI_SINGLEPLAYER_DISABLE_GAMEOVER
};
