// Autogenerated by the Generate Class from Layout plugin v0.5.1
// Layout file: UI/layouts/Editor/Saving/Save.layout
class SCR_SaveWidgets
{
	protected static const ResourceName LAYOUT = "{681D3C8C634F895F}UI/layouts/Editor/Saving/Save.layout";

	SizeLayoutWidget m_wNewSave;
	SCR_ButtonComponent m_NewSaveComponent;


	ButtonWidget m_wSaveNameInput;
	SCR_EditBoxComponent m_SaveNameInputComponent0;
	SCR_ModularButtonComponent m_SaveNameInputComponent1;

	ScrollLayoutWidget m_wSaveScroller;
	VerticalLayoutWidget m_wSaveList;

	ButtonWidget m_wExitButton;
	SCR_InputButtonComponent m_ExitButtonComponent;

	ButtonWidget m_wDeleteButton;
	SCR_InputButtonComponent m_DeleteButtonComponent;

	ButtonWidget m_wConfirmButton;
	SCR_InputButtonComponent m_ConfirmButtonComponent;

	ButtonWidget m_wOverrideButton;
	SCR_InputButtonComponent m_OverrideButtonComponent;

	//------------------------------------------------------------------------------------------------
	bool Init(notnull Widget root)
	{
		m_wNewSave = SizeLayoutWidget.Cast(root.FindWidget("SaveHorizontalLayout.SaveWindow.WindowOverlay.WindowStructure.Saves.SaveEntryList.m_NewSave"));
		m_NewSaveComponent = SCR_ButtonComponent.Cast(m_wNewSave.FindHandler(SCR_ButtonComponent));


		m_wSaveNameInput = ButtonWidget.Cast(root.FindWidget("SaveHorizontalLayout.SaveWindow.WindowOverlay.WindowStructure.Saves.SaveEntryList.m_NewSave.m_SaveNameInput"));
		m_SaveNameInputComponent0 = SCR_EditBoxComponent.Cast(m_wSaveNameInput.FindHandler(SCR_EditBoxComponent));
		m_SaveNameInputComponent1 = SCR_ModularButtonComponent.Cast(m_wSaveNameInput.FindHandler(SCR_ModularButtonComponent));

		m_wSaveScroller = ScrollLayoutWidget.Cast(root.FindWidget("SaveHorizontalLayout.SaveWindow.WindowOverlay.WindowStructure.Saves.SaveEntryList.m_SaveScroller"));
		m_wSaveList = VerticalLayoutWidget.Cast(root.FindWidget("SaveHorizontalLayout.SaveWindow.WindowOverlay.WindowStructure.Saves.SaveEntryList.m_SaveScroller.m_SaveList"));

		m_wExitButton = ButtonWidget.Cast(root.FindWidget("SaveHorizontalLayout.SaveWindow.WindowOverlay.WindowStructure.FooterHorizontal.m_ExitButton"));
		m_ExitButtonComponent = SCR_InputButtonComponent.Cast(m_wExitButton.FindHandler(SCR_InputButtonComponent));

		m_wDeleteButton = ButtonWidget.Cast(root.FindWidget("SaveHorizontalLayout.SaveWindow.WindowOverlay.WindowStructure.FooterHorizontal.m_DeleteButton"));
		m_DeleteButtonComponent = SCR_InputButtonComponent.Cast(m_wDeleteButton.FindHandler(SCR_InputButtonComponent));

		m_wConfirmButton = ButtonWidget.Cast(root.FindWidget("SaveHorizontalLayout.SaveWindow.WindowOverlay.WindowStructure.FooterHorizontal.m_ConfirmButton"));
		m_ConfirmButtonComponent = SCR_InputButtonComponent.Cast(m_wConfirmButton.FindHandler(SCR_InputButtonComponent));

		m_wOverrideButton = ButtonWidget.Cast(root.FindWidget("SaveHorizontalLayout.SaveWindow.WindowOverlay.WindowStructure.FooterHorizontal.m_OverrideButton"));
		m_OverrideButtonComponent = SCR_InputButtonComponent.Cast(m_wOverrideButton.FindHandler(SCR_InputButtonComponent));

		return true;
	}

	//------------------------------------------------------------------------------------------------
	ResourceName GetLayout()
	{
		return LAYOUT;
	}
}
