// Autogenerated by the Generate Class from Layout plugin v0.5.1
// Layout file: UI/layouts/Editor/Saving/Save_Entry.layout
class SCR_Save_EntryWidgets
{
	protected static const ResourceName LAYOUT = "{03826F525D905105}UI/layouts/Editor/Saving/Save_Entry.layout";

	ImageWidget m_wSaveImage;
	RichTextWidget m_wEntryName;

	ButtonWidget m_wLoadButton;
	SCR_ModularButtonComponent m_LoadButtonComponent0;
	SCR_DynamicIconComponent m_LoadButtonComponent1;


	ButtonWidget m_wSaveButton;
	SCR_ModularButtonComponent m_SaveButtonComponent0;
	SCR_DynamicIconComponent m_SaveButtonComponent1;


	ButtonWidget m_wDeleteButton;
	SCR_ModularButtonComponent m_DeleteButtonComponent0;
	SCR_DynamicIconComponent m_DeleteButtonComponent1;

	TextWidget m_wEntryVersion;
	TextWidget m_wPreviewDate;
	TextWidget m_wPreviewTime;
	HorizontalLayoutWidget m_wScenarioInfoList;
	ImageWidget m_wScenarioImage;
	TextWidget m_wPreviewWorld;

	//------------------------------------------------------------------------------------------------
	bool Init(notnull Widget root)
	{
		m_wSaveImage = ImageWidget.Cast(root.FindWidget("Save_EntrySize.SaveOverlay.SaveContent.SaveStructure.SaveImageSize.m_SaveImage"));
		m_wEntryName = RichTextWidget.Cast(root.FindWidget("Save_EntrySize.SaveOverlay.SaveContent.SaveStructure.SaveTitleLine.m_EntryName"));

		m_wLoadButton = ButtonWidget.Cast(root.FindWidget("Save_EntrySize.SaveOverlay.SaveContent.SaveStructure.SaveTitleLine.m_LoadButton"));
		m_LoadButtonComponent0 = SCR_ModularButtonComponent.Cast(m_wLoadButton.FindHandler(SCR_ModularButtonComponent));
		m_LoadButtonComponent1 = SCR_DynamicIconComponent.Cast(m_wLoadButton.FindHandler(SCR_DynamicIconComponent));


		m_wSaveButton = ButtonWidget.Cast(root.FindWidget("Save_EntrySize.SaveOverlay.SaveContent.SaveStructure.SaveTitleLine.m_SaveButton"));
		m_SaveButtonComponent0 = SCR_ModularButtonComponent.Cast(m_wSaveButton.FindHandler(SCR_ModularButtonComponent));
		m_SaveButtonComponent1 = SCR_DynamicIconComponent.Cast(m_wSaveButton.FindHandler(SCR_DynamicIconComponent));


		m_wDeleteButton = ButtonWidget.Cast(root.FindWidget("Save_EntrySize.SaveOverlay.SaveContent.SaveStructure.SaveTitleLine.m_DeleteButton"));
		m_DeleteButtonComponent0 = SCR_ModularButtonComponent.Cast(m_wDeleteButton.FindHandler(SCR_ModularButtonComponent));
		m_DeleteButtonComponent1 = SCR_DynamicIconComponent.Cast(m_wDeleteButton.FindHandler(SCR_DynamicIconComponent));

		m_wEntryVersion = TextWidget.Cast(root.FindWidget("Save_EntrySize.SaveOverlay.SaveContent.SaveStructure.SaveTitleLine.SaveMetaLine.m_EntryVersion"));
		m_wPreviewDate = TextWidget.Cast(root.FindWidget("Save_EntrySize.SaveOverlay.SaveContent.SaveStructure.SaveTitleLine.SaveMetaLine.m_PreviewDate"));
		m_wPreviewTime = TextWidget.Cast(root.FindWidget("Save_EntrySize.SaveOverlay.SaveContent.SaveStructure.SaveTitleLine.SaveMetaLine.m_PreviewTime"));
		m_wScenarioInfoList = HorizontalLayoutWidget.Cast(root.FindWidget("Save_EntrySize.SaveOverlay.SaveContent.SaveStructure.SaveTitleLine.SaveMetaLine.m_ScenarioInfoList"));
		m_wScenarioImage = ImageWidget.Cast(root.FindWidget("Save_EntrySize.SaveOverlay.SaveContent.SaveStructure.SaveTitleLine.SaveMetaLine.m_ScenarioInfoList.EntryScenarioIconSizer.m_ScenarioImage"));
		m_wPreviewWorld = TextWidget.Cast(root.FindWidget("Save_EntrySize.SaveOverlay.SaveContent.SaveStructure.SaveTitleLine.SaveMetaLine.m_ScenarioInfoList.m_PreviewWorld"));

		return true;
	}

	//------------------------------------------------------------------------------------------------
	ResourceName GetLayout()
	{
		return LAYOUT;
	}
}
