// Autogenerated by the Generate Class from Layout plugin, version 0.3.0
// Layout file: UI/layouts/Menus/ContentBrowser/DownloadManager/DownloadManagerEntry.layout

class SCR_DownloadManagerEntryWidgets
{
	static const ResourceName s_sLayout = "{FB196DBC0ABA6AE4}UI/layouts/Menus/ContentBrowser/DownloadManager/DownloadManagerEntry.layout";
	ResourceName GetLayout() { return s_sLayout; }

	ImageWidget m_AddonImg;

	TextWidget m_NameText;

	HorizontalLayoutWidget m_HorizontalButtons;

	ButtonWidget m_RetryBtn;
	SCR_ModularButtonComponent m_RetryBtnComponent;

	ButtonWidget m_CancelBtn;
	SCR_ModularButtonComponent m_CancelBtnComponent;

	ButtonWidget m_PauseBtn;
	SCR_ModularButtonComponent m_PauseBtnComponent;

	ButtonWidget m_ResumeBtn;
	SCR_ModularButtonComponent m_ResumeBtnComponent;

	ImageWidget m_DownloadIcon;

	ImageWidget m_DownloadIconShadow;
	
	ImageWidget m_ProcessingSpinner;

	TextWidget m_DownloadStateText;

	TextWidget m_DownloadedText;

	TextWidget m_VersionText;

	SizeLayoutWidget m_Progress;
	SCR_WLibProgressBarComponent m_ProgressComponent;

	bool Init(Widget root)
	{
		m_AddonImg = ImageWidget.Cast(root.FindWidget("SizeLayout.Overlay.HorizontalLayout.SizeImg.ScaleImg.m_AddonImg"));

		m_NameText = TextWidget.Cast(root.FindWidget("SizeLayout.Overlay.HorizontalLayout.VerticalLayout.HorizontalLayout.m_NameText"));

		m_HorizontalButtons = HorizontalLayoutWidget.Cast(root.FindWidget("SizeLayout.Overlay.HorizontalLayout.VerticalLayout.HorizontalLayout.SizeLayout0.m_HorizontalButtons"));

		m_RetryBtn = ButtonWidget.Cast(root.FindWidget("SizeLayout.Overlay.HorizontalLayout.VerticalLayout.HorizontalLayout.SizeLayout0.m_HorizontalButtons.m_RetryBtn"));
		m_RetryBtnComponent = SCR_ModularButtonComponent.Cast(m_RetryBtn.FindHandler(SCR_ModularButtonComponent));

		m_CancelBtn = ButtonWidget.Cast(root.FindWidget("SizeLayout.Overlay.HorizontalLayout.VerticalLayout.HorizontalLayout.SizeLayout0.m_HorizontalButtons.m_CancelBtn"));
		m_CancelBtnComponent = SCR_ModularButtonComponent.Cast(m_CancelBtn.FindHandler(SCR_ModularButtonComponent));

		m_PauseBtn = ButtonWidget.Cast(root.FindWidget("SizeLayout.Overlay.HorizontalLayout.VerticalLayout.HorizontalLayout.SizeLayout0.m_HorizontalButtons.m_PauseBtn"));
		m_PauseBtnComponent = SCR_ModularButtonComponent.Cast(m_PauseBtn.FindHandler(SCR_ModularButtonComponent));

		m_ResumeBtn = ButtonWidget.Cast(root.FindWidget("SizeLayout.Overlay.HorizontalLayout.VerticalLayout.HorizontalLayout.SizeLayout0.m_HorizontalButtons.m_ResumeBtn"));
		m_ResumeBtnComponent = SCR_ModularButtonComponent.Cast(m_ResumeBtn.FindHandler(SCR_ModularButtonComponent));

		m_DownloadIcon = ImageWidget.Cast(root.FindWidget("SizeLayout.Overlay.HorizontalLayout.VerticalLayout.HorizontalDownload.DownloadIconOverlay.m_DownloadIcon"));

		m_DownloadIconShadow = ImageWidget.Cast(root.FindWidget("SizeLayout.Overlay.HorizontalLayout.VerticalLayout.HorizontalDownload.DownloadIconOverlay.m_DownloadIconShadow"));

		m_ProcessingSpinner = ImageWidget.Cast(root.FindWidget("SizeLayout.Overlay.HorizontalLayout.VerticalLayout.HorizontalDownload.DownloadIconOverlay.m_ProcessingSpinner"));
		
		m_DownloadStateText = TextWidget.Cast(root.FindWidget("SizeLayout.Overlay.HorizontalLayout.VerticalLayout.HorizontalDownload.m_DownloadStateText"));

		m_DownloadedText = TextWidget.Cast(root.FindWidget("SizeLayout.Overlay.HorizontalLayout.VerticalLayout.HorizontalDownload.m_DownloadedText"));

		m_VersionText = TextWidget.Cast(root.FindWidget("SizeLayout.Overlay.HorizontalLayout.VerticalLayout.HorizontalDownload.SizeVersion.m_VersionText"));

		m_Progress = SizeLayoutWidget.Cast(root.FindWidget("SizeLayout.Overlay.HorizontalLayout.VerticalLayout.m_Progress"));
		m_ProgressComponent = SCR_WLibProgressBarComponent.Cast(m_Progress.FindHandler(SCR_WLibProgressBarComponent));

		return true;
	}
}
