// Autogenerated by the Generate Class from Layout plugin, version 0.3.0
// Layout file: UI/layouts/Menus/ContentBrowser/DownloadManager/DownloadManagerTabActive.layout

class SCR_DownloadManagerTabActiveWidgets
{
	static const ResourceName s_sLayout = "{A41D88CE1A3F1D92}UI/layouts/Menus/ContentBrowser/DownloadManager/DownloadManagerTabActive.layout";
	ResourceName GetLayout() { return s_sLayout; }

	ButtonWidget m_AutoenableAddonsButton;
	SCR_ModularButtonComponent m_AutoenableAddonsButtonComponent;

	VerticalLayoutWidget m_RecentFailedList;

	VerticalLayoutWidget m_RecentDownloadedList;

	VerticalLayoutWidget m_DownloadingList;

	bool Init(Widget root)
	{
		m_AutoenableAddonsButton = ButtonWidget.Cast(root.FindWidget("m_AutoenableAddonsButton"));
		m_AutoenableAddonsButtonComponent = SCR_ModularButtonComponent.Cast(m_AutoenableAddonsButton.FindHandler(SCR_ModularButtonComponent));

		m_RecentFailedList = VerticalLayoutWidget.Cast(root.FindWidget("ScrollSize.ScrollLayout.VerticalListWrap.m_RecentFailedList"));

		m_RecentDownloadedList = VerticalLayoutWidget.Cast(root.FindWidget("ScrollSize.ScrollLayout.VerticalListWrap.m_RecentDownloadedList"));

		m_DownloadingList = VerticalLayoutWidget.Cast(root.FindWidget("ScrollSize.ScrollLayout.VerticalListWrap.m_DownloadingList"));

		return true;
	}
}
