// Autogenerated by the Generate Class from Layout plugin, version 0.3.0
// Layout file: UI/layouts/Menus/ContentBrowser/AddonManager/AddonsTools/AddonsPresets/AddonLinePreset.layout

class SCR_AddonLinePresetWidgets
{
	static const ResourceName s_sLayout = "{35576491614D20E5}UI/layouts/Menus/ContentBrowser/AddonManager/AddonsTools/AddonsPresets/AddonLinePreset.layout";
	ResourceName GetLayout() { return s_sLayout; }

	ImageWidget m_LineBackground;

	TextWidget m_TxtAddonsCount;

	ButtonWidget m_EditName;
	SCR_EditBoxComponent m_EditNameComponent;

	TextWidget m_NameText;
	
	ButtonWidget m_wSelectedHighlight;
	SCR_ModularButtonComponent m_SelectedHighlightButtonComponent;

	ImageWidget m_SizeWarning;

	ButtonWidget m_EditNameButton;
	SCR_ModularButtonComponent m_EditNameButtonComponent;

	ButtonWidget m_DeleteButton;
	SCR_ModularButtonComponent m_DeleteButtonComponent;

	ButtonWidget m_OverrideButton;
	SCR_ModularButtonComponent m_OverrideButtonComponent;

	ButtonWidget m_LoadButton;
	SCR_ModularButtonComponent m_LoadButtonComponent;
	
	ImageWidget m_wImgAddons;

	bool Init(Widget root)
	{
		m_LineBackground = ImageWidget.Cast(root.FindWidget("LineHeight.Overlay.LineContent.m_LineBackground"));

		m_TxtAddonsCount = TextWidget.Cast(root.FindWidget("LineHeight.Overlay.LineContent.LineElements.SizeAddons.HorizontalAddons.m_TxtAddonsCount"));

		m_EditName = ButtonWidget.Cast(root.FindWidget("LineHeight.Overlay.LineContent.LineElements.OverlayName.m_EditName"));
		m_EditNameComponent = SCR_EditBoxComponent.Cast(m_EditName.FindHandler(SCR_EditBoxComponent));

		m_NameText = TextWidget.Cast(root.FindWidget("LineHeight.Overlay.LineContent.LineElements.OverlayName.HorizontalName.m_NameText"));
		
		m_wSelectedHighlight = ButtonWidget.Cast(root.FindWidget("LineHeight.Overlay.LineContent.LineElements.OverlayName.HorizontalName.m_SelectedHighlight"));
		m_SelectedHighlightButtonComponent = SCR_ModularButtonComponent.Cast(m_wSelectedHighlight.FindHandler(SCR_ModularButtonComponent));

		m_SizeWarning = ImageWidget.Cast(root.FindWidget("LineHeight.Overlay.LineContent.LineElements.m_SizeWarning.ImgWarning"));

		m_EditNameButton = ButtonWidget.Cast(root.FindWidget("LineHeight.Overlay.LineContent.LineElements.m_EditNameButton"));
		m_EditNameButtonComponent = SCR_ModularButtonComponent.Cast(m_EditNameButton.FindHandler(SCR_ModularButtonComponent));

		m_DeleteButton = ButtonWidget.Cast(root.FindWidget("LineHeight.Overlay.LineContent.LineElements.m_DeleteButton"));
		m_DeleteButtonComponent = SCR_ModularButtonComponent.Cast(m_DeleteButton.FindHandler(SCR_ModularButtonComponent));

		m_OverrideButton = ButtonWidget.Cast(root.FindWidget("LineHeight.Overlay.LineContent.LineElements.m_OverrideButton"));
		m_OverrideButtonComponent = SCR_ModularButtonComponent.Cast(m_OverrideButton.FindHandler(SCR_ModularButtonComponent));

		m_LoadButton = ButtonWidget.Cast(root.FindWidget("LineHeight.Overlay.LineContent.LineElements.m_LoadButton"));
		m_LoadButtonComponent = SCR_ModularButtonComponent.Cast(m_LoadButton.FindHandler(SCR_ModularButtonComponent));
		
		m_wImgAddons = ImageWidget.Cast(root.FindWidget("LineHeight.Overlay.LineContent.LineElements.SizeAddons.HorizontalAddons.m_ImgAddons"));;

		return true;
	}
}
