enum ESoundName
{
	// Conifer 0
	BIRD_CONIFER_CLOSE_JAY1 = 0,
	BIRD_CONIFER2_CLOSE_UNKNOWN8,
	BIRD_CONIFER_CLOSE_TOWHEE2,
	BIRD_CONIFER_CLOSE_TOWHEE3,
	BIRD_CONIFER_CLOSE_UNKNOWN1,
	BIRD_CONIFER2_CLOSE_GSWOODPACKER,
	BIRD_CONIFER2_CLOSE_UNKNOWN6,
	BIRD_CONIFER2_CLOSE_UNKNOWN9,
	BIRD_CONIFER2_CLOSE_UNKNOWN10,
	BIRD_CONIFER2_CLOSE_UNKNOWN11,
	BIRD_CONIFER2_CLOSE_UNKNOWN12 = 10,
	BIRD_CONIFER2_CLOSE_UNKNOWN13,
	BIRD_CONIFER2_CLOSE_UNKNOWN14,
	BIRD_CONIFER2_CLOSE_UNKNOWN15,
	BIRD_CONIFER_CLOSE_COMMONRAVEN,
	BIRD_CONIFER_CLOSE_UNKNOWN16,
	BIRD_CONIFER_CLOSE_UNKNOWN17,
	BIRD_CONIFER_CLOSE_UNKNOWN19,
	BIRD_CONIFER_CLOSE_UNKNOWN21,
	BIRD_CONIFER_CLOSE_UNKNOWN23,
	
	// Conifer MID
	BIRD_CONIFER_BTIT4 = 29,
	BIRD_CONIFER_MID_CROW = 30,
	BIRD_CONIFER_MID_JAY2,
	BIRD_CONIFER_MID_RAVEN1,
	BIRD_CONIFER2_MID_TIT1,
	BIRD_CONIFER2_MID_UNKNOWN1,
	BIRD_CONIFER2_MID_UNKNOWN6,
	BIRD_CONIFER2_MID_UNKNOWN7,
	BIRD_CONIFER_MID_COMMONRAVEN_CLICKING,
	BIRD_CONIFER_MID_GREASPOTTEDWOODPECKER,
	BIRD_CONIFER_MID_UNKNOWN18,
	BIRD_CONIFER_MID_UNKNOWN22 = 40,
	BIRD_CONIFER_MID_UNKNOWN25,
	BIRD_CONIFER_MID_UNKNOWN27,
	BIRD_CONIFER_MID_UNKNOWN30,
	BIRD_CONIFER_MID_MORNING_UNKNOWN1,
	BIRD_CONIFER_MID_MORNING_UNKNOWN2,
	BIRD_CONIFER_MID_MORNING_UNKNOWN3,
	BIRD_CONIFER_MID_MORNING_UNKNOWN4,
	BIRD_CONIFER_MID_ROBIN4,
	BIRD_CONIFER_MID_EUROASIAN_JAY,
	SQUIRREL_CONIFER_MID_1 = 50,
	SQUIRREL_CONIFER_MID_2,
	BIRD_CONIFER_MID_GREAT_TIT5,
	BIRD_CONIFER_MID_GREAT_TIT6,
	BIRD_CONIFER_MID_GREAT_TIT7,
	BIRD_CONIFER_MID_CROW2 = 55,
	BIRD_CONIFER_MID_RAVEN3,
	BIRD_CONIFER_MID_RAVEN4,
	BIRD_CONIFER_MID_BTIT3,
	BIRD_CONIFER_MID_BTIT4,
	
	// Conifer DIST
	BIRD_CONIFER_DIST_RAVEN1 = 60,
	BIRD_CONIFER_DIST_RAVEN2,
	BIRD_CONIFER_DIST_THRUSH,
	BIRD_CONIFER_DIST_UNKNOWN1,
	BIRD_CONIFER2_DIST_TIT1,
	BIRD_CONIFER2_DIST_UNKNOWN5,
	BIRD_CONIFER2_DIST_UNKNOWN6,
	BIRD_CONIFER2_DIST_WOODPECKER,
	BIRD_CONIFER_DIST_COMMONRAVEN,
	BIRD_CONIFER_DIST_COMMONRAVEN_DEEPNOISE,
	BIRD_CONIFER_DIST_EURASIANOYSTERCATCHER = 70,
	BIRD_CONIFER_DIST_GREASPOTTEDWOODPECKER_DRUMMING1,
	BIRD_CONIFER_DIST_GREASPOTTEDWOODPECKER_DRUMMING2,
	BIRD_CONIFER_DIST_UNKNOWN20,
	BIRD_CONIFER_DIST_UNKNOWN24,
	BIRD_CONIFER_DIST_UNKNOWN32,
	BIRD_CONIFER_DIST_UNKNOWN33,
	BIRD_CONIFER_DIST_WHITEBACKEDWOODPECKER,
	BIRD_CONIFER_DIST_WOODPECKERCALL,
	
	// Night Close 80
	// Night Mid 85
	BIRD_CONIFER_MID_OWL3 = 85,
	BIRD_CONIFER_MID_MAGPIE,
	BIRD_CONIFER_MID_OWLSHRIEK4,
	
	// Night Dist 90
	BIRD_CONIFER_DIST_OWL1 = 90,
	BIRD_CONIFER_DIST_OWL2,
	BIRD_CONIFER_DIST_SCOPSOWL1,
	BIRD_CONIFER_DIST_SCOPSOWL2,
	BIRD_CONIFER_DIST_OWLSHRIEK1,
	BIRD_CONIFER_DIST_OWLSHRIEK2,
	BIRD_CONIFER_DIST_OWLSHRIEK3,
	BIRD_CONIFER_DIST_TAWNYOWL1,
	BIRD_CONIFER_DIST_TAWNYOWL2,
	
	// Leafy 100
	BIRD_LEAFY_CLOSE_GROSBEAK = 100,
	BIRD_LEAFY_CLOSE_QUAIL,
	BIRD_LEAFY_CLOSE_SPARROW,
	BIRD_LEAFY_CLOSE_WARBLER1,
	BIRD_LEAFY_CLOSE_WARBLER2,
	BIRD_LEAFY_CLOSE_TIT1,
	BIRD_LEAFY_CLOSE_UNKNOWN1,
	BIRD_LEAFY_CLOSE_UNKNOWN8,
	BIRD_LEAFY_CLOSE_MAGPIE,
	BIRD_LEAFY_CLOSE_UNKNOWN26,
	BIRD_LEAFY_CLOSE_UNKNOWN28,
	BIRD_LEAFY_CLOSE_UNKNOWN31,
	BIRD_LEAFY_MID_UNKNOWN2 = 130,
	BIRD_LEAFY_MID_UNKNOWN5,
	BIRD_LEAFY_MID_UNKNOWN6,
	BIRD_LEAFY_MID_UNKNOWN7,
	BIRD_LEAFY_MID_YELLOWHAMMER,
	BIRD_LEAFY_DIST_UNKNOWN3 = 160,
	BIRD_LEAFY_DIST_UNKNOWN4,
	BIRD_LEAFY_DIST_UNKNOWN7,
	BIRD_LEAFY_DIST_UNKNOWN8,
	BIRD_LEAFY_DIST_WOODPACKER_DRUMMING1,
	BIRD_LEAFY_DIST_WOODPACKER_DRUMMING2,	
	// Night Close 180
	// Night Mid 185
	BIRD_LEAFY_MID_NIGHTINGALE1 = 185,
	BIRD_LEAFY_MID_NIGHTINGALE2,
	// Night Dist 190
	BIRD_LEAFY_MID_NIGHTINGALE3,
	BIRD_LEAFY_DIST_NIGHTINGALE4 = 190,
	BIRD_LEAFY_DIST_NIGHTINGALE5,
	
	
	// Houses
	BIRD_HOUSES_DIST_SWALLOW = 200,
	
	// Insect
	INSECT_INSECT = 300,
	INSECT_GRASSHOPPER,
	INSECT_CICADAS,
	INSECT_CONIFER_HARSH1,
	INSECT_CONIFER_HARSH2,
	INSECT_CONIFER_CRICKET1,
	INSECT_CONIFER_CRICKET2,
	INSECT_CONIFER_HIGH1,
	INSECT_CONIFER_HIGH2,
	INSECT_CORNFIELD_UNKNOWN1,
	INSECT_MEADOW2_CRICKET1,
	INSECT_MEADOW2_DISTANT_CRICKET1,
	INSECT_MEADOW2_CICADAS1,
	INSECT_MEADOW_DISTANT_CRICKET1,
	INSECT_MEADOW_DISTANT_KATYDID1,
	INSECT_MEADOW_GRASSHOPPER2,
	INSECT_MEADOW_FLY,
	// Details
	DETAIL_CONIFER = 400,
	//DELETE
	DETAIL_TREECREAK,
	DETAIL_TREECREAKSMALL,
	DETAIL_FALLINGLEAVES = 430,
	DETAIL_TREECREAKDISTANT = 460,
	//
	DETAIL_HOUSES_DECAY_MIXED_IMPACS = 470,
	DETAIL_HOUSES_DOORRATTLE,
	DETAIL_HOUSES_FLAGPOLETAPPING,
	DETAIL_HOUSES_HEAVYMETALCLANK,		// OBSOLETE - UNUSED
	DETAIL_HOUSES_METALCREAK,			// OBSOLETE - UNUSED
	DETAIL_HOUSES_METALFENCERATTLE,
	DETAIL_HOUSES_METALFENCERATTLE2,	// OBSOLETE - UNUSED
	DETAIL_HOUSES_METALHOLLOWRATTLE,
	DETAIL_HOUSES_WINDOWRATTLE,
	DETAIL_HOUSES_WIREFENCERATLLE,
	DETAIL_HOUSES_DECAY_ALL = 480,
	
	// --- OCEAN ---
	// Close 500
	// Mid 530
	BIRD_OCEAN_MID_SEAGULL1 = 530,
	BIRD_OCEAN_MID_SEAGULL2,
	// Dist 560
	BIRD_OCEAN_DIST_SEAGULL1 = 560,
	BIRD_OCEAN_DIST_BLACKHEADEDGULL,
	BIRD_OCEAN_DIST_HERRING_GULL,
	BIRD_OCEAN_DIST_SEAGULL_2,
	
	// Grass Short Insect 600
	// 600 PL Morning
	// 610 PL Noon
	INSECT_GRASSSHORT_NOON_CICADAS = 610,
	// 620 PL Evening
	INSECT_GRASSSHORT_EVENING_CICADAS = 620,
	// 630 PL Night
	INSECT_GRASSSHORT_NIGHT_CRICKET = 630,
	// 640 SL Morning
	// 650 SL Noon
	INSECT_GRASSSHORT_NOON_SL_CRICKET = 650,
	// 660 SL Evening
	INSECT_GRASSSHORT_EVENING_SL_CRICKET1 = 660,
	INSECT_GRASSSHORT_EVENING_SL_CRICKET2,
	INSECT_GRASSSHORT_EVENING_SL_KATYDID,
	// 670 SL Night
	INSECT_GRASSSHORT_NIGHT_SL_CRICKET = 670,
	INSECT_GRASSSHORT_NIGHT_SL_MARSHCRICKET,
	// 680 Misc
		
	// Grass Tall Insect 700
	//700
	
	//710
	INSECT_GRASSTTALL_NOON_GRASSHOPPER = 710,
	//720
	INSECT_GRASSTTALL_EVENING = 720,
	//730
	INSECT_GRASSTTALL_NIGHT_CRICKET = 730,
	INSECT_GRASSTTALL_NIGHT_KATYDID,
	//740 SL Morning
	
	//750 SL Noon
	INSECT_GRASSTTALL_NOON_SL_GRASSHOPPER = 750,
	INSECT_GRASSTTALL_NOON_SL_GRASSHOPPER_SHORT,
	//760 SL Evening
	INSECT_GRASSTTALL_EVENING_SL_GRASSHOPPER = 760,
	//770 SL Night
	INSECT_GRASSTTALL_NIGHT_SL_CRICKET = 770,
	//780 Misc
	INSECT_GRASSTTALL_GRASSHOPPER_WINGS = 780,
	INSECT_GRASSTTALL_FLY,
	
	// Conifer Insect 800
	// Morning SL 840
	INSECT_CONIFER_MORNING_SL_HARSH1 = 840,
	INSECT_CONIFER_MORNING_SL_HARSH2,
	// Noon SL 850
	INSECT_CONIFER_NOON_SL_HIGH1 = 850,
	INSECT_CONIFER_NOON_SL_HIGH2,
	// Evening SL 860
	INSECT_CONIFER_EVENING_SL_CRICKET = 860,
	INSECT_CONIFER_EVENING_SL_CRICKETLONG,
	// Night SL 870
	INSECT_CONIFER_NIGHT_SL_CRICKET = 870,
	INSECT_CONIFER_NIGHT_SL_FROG1,
	INSECT_CONIFER_NIGHT_SL_FROG2,
	// Misc 880
	INSECT_CONIFER_MOSQUITO = 880,
	
	// Leafy Insect 900
	// Morning SL 940
	INSECT_LEAFY_MORNING_SL_CRICKET = 940,
	// Noon SL 950
	INSECT_LEAFY_NOON_SL_CRICKET = 950,
	INSECT_LEAFY_NOON_SL_HEIGH,
	// Evening SL 960
	INSECT_LEAFY_EVENING_SL_CRICKET1 = 960,
	INSECT_LEAFY_EVENING_SL_CRICKET2,
	// Night SL 970
	INSECT_LEAFY_NIGHT_SL_CRICKET1 = 970,
	INSECT_LEAFY_NIGHT_SL_CRICKET2,
	INSECT_LEAFY_NIGHT_SL_CRICKET3,
	INSECT_LEAFY_NIGHT_SL_CRICKET4,
	
	// --- CROPFIELD --- 
	// Close 1000
	INSECT_CROPFIELD_DAY_CICADAS = 1000,
	// Mid 1030
	WIND_CROPFIELD = 1030,
	// Dist 1060
		
	// --- POND ---
	// Close 1100
	// Mid 1130
	FROG_POND_MID_EDIBLEFROG1 = 1130,
	FROG_POND_MID_EDIBLEFROG2,
	FROG_POND_MID_EDIBLEFROG3,
	FROG_POND_MID_EDIBLEFROG4,
	// Dist 1160
	BIRD_POND_DIST_DUCK = 1160,
	BIRD_POND_DIST_DUCKAGITATED,
	BIRD_POND_DIST_DUCKS,
	BIRD_POND_DIST_EURASIANCOOT,
	BIRD_POND_DIST_GHOOSE1,
	BIRD_POND_DIST_GHOOSE2,
	BIRD_POND_DIST_GRATERGOOSE,
	BIRD_POND_DIST_GREYLAGGOOSE,
	
	// --- CONCRETE ---
	// Close 1200
	// Mid 1230
	WIND_CONCRETE = 1230,
	// Dist 1260

	// --- MEADOW ---
	// Close 1300
	// Mid 1330
	BIRD_MEADOW_MID_SNOW_BUNTING = 1330,
	BIRD_MEADOW_MID_CHIPPING_SPARROW,
	BIRD_MEADOW_MID_FOX_SPARROW,
	BIRD_MEADOW_MID_HOUSE_SPARROW,
	BIRD_MEADOW_MID_CORN_CRAKE,
	BIRD_MEADOW_MID_TREE_PIPIT,
	// Dist 1360
	BIRD_MEADOW_DIST_COMMONBUZZARD = 1360,
	BIRD_MEADOW_DIST_COMMONBUZZARD2 = 1361,
	
	// --- ROCKS ---
	// Close 1400
	// Mid 1430
	// Dist 1460
	ROCKS_SLIDE = 1430,
	
	// --- RUSTLE ---
	BUSH_LEAVES_RUSTLE = 1500,
	TREE_CREAK_LOW = 1600,
	TREE_CREAK_HIGH,
}

[BaseContainerProps()]
class SCR_SoundDef
{
	[Attribute("0", UIWidgets.ComboBox, "", "", ParamEnumArray.FromEnum(ESoundName))]
	ESoundName m_eSoundName;
	
	[Attribute("0", UIWidgets.Slider, "[ms]", "-100000 100000 1")]
	int m_iCoolDown;
	
	[Attribute("500", UIWidgets.Slider, "[ms]", "100 10000 1")]
	int m_iSampleLength;
	
	[Attribute("0", UIWidgets.EditBox, "[ms], adds sequence lenght to cool down time", "")]
	bool m_bAddSequenceLength;
		
	[Attribute("5000", UIWidgets.Slider, "[ms]", "0 30000 1")]
	int m_iStartDelay;
	
	[Attribute("5000", UIWidgets.Slider, "[ms]", "0 30000 1")]
	int m_iStartDelayRnd;
	
	[Attribute("", UIWidgets.Object)]
	ref array<ref SCR_SequenceDef> m_aSequenceDef;
		
	[Attribute("1", UIWidgets.ComboBox, "", "", ParamEnumArray.FromEnum(EDayTimeCurve))]
	EDayTimeCurve m_eDayTimeCurve;
	
	float m_fCoolDownEnd;
	
#ifdef ENABLE_DIAG
	int m_iCount;	
#endif
}
