// Autogenerated by the Generate Class from Layout plugin v0.5.1
// Layout file: UI/layouts/Menus/DeployMenu/JournalButton.layout
class SCR_JournalButtonWidgets
{
	protected static const ResourceName LAYOUT = "{3EAF5389D3D89EE5}UI/layouts/Menus/DeployMenu/JournalButton.layout";

	ButtonWidget m_wButton;
	SCR_ModularButtonComponent m_ButtonComponent0;
	SCR_MapJournalUIButton m_ButtonComponent1;

	Widget m_wContent;

	//------------------------------------------------------------------------------------------------
	bool Init(notnull Widget root)
	{
		m_wButton = ButtonWidget.Cast(root);
		m_ButtonComponent0 = SCR_ModularButtonComponent.Cast(m_wButton.FindHandler(SCR_ModularButtonComponent));
		m_ButtonComponent1 = SCR_MapJournalUIButton.Cast(m_wButton.FindHandler(SCR_MapJournalUIButton));

		m_wContent = root.FindWidget("SizeLayout.Overlay.m_wContent");

		return true;
	}

	//------------------------------------------------------------------------------------------------
	ResourceName GetLayout()
	{
		return LAYOUT;
	}
}
