// Autogenerated by the Generate Class from Layout plugin v0.5.1
// Layout file: UI/layouts/HUD/CompositionInfo/CompositionInfo.layout
class SCR_CompositionInfoWidgets
{
	protected static const ResourceName LAYOUT = "{DB7AE399AA22C2E2}UI/layouts/HUD/CompositionInfo/CompositionInfo.layout";

	ImageWidget m_wEntityPivot;
	VerticalLayoutWidget m_wAuthorDetails;
	ImageWidget m_wAuthorPlatformIcon;
	TextWidget m_wAuthorName;
	TextWidget m_wAuthorTime;
	OverlayWidget m_wLinePoint;
	TextWidget m_wEntityName;
	VerticalLayoutWidget m_wDetailsInfo;
	VerticalLayoutWidget m_wReportedInfo;

	ButtonWidget m_wReportButton;
	SCR_InputButtonComponent m_ReportButtonComponent;

	OverlayWidget m_wOverlay;
	ImageWidget m_wGlow;
	ImageWidget m_wOutlineClear;
	ImageWidget m_wOutline;
	ImageWidget m_wButtonImgGlow;
	ImageWidget m_wKeyBG;
	ImageWidget m_wDoubleTabIndicator;
	ImageWidget m_wHoldIndicator;
	ImageWidget m_wButtonImg;
	VerticalLayoutWidget m_wVerticalLayout0;
	RichTextWidget m_wButtonText;

	//------------------------------------------------------------------------------------------------
	bool Init(notnull Widget root)
	{
		m_wEntityPivot = ImageWidget.Cast(root.FindWidget("m_wEntityPivot"));
		m_wAuthorDetails = VerticalLayoutWidget.Cast(root.FindWidget("AuthorPanel.m_wAuthorDetails"));
		m_wAuthorPlatformIcon = ImageWidget.Cast(root.FindWidget("AuthorPanel.m_wAuthorDetails.HorizontalLayout0.m_wAuthorPlatformIcon"));
		m_wAuthorName = TextWidget.Cast(root.FindWidget("AuthorPanel.m_wAuthorDetails.HorizontalLayout0.AuthorNameFrame.AuthorNameWrapper.m_wAuthorName"));
		m_wAuthorTime = TextWidget.Cast(root.FindWidget("AuthorPanel.m_wAuthorDetails.TimeInfo.m_wAuthorTime"));
		m_wLinePoint = OverlayWidget.Cast(root.FindWidget("AuthorPanel.m_wAuthorDetails.m_wLinePoint"));
		m_wEntityName = TextWidget.Cast(root.FindWidget("AuthorPanel.m_wAuthorDetails.EntityNameFrame.EntityNameWrapper.m_wEntityName"));
		m_wDetailsInfo = VerticalLayoutWidget.Cast(root.FindWidget("AuthorPanel.m_wDetailsInfo"));
		m_wReportedInfo = VerticalLayoutWidget.Cast(root.FindWidget("AuthorPanel.m_wReportedInfo"));

		m_wReportButton = ButtonWidget.Cast(root.FindWidget("AuthorPanel.m_wReportButton"));
		m_ReportButtonComponent = SCR_InputButtonComponent.Cast(m_wReportButton.FindHandler(SCR_InputButtonComponent));

		m_wOverlay = OverlayWidget.Cast(root.FindWidget("AuthorPanel.m_wReportButton.HorizontalLayout1.HorizontalLayout0.InputButtonDisplayRoot.m_Overlay"));
		m_wGlow = ImageWidget.Cast(root.FindWidget("AuthorPanel.m_wReportButton.HorizontalLayout1.HorizontalLayout0.InputButtonDisplayRoot.m_Overlay.m_Glow"));
		m_wOutlineClear = ImageWidget.Cast(root.FindWidget("AuthorPanel.m_wReportButton.HorizontalLayout1.HorizontalLayout0.InputButtonDisplayRoot.m_Overlay.m_OutlineClear"));
		m_wOutline = ImageWidget.Cast(root.FindWidget("AuthorPanel.m_wReportButton.HorizontalLayout1.HorizontalLayout0.InputButtonDisplayRoot.m_Overlay.m_Outline"));
		m_wButtonImgGlow = ImageWidget.Cast(root.FindWidget("AuthorPanel.m_wReportButton.HorizontalLayout1.HorizontalLayout0.InputButtonDisplayRoot.m_Overlay.Shadow_Overlay.m_ButtonImgGlow"));
		m_wKeyBG = ImageWidget.Cast(root.FindWidget("AuthorPanel.m_wReportButton.HorizontalLayout1.HorizontalLayout0.InputButtonDisplayRoot.m_Overlay.Overlay0.m_KeyBG"));
		m_wDoubleTabIndicator = ImageWidget.Cast(root.FindWidget("AuthorPanel.m_wReportButton.HorizontalLayout1.HorizontalLayout0.InputButtonDisplayRoot.m_Overlay.Overlay0.m_DoubleTabIndicator"));
		m_wHoldIndicator = ImageWidget.Cast(root.FindWidget("AuthorPanel.m_wReportButton.HorizontalLayout1.HorizontalLayout0.InputButtonDisplayRoot.m_Overlay.Frame0.m_HoldIndicator"));
		m_wButtonImg = ImageWidget.Cast(root.FindWidget("AuthorPanel.m_wReportButton.HorizontalLayout1.HorizontalLayout0.InputButtonDisplayRoot.m_Overlay.m_ButtonImg"));
		m_wVerticalLayout0 = VerticalLayoutWidget.Cast(root.FindWidget("AuthorPanel.m_wReportButton.HorizontalLayout1.HorizontalLayout0.InputButtonDisplayRoot.m_Overlay.SizeLayout0.m_VerticalLayout0"));
		m_wButtonText = RichTextWidget.Cast(root.FindWidget("AuthorPanel.m_wReportButton.HorizontalLayout1.HorizontalLayout0.InputButtonDisplayRoot.m_Overlay.SizeLayout0.m_VerticalLayout0.m_ButtonText"));

		return true;
	}

	//------------------------------------------------------------------------------------------------
	ResourceName GetLayout()
	{
		return LAYOUT;
	}
}
