// Autogenerated by the Generate Class from Layout plugin v0.5.0
// Layout file: UI/layouts/Menus/ServerBrowser/ServerHosting/ServerHostingTabs/ServerHostingMods.layout
class SCR_ServerHostingModsWidgets
{
	protected static const ResourceName LAYOUT = "{DE4EA9E0DA35261F}UI/layouts/Menus/ServerBrowser/ServerHosting/ServerHostingTabs/ServerHostingMods.layout";

	SizeLayoutWidget m_wDisabledAddonsPanel;

	ButtonWidget m_wDeleteAllDisabled;
	SCR_ModularButtonComponent m_DeleteAllDisabledComponent0;
	SCR_DynamicIconComponent m_DeleteAllDisabledComponent1;


	ButtonWidget m_wButtonEnableAll;
	SCR_ModularButtonComponent m_ButtonEnableAllComponent0;
	SCR_DynamicIconComponent m_ButtonEnableAllComponent1;

	VerticalLayoutWidget m_wDisabledAddonsList;
	SizeLayoutWidget m_wEnabledAddonsPanel;

	ButtonWidget m_wButtonDisableAll;
	SCR_ModularButtonComponent m_ButtonDisableAllComponent0;
	SCR_DynamicIconComponent m_ButtonDisableAllComponent1;


	ButtonWidget m_wDeleteAllEnabled;
	SCR_ModularButtonComponent m_DeleteAllEnabledComponent0;
	SCR_DynamicIconComponent m_DeleteAllEnabledComponent1;

	VerticalLayoutWidget m_wEnabledAddonsList;

	//------------------------------------------------------------------------------------------------
	bool Init(Widget root)
	{
		m_wDisabledAddonsPanel = SizeLayoutWidget.Cast(root.FindWidget("HorizontalLayout0.m_DisabledAddonsPanel"));

		m_wDeleteAllDisabled = ButtonWidget.Cast(root.FindWidget("HorizontalLayout0.m_DisabledAddonsPanel.Overlay0.VerticalLayout0.TopBarHeight.TopBar.Content.HorizontalLayout0.m_DeleteAllDisabled"));
		m_DeleteAllDisabledComponent0 = SCR_ModularButtonComponent.Cast(m_wDeleteAllDisabled.FindHandler(SCR_ModularButtonComponent));
		m_DeleteAllDisabledComponent1 = SCR_DynamicIconComponent.Cast(m_wDeleteAllDisabled.FindHandler(SCR_DynamicIconComponent));


		m_wButtonEnableAll = ButtonWidget.Cast(root.FindWidget("HorizontalLayout0.m_DisabledAddonsPanel.Overlay0.VerticalLayout0.TopBarHeight.TopBar.Content.HorizontalLayout0.m_ButtonEnableAll"));
		m_ButtonEnableAllComponent0 = SCR_ModularButtonComponent.Cast(m_wButtonEnableAll.FindHandler(SCR_ModularButtonComponent));
		m_ButtonEnableAllComponent1 = SCR_DynamicIconComponent.Cast(m_wButtonEnableAll.FindHandler(SCR_DynamicIconComponent));

		m_wDisabledAddonsList = VerticalLayoutWidget.Cast(root.FindWidget("HorizontalLayout0.m_DisabledAddonsPanel.Overlay0.VerticalLayout0.Content.Scroll.m_DisabledAddonsList"));
		m_wEnabledAddonsPanel = SizeLayoutWidget.Cast(root.FindWidget("HorizontalLayout0.m_EnabledAddonsPanel"));

		m_wButtonDisableAll = ButtonWidget.Cast(root.FindWidget("HorizontalLayout0.m_EnabledAddonsPanel.Overlay0.VerticalLayout0.TopBarHeight.TopBar.Content.HorizontalLayout0.m_ButtonDisableAll"));
		m_ButtonDisableAllComponent0 = SCR_ModularButtonComponent.Cast(m_wButtonDisableAll.FindHandler(SCR_ModularButtonComponent));
		m_ButtonDisableAllComponent1 = SCR_DynamicIconComponent.Cast(m_wButtonDisableAll.FindHandler(SCR_DynamicIconComponent));


		m_wDeleteAllEnabled = ButtonWidget.Cast(root.FindWidget("HorizontalLayout0.m_EnabledAddonsPanel.Overlay0.VerticalLayout0.TopBarHeight.TopBar.Content.HorizontalLayout0.m_DeleteAllEnabled"));
		m_DeleteAllEnabledComponent0 = SCR_ModularButtonComponent.Cast(m_wDeleteAllEnabled.FindHandler(SCR_ModularButtonComponent));
		m_DeleteAllEnabledComponent1 = SCR_DynamicIconComponent.Cast(m_wDeleteAllEnabled.FindHandler(SCR_DynamicIconComponent));

		m_wEnabledAddonsList = VerticalLayoutWidget.Cast(root.FindWidget("HorizontalLayout0.m_EnabledAddonsPanel.Overlay0.VerticalLayout0.Content.Scroll.m_EnabledAddonsList"));

		return true;
	}

	//------------------------------------------------------------------------------------------------
	ResourceName GetLayout()
	{
		return LAYOUT;
	}
}
