// Autogenerated by the Generate Class from Layout plugin v0.5.1
// Layout file: UI/layouts/MANW2025/MANW_RankLabel.layout
class SCR_MANW_RankLabelWidgets
{
	protected static const ResourceName LAYOUT = "{7680AB084DD35661}UI/layouts/MANW2025/MANW_RankLabel.layout";

	ImageWidget m_wRankIcon;
	TextWidget m_wCategoryText;

	//------------------------------------------------------------------------------------------------
	bool Init(notnull Widget root)
	{
		m_wRankIcon = ImageWidget.Cast(root.FindWidget("Overlay0.HorizontalLayout0.m_wRankIcon"));
		m_wCategoryText = TextWidget.Cast(root.FindWidget("Overlay0.HorizontalLayout0.m_wCategoryText"));

		return true;
	}

	//------------------------------------------------------------------------------------------------
	ResourceName GetLayout()
	{
		return LAYOUT;
	}
}
